Return-Path: info@firstnaukri.com
Received: from mx99.stngva01.us.mxservers.net (198.173.112.36)
	by mail19f.g19.rapidsite.net (RS ver 1.0.95vs) with SMTP id 1-0499755581
	for <jayanthi@altechstar.com>; Tue, 28 Sep 2010 13:39:41 -0400 (EDT)
Received: from unknown [198.64.159.76] (EHLO m7.naukri.com)
	by va1-mx99.stngva01.us.mxservers.net (mxl_mta-3.1.0-05)
	with ESMTP id d5822ac4.2631838624.35226.00-033.va1-mx99.stngva01.us.mxservers.net (envelope-from <info@firstnaukri.com>);
	Tue, 28 Sep 2010 13:39:41 -0400 (EDT)
Return-Path: <info@firstnaukri.com>
Received: from [127.0.0.1] ([127.0.0.1:30701] helo=localhost.localdomain)
	by m7.naukri.com (envelope-from <info@firstnaukri.com>)
	(ecelerity 3.0.19.34928 r(34928)) with ESMTP
	id 9D/8D-02858-D5822AC4; Tue, 28 Sep 2010 23:09:41 +0530
Date: Tue, 28 Sep 2010 23:09:41 +0530
To: "jayanthi@altechstar.com" <jayanthi@altechstar.com>
From: First Naukri <info@firstnaukri.com>
Subject: Hiring from campuses made simple
Message-ID: <35842ce14519c29b6e94fd9ed4706559@localhost.localdomain>
X-Priority: 3
X-Mailer: PHPMailer 5.1 (phpmailer.sourceforge.net)
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
Precedence: bulk
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: text/html; charset=us-ascii; charset="iso-8859-1"
X-Processed-By: Rebuild v2.0-0
X-Spam: [F=0.2000000000; B=0.500(0); S=0.200(2010073001); MH=0.500(2010092825)]
X-MAIL-FROM: <info@firstnaukri.com>
X-SOURCE-IP: [198.64.159.76]
X-SF-Loop: 1

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<title>Firstnaukri.com</title>
</head>

<body><table align="center" cellpadding="0" cellspacing="0" border="0" width="600"> <tr><td height="25" align="center" valign="middle"><div align="center"><font color="#CC0000"></font><a target="_blank" href="http://w10.naukri.com/mailers/campus_hiring_14sep10/index.html">Use this link, if unable to view the page</a></div></td></tr></table>
<table bgcolor="#e7eaeb" align="center" style="border:1px solid #ebebeb;" cellpadding="0" cellspacing="0" border="0" width="600">
  <tr bgcolor="#ffffff"><td></td><td style="border-bottom:1px solid #ccd1d3;" width="39"></td><td style="border-bottom:1px solid #ccd1d3;" height="10"></td><td style="border-bottom:1px solid #ccd1d3;" width="38"></td><td></td></tr>
  <tr>
  	<td bgcolor="#ffffff" style="border-right:1px solid #ccd1d3;" width="10" rowspan="10"></td>
    <td></td>

    <td valign="bottom" height="76"><div style="font-family:Arial, Helvetica; font-size:14px; color:#535050; text-align:right; line-height:30px;"><a target="_blank" href="http://www.naukri.com/"><img style="color:#000000; font-size:16px;" align="left" border="0" vspace="0" hspace="0" height="62" width="248" alt="Naukri.com" src="http://w10.naukri.com/mailers/campus_hiring_14sep10/gifs/logo.gif"></a>a <a style="color:#535050; text-decoration:none;" target="_blank" href="http://www.naukri.com/">naukri.com</a> venture</div></td>
    <td></td>
	<td bgcolor="#ffffff" style="border-left:1px solid #ccd1d3;" width="10" rowspan="10"></td>
  </tr>
  <tr><td></td><td height="30"></td><td></td></tr>
  <tr>
    <td></td>

    <td><table align="center" cellpadding="0" cellspacing="0" border="0" width="414">
        <tr>
        <td align="right" width="414"><div style="font-family:Verdana, Arial; font-size:22px; color:#000000;">Our UNIQUE SOLUTIONS</div></td>
        </tr>
        </table></td>
    <td></td>
  </tr>
  <tr><td></td><td><img hspace="0" vspace="0" src="http://w10.naukri.com/mailers/campus_hiring_14sep10/gifs/img2.gif"></td><td></td></tr>

  <tr>
    <td></td>
    <td><div style="font-family:Arial, Helvetica, sans-serif; font-size:13px; color:#232424">At <b>Naukri.com,</b> we understand that hiring freshers from campuses has unique requirements. For most of you, it is a tedious & costly process requiring high bandwidth from your end for visiting multiple campuses, short listing candidates and then interviewing them. But not anymore!
</div></td>
    <td></td>
  </tr>
  <tr><td></td><td height="26"></td><td></td></tr>

  <tr>
    <td></td>
    <td><div style="font-family:Arial, Helvetica, sans-serif; font-size:13px; color:#232424">With our new campus hiring website, <b>Firstnaukri.com</b>, you can now reduce hiring costs and manage fresher hiring efficiently. Check out our unique features, designed keeping in mind your campus hiring requirements:</div></td>
    <td></td>
  </tr>
  <tr><td></td><td height="40"></td><td></td></tr>
  <tr>

    <td></td>
    <td><table background="http://w10.naukri.com/mailers/campus_hiring_14sep10/gifs/button.gif" bgcolor="#387fd4" cellspacing="0" cellpadding="0" align="center" border="0" height="38" width="381">
      <tr>
        <td align="center"><div style="font-family:Arial, Helvetica, sans-serif; font-size:17px; color:#ffffff"><b><a style="color:#ffffff; text-decoration:none;" target="_blank" href="http://www.naukri.com/tieups/tieups.php?othersrcp=10929">Here's how we help you in hiring freshers?</a></b></div></td>
      </tr>
    </table></td>
    <td></td>
  </tr>

  <tr><td></td><td height="41"></td><td></td></tr>
  <tr bgcolor="#FFFFFF"><td></td><td style="border-top:1px solid #ccd1d3;"></td><td style="border-top:1px solid #ccd1d3;" height="10"></td><td style="border-top:1px solid #ccd1d3;"></td><td></td></tr></table>

<br><br>
<TABLE ALIGN="CENTER"><TR><TD ALIGN="CENTER"><DIV ALIGN="CENTER">We are sending this mail as you have registered with Firstnaukri.com. </DIV></TD></TR></TABLE><br><br><IMG border="0" height="0" width="0" src="http://portal.mxlogic.com/images/transparent.gif"><INPUT VALUE="<?=jayanthi@altechstar.com?>" NAME="hid_email" TYPE="hidden"></BODY>
<script type="text/JavaScript" language="JavaScript">
                if(navigator.appName == "Microsoft Internet Explorer")
                {
                        document.getElementById('id_brwsr').innerHTML="<center>"+document.getElementById('ID').innerHTML;
                }
                else
                {
                        document.getElementById('id_brwsr').innerHTML="<br><center>"+document.getElementById('ID').innerHTML;
                }
        </script></html>


