Return-Path: jitender.karira@yahoo.com
Received: from mx51.stngva01.us.mxservers.net (204.202.242.110)
	by mail19b.g19.rapidsite.net (RS ver 1.0.95vs) with SMTP id 4-020336979
	for <jayanthi@altechstar.com>; Fri, 21 Jan 2011 22:29:39 -0500 (EST)
Received: from unknown [121.101.151.224] (HELO nm2.bullet.mail.in.yahoo.com)
	by va1-mx51.stngva01.us.mxservers.net (mxl_mta-3.1.0-05)
	with SMTP id 12f4a3d4.2329934752.169903.00-008.va1-mx51.stngva01.us.mxservers.net (envelope-from <jitender.karira@yahoo.com>);
	Fri, 21 Jan 2011 22:29:37 -0500 (EST)
Received: from [121.101.151.238] by nm2.bullet.mail.in.yahoo.com with NNFMP; 22 Jan 2011 03:29:31 -0000
Received: from [121.101.151.234] by tm3.bullet.mail.in.yahoo.com with NNFMP; 22 Jan 2011 03:29:39 -0000
Received: from [127.0.0.1] by omp1003.mail.in.yahoo.com with NNFMP; 22 Jan 2011 03:29:32 -0000
X-Yahoo-Newman-Property: ymail-3
X-Yahoo-Newman-Id: 910896.64002.bm@omp1003.mail.in.yahoo.com
Received: (qmail 73315 invoked by uid 60001); 22 Jan 2011 03:29:30 -0000
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=yahoo.com; s=s1024; t=1295666970; bh=tvL/9Bu8W2P226aVD9eM0VbuufzUdOoPIpP3cLjT5xw=; h=Message-ID:X-YMail-OSG:Received:X-Mailer:Date:From:Subject:To:MIME-Version:Content-Type; b=eLIz+gqTTyK/mvtAaqGyfOyLU0cvsxqZGdS0jVjbid3Dod4CLPAyqvQmfLaAW5eorpqoayTkpvh7Pjs10BxILIms/zahp6dVfDe/GLZyHMHndRM37T+yT+NShDJKJwjTjPsilv9B+OyOWsxc780MJ8kh4EMikiRdBdYcqm5MksY=
DomainKey-Signature:a=rsa-sha1; q=dns; c=nofws;
  s=s1024; d=yahoo.com;
  h=Message-ID:X-YMail-OSG:Received:X-Mailer:Date:From:Subject:To:MIME-Version:Content-Type;
  b=Qp7s8IZk00aJVlf+Fxfl4K9azt48BFyn0VNzW27ahk9M3ekr7RzxEScHDdGc3dLv0wNlyKIeYE69LKyJqWG8UoQqwEOdvCujnFNAKiOBpCO5t/36YgjjyF87tUbVFRhg5Esl0UyzSedDSc0QjlUl0crjn1eRibEKzMeAVO31WDk=;
Message-ID: <344362.73308.qm@web95706.mail.in.yahoo.com>
X-YMail-OSG: 5AxTbo0VM1mK1oklsLVxCZEnmz_2lL_5yS5.Q6ay0a1x5Zt
 j9xHPpT0Tof2m22tbi9HocDf2N5el.R.rvnHto6zHbl.WuJ2JtH3iovgKPXx
 JJQcx9fpdBPx6lqmgW02.Wc_TpN8FAhlKuIgxe50uwdn6GHNzPUaLuFoIfvd
 FYjNsDSJCFGBq1bAyr8Cn8ljEp2mDdZASxthr4Ip.ivEZDMn1fH27Mpmu4Aj
 1P74RcxrAUmVGQhBPDcRU7Tkov7V8gXydewXITDkMx6nCfaAXRp0GMK_Tgy3
 ec.zoI_4kjhOg45sWlvVafhR0iw3zmRXkXTI0yIEFmraBMoE0UaqFVUwK8SK
 rt6GknvE._tnGhmiPEfuepPaa.LKCKdLIHGSHO_kJrC48j8nvQK5aLsnQCXw
 uO47e9FgyKAI8nBsgMYWuzY03a.DmoIwr0zBHyESDFeIN0LBZ4MyYeBeFgi9
 ZJmOAwV54Ae38_JEQCPnOsFB8KOz3F6b4MnfVPPlMr5fDIO52JTrUK1DNr9w
 ncA--
Received: from [111.119.207.58] by web95706.mail.in.yahoo.com via HTTP; Sat, 22 Jan 2011 08:59:29 IST
X-Mailer: YahooMailClassic/11.4.20 YahooMailWebService/0.8.107.285259
Date: Sat, 22 Jan 2011 08:59:29 +0530 (IST)
From: Jitender Karira <jitender.karira@yahoo.com>
Subject: Resume - Microsoft certified in .Net version 3.5
To: undisclosed recipients: ;
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="0-1837947753-1295666969=:73308"
X-Spam: [F=0.2000000000; B=0.500(0); S=0.200(2010122901); MH=0.500(2011012133)]
X-MAIL-FROM: <jitender.karira@yahoo.com>
X-SOURCE-IP: [121.101.151.224]
To:undisclosed-recipients:;
X-SF-Loop: 1

--0-1837947753-1295666969=:73308
Content-Type: multipart/alternative; boundary="0-1525914780-1295666969=:73308"

--0-1525914780-1295666969=:73308
Content-Type: text/plain; charset=iso-8859-1
Content-Transfer-Encoding: quoted-printable









Jitendra M. Karira
Phone: +91 9970308630, +91 9820288794=20
E-Mail: j2karira@yahoo.com=A0=A0=20
=A0=20

=A0=20
Dear Recruiter,=20
=A0=20
=A0=20
It was with great interest that I read your recent posting in the job porta=
l for the position of Dotnet software developer. Review of my credentials w=
ill confirm that I am capable of serving as a catalyst for achieving revenu=
e objectives and organic growth through effective contributions.=20
=A0=20
=A0=20
I have completed Bachelors of engineering(computers) from RAIT, Nerul, Univ=
ersity of Mumbai. I am also Microsoft certified MCPD in VB.Net 3.5.=20
=A0=20
=A0=20
In addition, I offer excellent organizational skills, which have proven to =
be a critical asset in driving operations during the current associations. =
These qualities, combined with my dedication and tireless work ethic, shoul=
d enable me to make a positive impact at your organization.=20
=A0=20
=A0=20
Enclosed is a copy of my resume for your review. I would welcome an opportu=
nity to discuss your needs and objectives and the possibility of working to=
gether to meet them. Thank you for your time and consideration.=20
=A0=20
=A0=20
Yours sincerely,=20
=A0=20
Jitendra M. Karira=20
=A0=20
Enclosure: Resume=20
=A0=20
=A0=20
=A0=20
=A0=20
=A0=20
=A0=20
=A0=20
=A0=20
=A0=20
=A0=20
=A0=20
=A0=20
=A0=20
=A0=20
=A0=20
=A0=20
=A0=20
=A0
=0A=0A
--0-1525914780-1295666969=:73308
Content-Type: text/html; charset=iso-8859-1
Content-Transfer-Encoding: quoted-printable

<table cellspacing=3D"0" cellpadding=3D"0" border=3D"0" ><tr><td valign=3D"=
top" style=3D"font: inherit;"><BLOCKQUOTE style=3D"PADDING-LEFT: 5px; MARGI=
N-LEFT: 5px; BORDER-LEFT: rgb(16,16,255) 2px solid"><BR>
<DIV id=3Dyiv1455658011>
<TABLE cellSpacing=3D0 cellPadding=3D0 border=3D0>
<TBODY>
<TR>
<TD vAlign=3Dtop>
<DIV style=3D"BORDER-RIGHT: medium none; PADDING-RIGHT: 0cm; BORDER-TOP: me=
dium none; PADDING-LEFT: 0cm; PADDING-BOTTOM: 1pt; BORDER-LEFT: medium none=
; PADDING-TOP: 0cm; BORDER-BOTTOM: windowtext 1.5pt double">
<P class=3Dyiv1455658011MsoNormal style=3D"BORDER-RIGHT: medium none; PADDI=
NG-RIGHT: 0cm; BORDER-TOP: medium none; PADDING-LEFT: 0cm; PADDING-BOTTOM: =
0cm; MARGIN: 0cm 0cm 0pt; BORDER-LEFT: medium none; PADDING-TOP: 0cm; BORDE=
R-BOTTOM: medium none; TEXT-ALIGN: justify"><B><SPAN style=3D"FONT-FAMILY: =
'sans-serif'"><FONT size=3D3>Jitendra M. Karira</FONT></SPAN></B></DIV></DI=
V>
<P class=3Dyiv1455658011MsoNormal style=3D"BORDER-RIGHT: medium none; PADDI=
NG-RIGHT: 0cm; BORDER-TOP: medium none; PADDING-LEFT: 0cm; PADDING-BOTTOM: =
0cm; MARGIN: 0cm 0cm 0pt; BORDER-LEFT: medium none; PADDING-TOP: 0cm; BORDE=
R-BOTTOM: medium none; TEXT-ALIGN: justify"><B><SPAN style=3D"FONT-SIZE: 9p=
t; FONT-FAMILY: 'sans-serif'">Phone: +91 <SPAN>9970308630, +91 9820288794</=
SPAN></SPAN></B>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BORDER-RIGHT: medium none; PADDI=
NG-RIGHT: 0cm; BORDER-TOP: medium none; PADDING-LEFT: 0cm; PADDING-BOTTOM: =
0cm; MARGIN: 0cm 0cm 0pt; BORDER-LEFT: medium none; PADDING-TOP: 0cm; BORDE=
R-BOTTOM: medium none; TEXT-ALIGN: justify"><B><SPAN style=3D"FONT-SIZE: 9p=
t; FONT-FAMILY: 'sans-serif'">E-Mail: j2karira<SPAN>@yahoo.com<SPAN>&nbsp;&=
nbsp; </SPAN></SPAN></SPAN></B>
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify">
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; CO=
LOR: blue; FONT-FAMILY: 'sans-serif'"></SPAN><SPAN lang=3DEN-US style=3D"FO=
NT-SIZE: 9pt; FONT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">Dear Recruiter,</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">It was with great interest that I read your recent=
 posting in the job portal for the position of Dotnet software developer. R=
eview of my credentials will confirm that I am capable of serving as a cata=
lyst for achieving revenue objectives and organic growth through effective =
contributions.</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><B><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt;=
 FONT-FAMILY: 'sans-serif'">&nbsp;</SPAN></B>=20
<P class=3Dyiv1455658011MsoNormal style=3D"MARGIN: 0cm 0cm 0pt; TEXT-ALIGN:=
 justify"><B><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FONT-FAMILY: 'sans=
-serif'">I have completed Bachelors of engineering(computers)</SPAN></B><B>=
<SPAN style=3D"FONT-SIZE: 9pt; FONT-FAMILY: 'sans-serif'"> from RAIT, Nerul=
, University of Mumbai. I am also Microsoft certified MCPD in VB.Net 3.5.</=
SPAN></B>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; CO=
LOR: black; FONT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoBodyText style=3D"BACKGROUND: white; MARGIN: 0cm=
 0cm 0pt; LINE-HEIGHT: normal"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; =
COLOR: black; FONT-FAMILY: 'sans-serif'">In addition, I offer excellent org=
anizational skills, which have proven to be a critical asset in driving ope=
rations during the current associations. These qualities, combined with my =
dedication and tireless work ethic, should enable me to make a positive imp=
act at your organization.</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoBodyText style=3D"BACKGROUND: white; MARGIN: 0cm=
 0cm 0pt; LINE-HEIGHT: normal"><SPAN style=3D"FONT-SIZE: 9pt; FONT-FAMILY: =
'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoBodyText style=3D"BACKGROUND: white; MARGIN: 0cm=
 0cm 0pt; LINE-HEIGHT: normal"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; =
FONT-FAMILY: 'sans-serif'">Enclosed is a copy of my resume for your review.=
 I would welcome an opportunity to discuss your needs and objectives and th=
e possibility of working together to meet them. Thank you for your time and=
 consideration.</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">Yours sincerely,</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"MARGIN: 0cm 0cm 0pt; TEXT-ALIGN:=
 justify"><B><SPAN style=3D"FONT-SIZE: 9pt; FONT-FAMILY: 'sans-serif'">Jite=
ndra M. Karira</SPAN></B>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">Enclosure: Resume</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN>=20
<P class=3Dyiv1455658011MsoNormal style=3D"BACKGROUND: white; MARGIN: 0cm 0=
cm 0pt; TEXT-ALIGN: justify"><SPAN lang=3DEN-US style=3D"FONT-SIZE: 9pt; FO=
NT-FAMILY: 'sans-serif'">&nbsp;</SPAN></DIV></TD></TR></TBODY></TABLE><BR><=
/DIV></BLOCKQUOTE></td></tr></table><br>
--0-1525914780-1295666969=:73308--
--0-1837947753-1295666969=:73308
Content-Type: application/msword; name="CV-JMKarira1.doc"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="CV-JMKarira1.doc"

0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAPgADAP7/CQAGAAAAAAAAAAAAAAAB
AAAAWQAAAAAAAAAAEAAAWwAAAAEAAAD+////AAAAAFgAAAD/////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
///////////////////////spcEAW4AJBAAA8BK/AAAAAAAAEAAAAAAACAAA
2hIAAA4AYmpiaqz6rPoAAAAAAAAAAAAAAAAAAAAAAAAJBBYAgDgAAM6QAQDO
kAEA2goAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//w8AAAAAAAAA
AAD//w8AAAAAAAAAAAD//w8AAAAAAAAAAAAAAAAAAAAAALcAAAAAAMoGAAAA
AAAAygYAAA0UAAAAAAAADRQAAAAAAAANFAAAAAAAAA0UAAAAAAAADRQAABQA
AAAAAAAAAAAAAP////8AAAAAIRQAAAAAAAAhFAAAAAAAACEUAAAAAAAAIRQA
AGwAAACNFAAALAAAACEUAAAAAAAA8j4AAC4CAAC5FAAAAAAAALkUAAAAAAAA
uRQAAAAAAAC5FAAAAAAAALkUAAAAAAAAlBUAAAAAAACUFQAAAAAAAJQVAAAA
AAAAcT4AAAIAAABzPgAAAAAAAHM+AAAAAAAAcz4AAAAAAABzPgAAAAAAAHM+
AAAAAAAAcz4AACQAAAAgQQAAogIAAMJDAABWAAAAlz4AABUAAAAAAAAAAAAA
AAAAAAAAAAAADRQAAAAAAAB3FgAAAAAAAAAAAAAAAAAAAAAAAAAAAACUFQAA
AAAAAJQVAAAAAAAAdxYAAAAAAAB3FgAAAAAAAJc+AAAAAAAAAAAAAAAAAAAN
FAAAAAAAAA0UAAAAAAAAuRQAAAAAAAAAAAAAAAAAALkUAADbAAAArD4AABYA
AADdFwAAAAAAAN0XAAAAAAAA3RcAAAAAAAB3FgAAfAAAAA0UAAAAAAAAuRQA
AAAAAAANFAAAAAAAALkUAAAAAAAAcT4AAAAAAAAAAAAAAAAAAN0XAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAdxYAAAAAAABxPgAAAAAAAAAAAAAAAAAA3RcAAAAAAADdFwAAbgEAADE5
AAAIAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATT0AAAAAAAC5FAAA
AAAAAP////8AAAAAEAF6tBKuywEAAAAAAAAAACEUAAAAAAAA8xYAAF4AAAA5
OwAAIAAAAAAAAAAAAAAAXT4AABQAAADCPgAAMAAAAPI+AAAAAAAAWTsAAPQB
AAAYRAAAAAAAAFEXAABGAAAAGEQAAEAAAABNPQAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAABNPQAAOAAAABhEAAAAAAAAAAAAAAAAAAANFAAAAAAAAIU9AADY
AAAAlBUAACIAAAC2FQAAGAAAAN0XAAAAAAAAzhUAABQAAADiFQAAlQAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlBUAAAAAAACUFQAAAAAA
AJQVAAAAAAAAlz4AAAAAAACXPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAlxcAAEYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAJQVAAAAAAAAlBUAAAAAAACUFQAAAAAAAPI+AAAAAAAAdxYAAAAA
AAB3FgAAAAAAAHcWAAAAAAAAdxYAAAAAAAAAAAAAAAAAAP////8AAAAA////
/wAAAAD/////AAAAAAAAAAAAAAAA/////wAAAAD/////AAAAAP////8AAAAA
/////wAAAAD/////AAAAAP////8AAAAA/////wAAAAD/////AAAAAP////8A
AAAA/////wAAAAD/////AAAAAP////8AAAAA/////wAAAAD/////AAAAABhE
AAAAAAAAlBUAAAAAAACUFQAAAAAAAJQVAAAAAAAAlBUAAAAAAACUFQAAAAAA
AJQVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAACUFQAAAAAAAJQVAAAAAAAAlBUAAAAAAADK
BgAACQwAANMSAAA6AQAABQASAQAACQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEppdGVu
ZHJhIE0uIEthcmlyYQ1QaG9uZTogKzkxIDk5NzAzMDg2MzAgfHwgRS1NYWls
OiBqMmthcmlyYUB5YWhvby5jb20gICANDVNlZWtpbmcgY2hhbGxlbmdpbmcg
YXNzaWdubWVudHMgaW4gU29mdHdhcmUgZGV2ZWxvcG1lbnQvSVQgSW5kdXN0
cnkgd2l0aCBncm93dGggb3JpZW50ZWQgb3JnYW5pc2F0aW9uLiANDUxvY2F0
aW9uIFByZWZlcmVuY2U6IE11bWJhaSwgUHVuZSwgQmFuZ2Fsb3JlLCBVU0Es
IFVLLCBDYW5hZGEsIEF1c3RyYWxpYSANDVByb2Zlc3Npb25hbCBTbmFwc2hv
dA1CYWNoZWxvcnMgb2YgRW5naW5lZXJpbmcgKENvbXB1dGVycykgZnJvbSBS
QUlULCBOZXJ1bCwgVW5pdmVyc2l0eSBvZiBNdW1iYWkuIA1BY3F1aXJlZCBr
bm93bGVkZ2Ugb2YgbmV3IG1ldGhvZHMgJiBpbmR1c3RyeSB0cmVuZHMgd2hp
bGUgdW5kZXJ0YWtpbmcgcHJvamVjdHMuDSBFZmZpY2llbnQgJiBtZXRob2Rp
Y2FsIGluIGhhbmRsaW5nIGFzc2lnbmVkIHRhc2tzLg1Qb3NzZXNzIGV4Y2Vs
bGVudCBudW1lcmljYWwgJiBhbmFseXRpY2FsIGFiaWxpdGllcy4NRGV0YWls
LW9yaWVudGVkIHdpdGggYW4gYW5hbHl0aWNhbCBiZW50IG9mIG1pbmQgYW5k
IHBvc2l0aXZlIGF0dGl0dWRlLg1DYXBhYmxlIG9mIGdyYXNwaW5nIG5ldyB0
ZWNobmljYWwgY29uY2VwdHMgcXVpY2tseSBhbmQgdXRpbGl6aW5nIHRoZW0g
aW4gYSBwcm9kdWN0aXZlIG1hbm5lci4NQW4gZWZmZWN0aXZlIGNvbW11bmlj
YXRvciB3aXRoIHN0cm9uZyBpbnRlcnBlcnNvbmFsIGFuZCBwcm9ibGVtLXNv
bHZpbmcgc2tpbGxzLg0NQWNhZGVtaWENDUJhY2hlbG9ycyBvZiBFbmdpbmVl
cmluZyAoQ29tcHV0ZXJzKSBmcm9tIFJBSVQsIE5lcnVsLCBVbml2ZXJzaXR5
IG9mIE11bWJhaSBpbiAyMDEwLg0NSFNDIChTY2llbmNlKSBmcm9tIE5hdGlv
bmFsIENvbGxlZ2UsIE11bWJhaSBCb2FyZCBpbiAyMDAzLg0NU1NDIGZyb20g
U3JpIFNhdHlhIFNhaSBIaWdoIFNjaG9vbCwgTXVtYmFpIEJvYXJkIGluIDIw
MDEuIA0NSVQgU2tpbGxzOiBDLCBDKyssIERCTVMsIFNRTCBzZXJ2ZXIgMjAw
OCwgLk5ldCBmcmFtZXdvcmsgMy41LCBWQi5OZXQgMy41Lg0NQ2VydGlmaWNh
dGlvbg0NTWlzY3Jvc29mdCBDZXJ0aWZpY2F0aW9uIJYgTUNQRCBpbiBWQi5u
ZXQgMy41IGluIDIwMTAuDQ1Qcm9mZXNzaW9uYWwgRW5oYW5jZW1lbnQgDQ1P
bmxpbmUgSGFuZHdyaXR0ZW4gQ2hhcmFjdGVyIFJlY29nbml0aW9uOiAJCQ1U
b3BpYzoJCQlPbmxpbmUgSGFuZHdyaXR0ZW4gQ2hhcmFjdGVyIFJlY29nbml0
aW9uDVN5bm9wc2lzOgkJRmluYWwgWWVhciBCLkUgUHJvamVjdDogUmVzZWFy
Y2ggb24gT25saW5lIEhhbmR3cml0dGVuIENoYXJhY3RlciBSZWNvZ25pdGlv
bi4NSW4gT0hDUiB3YXMgZGl2aWRlZCBpbnRvIDQgbW9kdWxlczoNSW50ZXJm
YWNpbmcgb2YgdGhlIERpZ2l0aXplciANR2VuZXJhdGlvbiBvZiB0aGUgQ2hh
cmFjdGVyDVJlY29nbml0aW9uIG9mIHRoZSBDaGFyYWN0ZXINUG9zdCBwcm9j
ZXNzaW5nIChBZGRpdGlvbmFsIEZlYXR1cmUgb2YgQ29ycmVjdGlvbiBhbmQg
RGljdGlvbmFyeSkNU29mdHdhcmUgdXNlZDoNTWljcm9zb2Z0IE9mZmljZSAy
MDA3Lg1NaWNyb3NvZnQgVmlzdWFsIFN0dWRpbyAyMDA4Lg1NaWNyb3NvZnQg
U1FMIHNlcnZlciAyMDA4Lg1NcyBUdXJibyBDLg0NDQ0NS2V5IHJlc3BvbnNp
YmlsaXRpZXM6DUludGVyYWN0aW5nIHdpdGggdXNlciBmb3IgcmVxdWlyZW1l
bnQgZ2F0aGVyaW5nLCBzeXN0ZW0gc3R1ZHkgJiBhbmFseXNpcy4NVW5kZXJz
dGFuZGluZyB0ZWNobmljYWwgJiBmdW5jdGlvbmFsIHNwZWNpZmljYXRpb25z
Lg1JbXBsZW1lbnRpbmcgcHJvamVjdCBwbGFuIHdpdGggZGVhZGxpbmVzLg1E
ZXNpZ25pbmcgJiBkZXZlbG9waW5nIGNvZGUsIHRlc3RpbmcsIGRlYnVnZ2lu
ZyAmIHRyb3VibGUgc2hvb3RpbmcuDURlcGxveWluZyB0aGUgc29mdHdhcmUg
YXBwbGljYXRpb24gb24gZGVza3RvcC4NDUJleW9uZCBDdXJyaWN1bHVtIA0g
TWVtYmVyIG9mIENvbXB1dGVyIFNvY2lldHkgT2YgSW5kaWEgKENTSSkgaW4g
Q29sbGVnZS4NV29ya2VkIGFzIHRoZSBFdmVudCBDb29yZGluYXRvciBmb3Ig
dGhlIGV2ZW50IG9mIExBTiBHYW1pbmcgaGVsZCBieSBDU0ktUkFJVC4NT3Jn
YW5pc2VkIHZhcmlvdXMgZ3JvdXAgZXZlbnRzIGFuZCB0cmlwcy4NUGFydGlj
aXBhdGVkIGluIHZhcmlvdXMgTWF0aHMgJiBTY2llbmNlIHF1aXouDQ1QZXJz
b25hbCBEb3NzaWVyDURhdGUgb2YgQmlydGg6CQkybmQgRmVicnVhcnkgMTk4
NA1MYW5ndWFnZToJCUVuZ2xpc2gsIEhpbmRpLCBhbmQgU2luZGhpLg1Ib2Ji
aWVzOgkJTmV0IHN1cmZpbmcsIHdhdGNoaW5nIE5hdGlvbmFsIGdlb2dyYXBo
aWMgJiBEaXNjb3ZlcnkgY2hhbm5lbHMsIFJlYWRpbmcuDVBlcm1hbmVudCBB
ZGRyZXNzOglCbG9jay1BIDIxMiAvIDQyNCwgRGV2IFNhbWFqIFJvYWQsIE5l
dGFqaSBDaG93aywgVWxoYXNuYWdhciCWIDQyMTAwNCwNIE1haGFyYXNodHJh
Lg1DdXJyZW50IEFkZHJlc3M6CSMyMDMsIEEgV2luZywgS2luZ3N0b24gU2hh
c3RyaW5hZ2FyLCBMb2toYW5kd2FsYSwgTXVtYmFpIJYgNDAwMDUzDQkJCU1h
aGFyYXNodHJhLg0NDQ0NDQ1JIGhlcmVieSBkZWNsYXJlIHRoYXQgdGhlIGlu
Zm9ybWF0aW9uIGZ1cm5pc2hlZCBhYm92ZSBpcyB0cnVlIHRvIHRoZSBiZXN0
IG9mIG15IGtub3dsZWRnZSBhbmQgaWYgeW91IGdpdmUgbWUgYW4gb3Bwb3J0
dW5pdHksIEkgd2lsbCBnaXZlIG15IGJlc3QuDQ0NDQ0NRGF0ZSA6ICAJCQkJ
CQkJCQkJSml0ZW5kcmEgTS4gS2FyaXJhLg0NDQAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAIAAASCAAAEwgAAB4IAAAoCAAAKwgAACwIAAAtCAAANAgAADwI
AAA9CAAAQggAAEkIAABKCAAAbggAAO3XxLSklIHEtG1cbUkzAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAACoVaLRpTgAWaJN4CAA1CIFDShQAT0oDAFFK
AwBcCIFhShQAbUgJCHNICQgAJBVotGlOABZok3gIAENKHABPSgMAUUoDAGFK
HABtSAkIc0gJCAAhFmhxQNsAQ0oUAE9KAwBRSgMAXAiBYUoUAG1ICQhzSAkI
JxVotGlOABZok3gIAENKFABPSgMAUUoDAFwIgWFKFABtSAkIc0gJCCQVaLRp
TgAWaPIfvwBDShQAT0oDAFFKAwBhShQAbUgJCHNICQgAHhZo8h+/AENKFABP
SgMAUUoDAGFKFABtSAkIc0gJCAAeFmjcfPUAQ0oUAE9KAwBRSgMAYUoUAG1I
CQhzSAkIAB4WaHFA2wBDShQAT0oDAFFKAwBhShQAbUgJCHNICQgAJBVotGlO
ABZok3gIAENKFABPSgMAUUoDAGFKFABtSAkIc0gJCAAqFWi0aU4AFmiTeAgA
NQiBQ0ocAE9KAwBRSgMAXAiBYUocAG1ICQhzSAkIACQWaHFA2wA1CIFDShwA
T0oDAFFKAwBcCIFhShwAbUgJCHNICQgOAAgAABMIAABKCAAASwgAALMIAAC0
CAAA/ggAAP8IAAAVCQAAYwkAALMJAADnCQAAGwoAAGIKAADACgAAEAsAABEL
AAAaCwAAGwsAAO8AAAAAAAAAAAAAAADvAAAAAAAAAAAAAAAA6gAAAAAAAAAA
AAAAAOIAAAAAAAAAAAAAAADaAAAAAAAAAAAAAAAA4gAAAAAAAAAAAAAAAOoA
AAAAAAAAAAAAAAC5AAAAAAAAAAAAAAAArAAAAAAAAAAAAAAAAKwAAAAAAAAA
AAAAAACsAAAAAAAAAAAAAAAArAAAAAAAAAAAAAAAAKwAAAAAAAAAAAAAAACs
AAAAAAAAAAAAAAAArAAAAAAAAAAAAAAAAKIAAAAAAAAAAAAAAAC5AAAAAAAA
AAAAAAAA4gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAMkAxOkUABh
JANnZF9zlgANAAADJAMKJgALRgEAE6RQAGEkA2dkk3gIACEAAAMkASRkGBIA
ASZkGBIAAS1EAAFNxgoAAAD/5ubmAAAATsYIAAAA/xgSAQBQxggAAAD/GBIB
AGEkAWdkk3gIAAAHAAADJAFhJAFnZJQD4AAABwAAAyQBYSQBZ2STeAgAAAQA
AGdkk3gIABAAAAMkASZkBAMAAVDGCAAAAP8EAwEAYSQBZ2STeAgAABJuCAAA
jggAALMIAADVCAAA/AgAAP0IAAD+CAAA/wgAABUJAAAtCQAALwkAADgJAAA6
CQAAPwkAAO3Xwa7BmIVvXEZcRjEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAACgVaLRpTgAWaJN4CABDShQAT0oDAFFKAwBeSgIAYUoUAG1ICQhzSAkI
ACsVaLRpTgAWaJN4CAA1CIFDShQAT0oDAFFKAwBeSgIAYUoUAG1ICQhzSAkI
JRZocUDbADUIgUNKFABPSgMAUUoDAF5KAgBhShQAbUgJCHNICQgqFWi0aU4A
FmiTeAgANQiBNgiBQ0oUAE9KAwBRSgMAYUoUAG1ICQhzSAkIACQVaLRpTgAW
aJN4CABDShQAT0oDAFFKAwBhShQAbUgJCHNICQgAKhVotGlOABZolAPgADUI
gUNKFABPSgMAUUoDAFwIgWFKFABtSAkIc0gJCAAkFmhxQNsANgiBQ0oUAE9K
AwBRSgMAXAiBYUoUAG1ICQhzSAkIACoVaLRpTgAWaJQD4AA2CIFDShQAT0oD
AFFKAwBcCIFhShQAbUgJCHNICQgAKhVotGlOABZok3gIADUIgUNKFABPSgMA
UUoDAFwIgWFKFABtSAkIc0gJCAAkFmhxQNsANQiBQ0oUAE9KAwBRSgMAXAiB
YUoUAG1ICQhzSAkIDT8JAABDCQAARQkAAEoJAABaCQAAYAkAAGIJAABjCQAA
fQkAAJYJAACyCQAAswkAALUJAADKCQAA+QkAAA8KAAAaCgAAGwoAADMKAABg
CgAAjQoAAL4KAADACgAAzAoAABELAADu2e7Z7tnDsJywjHtnV2dXRLCcsJyw
nLAAAAAAAAAAAAAAAAAkFWi0aU4AFmgdMbgAQ0oUAE9KAwBRSgMAYUoUAG1I
CQhzSAkIAB4WaB0xuABDShQAT0oDAFFKAwBhShQAbUgJCHNICQgAJxVosS4k
ABZoHTG4ADUIgUNKFABPSgMAUUoDAGFKFABtSAkIc0gJCCEWaP0UHgA1CIFD
ShQAT0oDAFFKAwBhShQAbUgJCHNICQgeFmiTeAgAQ0oUAE9KAwBRSgMAYUoU
AG1ICQhzSAkIACcVaLEuJAAWaJN4CAA1CIFDShQAT0oDAFFKAwBhShQAbUgJ
CHNICQgkFWi0aU4AFmiTeAgAQ0oUAE9KAwBRSgMAYUoUAG1ICQhzSAkIACsV
aLRpTgAWaJN4CAA1CIFDShQAT0oDAFFKAwBeSgIAYUoUAG1ICQhzSAkIKBVo
tGlOABZok3gIAENKFABPSgMAUUoDAF5KAgBhShQAbUgJCHNICQgAIhZocUDb
AENKFABPSgMAUUoDAF5KAgBhShQAbUgJCHNICQgYEQsAABoLAAAbCwAAMwsA
ADULAAA+CwAAQAsAAEULAABJCwAASwsAAFALAABgCwAAZgsAAGwLAABtCwAA
cQsAAHULAAB2CwAAfQsAAH8LAACECwAAjQsAAJ0LAACiCwAAqQsAAKoLAACs
CwAArQsAAOrWw63DrZiGmIaYhpiGmHXWddZiUmJSYlJi6gAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAeFmhxQNsAQ0oUAE9KAwBRSgMAYUoUAG1ICQhzSAkI
ACQVaLRpTgAWaJN4CABDShQAT0oDAFFKAwBhShQAbUgJCHNICQgAIRZocUDb
ADUIgUNKFABPSgMAUUoDAGFKFABtSAkIc0gJCCIWaHFA2wBDShQAT0oDAFFK
AwBeSgIAYUoUAG1ICQhzSAkIACgVaLRpTgAWaJN4CABDShQAT0oDAFFKAwBe
SgIAYUoUAG1ICQhzSAkIACsVaLRpTgAWaJN4CAA1CIFDShQAT0oDAFFKAwBe
SgIAYUoUAG1ICQhzSAkIJRZocUDbADUIgUNKFABPSgMAUUoDAF5KAgBhShQA
bUgJCHNICQgnFWi0aU4AFmiTeAgANQiBQ0oUAE9KAwBRSgMAYUoUAG1ICQhz
SAkIKhVotGlOABZok3gIADUIgTYIgUNKFABPSgMAUUoDAGFKFABtSAkIc0gJ
CBsbCwAAcAsAAHELAACsCwAArQsAAOgLAADpCwAAMwwAADQMAABCDAAAQwwA
AHoMAAB7DAAAlQwAAJYMAADDDAAA9QwAAPoAAAAAAAAAAAAAAAD6AAAAAAAA
AAAAAAAA+gAAAAAAAAAAAAAAAPoAAAAAAAAAAAAAAAD6AAAAAAAAAAAAAAAA
+gAAAAAAAAAAAAAAAPoAAAAAAAAAAAAAAAD6AAAAAAAAAAAAAAAA2QAAAAAA
AAAAAAAAANEAAAAAAAAAAAAAAADMAAAAAAAAAAAAAAAAxwAAAAAAAAAAAAAA
AKYAAAAAAAAAAAAAAADHAAAAAAAAAAAAAAAAxwAAAAAAAAAAAAAAAJwAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
CQAAAyQDE6QoAGEkA2dkk3gIACEAAAMkASRkGBIAASZkGBIAAS1EAAFNxgoA
AAD/5ubmAAAATsYIAAAA/xgSAQBQxggAAAD/GBIBAGEkAWdkk3gIAAAEAABn
ZJN4CAAABAAAZ2QdMbgAAAcAAAMkAWEkAWdkHTG4ACEAAAMkASRkGBIAASZk
GBIAAS1EAAFNxgoAAAD/5ubmAAAATsYIAAAA/xgSAQBQxggAAAD/GBIBAGEk
AWdkHTG4AAAEAABnZAdauQAAEK0LAACwCwAAsQsAAOYLAADoCwAA6QsAAPML
AAD0CwAA/AsAAA0MAAAxDAAAMgwAADMMAAA0DAAA7trHsZ6KnnpmUp5CMgAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeFmgdMbgAQ0oUAE9KAwBR
SgMAYUoUAG1ICQhzSAkIAB4WaF9zlgBDShQAT0oDAFFKAwBhShQAbUgJCHNI
CQgAJxVoV2O3ABZoHTG4ADUIgUNKFABPSgMAUUoDAGFKFABtSAkIc0gJCCcV
aFdjtwAWaJwqBAA1CIFDShQAT0oDAFFKAwBhShQAbUgJCHNICQgeFmicKgQA
Q0oUAE9KAwBRSgMAYUoUAG1ICQhzSAkIACcVaLRpTgAWaF9zlgA1CIFDShQA
T0oDAFFKAwBhShQAbUgJCHNICQgkFWi0aU4AFmhfc5YAQ0oUAE9KAwBRSgMA
YUoUAG1ICQhzSAkIACoVaLRpTgAWaJN4CAA1CIE2CIFDShQAT0oDAFFKAwBh
ShQAbUgJCHNICQgAJBVotGlOABZok3gIAENKFABPSgMAUUoDAGFKFABtSAkI
c0gJCAAnFWi0aU4AFmiTeAgANQiBQ0oUAE9KAwBRSgMAYUoUAG1ICQhzSAkI
IRZosS4kADUIgUNKFABPSgMAUUoDAGFKFABtSAkIc0gJCAANNAwAAEEMAABC
DAAAQwwAAHAMAAB2DAAAdwwAAHoMAAB7DAAAlQwAAJYMAAC6DAAAvgwAAO3X
w7CbiZt2YE8+LQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIRZo0zZlADUI
gUNKFABPSgMAUUoDAGFKFABtSAkIc0gJCCEWaP0UHgA1CIFDShQAT0oDAFFK
AwBhShQAbUgJCHNICQghFmjYI9wANQiBQ0oUAE9KAwBRSgMAYUoUAG1ICQhz
SAkIKhVotGlOABZok3gIADUIgTYIgUNKFABPSgMAUUoDAGFKFABtSAkIc0gJ
CAAkFWi0aU4AFmiTeAgAQ0oUAE9KAwBRSgMAYUoUAG1ICQhzSAkIACIWaB0x
uABDShQAT0oDAFFKAwBeSgIAYUoUAG1ICQhzSAkIACgVaLRpTgAWaB0xuABD
ShQAT0oDAFFKAwBeSgIAYUoUAG1ICQhzSAkIACUWaB0xuAA1CIFDShQAT0oD
AFFKAwBeSgIAYUoUAG1ICQhzSAkIJxVotGlOABZoHTG4ADUIgUNKFABPSgMA
UUoDAGFKFABtSAkIc0gJCCoVaLRpTgAWaB0xuAA1CIE2CIFDShQAT0oDAFFK
AwBhShQAbUgJCHNICQgAJBZoHTG4ADUIgTYIgUNKFABPSgMAUUoDAGFKFABt
SAkIc0gJCAy+DAAAwgwAAMMMAADIDAAAyQwAAMwMAADgDAAA6QwAAPAMAAD0
DAAA9QwAAP0MAAD+DAAA/wwAAAANAAAYDQAA69fBrpqJeIl4mmRUQVQyAAAA
AAAAAAAAAAAAAAAAAAAAAAAAHBVoe3MFABZo/RQeAENKFABPSgMAUUoDAGFK
FAAAJBVotGlOABZok3gIAENKFABPSgMAUUoDAGFKFABtSAkIc0gJCAAeFmj9
FB4AQ0oUAE9KAwBRSgMAYUoUAG1ICQhzSAkIACcVaP0UHgAWaJN4CAA1CIFD
ShQAT0oDAFFKAwBhShQAbUgJCHNICQghFmjgDA4AQ0oUAE9KAwBRSgMAXAiB
YUoUAG1ICQhzSAkIIRZo/RQeAENKFABPSgMAUUoDAFwIgWFKFABtSAkIc0gJ
CCcVaLRpTgAWaJN4CABDShQAT0oDAFFKAwBcCIFhShQAbUgJCHNICQgkFmj9
FB4ANQiBQ0oUAE9KAwBRSgMAXAiBYUoUAG1ICQhzSAkIACoVaP0UHgAWaJN4
CAA1CIFDShQAT0oDAFFKAwBcCIFhShQAbUgJCHNICQgAJxVotGlOABZok3gI
ADUIgUNKFABPSgMAUUoDAGFKFABtSAkIc0gJCCcVaLRpTgAWaJQD4AA1CIFD
ShQAT0oDAFFKAwBhShQAbUgJCHNICQgADxgNAABNDQAATg0AAAsOAAAYDgAA
GQ4AABoOAAAvDgAAMA4AADEOAABNDgAATg4AAE8OAABYDgAAWQ4AAHUOAAB2
DgAAeg4AAI4OAACPDgAA7t7PvqqWg3OWg3OWc4NzlmJRPQAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAJxVotGlOABZoDXn0ADUIgUNKFABPSgMAUUoDAGFKFABt
SAkIc0gJCCEWaA159AA1CIFDShQAT0oDAFFKAwBhShQAbUgJCHNICQghFmic
KgQANQiBQ0oUAE9KAwBRSgMAYUoUAG1ICQhzSAkIHhZonCoEAENKFABPSgMA
UUoDAGFKFABtSAkIc0gJCAAkFWicKgQAFmicKgQAQ0oUAE9KAwBRSgMAYUoU
AG1ICQhzSAkIACcVaJwqBAAWaJwqBAA1CIFDShQAT0oDAFFKAwBhShQAbUgJ
CHNICQgnFWi0aU4AFmiTeAgANQiBQ0oUAE9KAwBRSgMAYUoUAG1ICQhzSAkI
IRZo4AwOADUIgUNKFABPSgMAUUoDAGFKFABtSAkIc0gJCBwVaHtzBQAWaP0U
HgBDShQAT0oDAFFKAwBhShQAAB8VaHtzBQAWaP0UHgA1CIFDShQAT0oDAFFK
AwBhShQAIhVoe3MFABZo/RQeADUIgT4qAUNKFABPSgMAUUoDAGFKFAAT9QwA
AE4NAAByDQAAkA0AAKwNAADJDQAACw4AABoOAAAxDgAATw4AAGoOAAB2DgAA
dw4AAHgOAAB5DgAAeg4AAJAOAADaDgAADw8AAPAAAAAAAAAAAAAAAADZAAAA
AAAAAAAAAAAAxwAAAAAAAAAAAAAAAMcAAAAAAAAAAAAAAADHAAAAAAAAAAAA
AAAAxwAAAAAAAAAAAAAAALUAAAAAAAAAAAAAAACtAAAAAAAAAAAAAAAArQAA
AAAAAAAAAAAAAK0AAAAAAAAAAAAAAACtAAAAAAAAAAAAAAAAqAAAAAAAAAAA
AAAAAKgAAAAAAAAAAAAAAACoAAAAAAAAAAAAAAAAqAAAAAAAAAAAAAAAAKgA
AAAAAAAAAAAAAACbAAAAAAAAAAAAAAAAmwAAAAAAAAAAAAAAAA0AAAMkAwom
AAtGAQATpFAAYSQDZ2QNefQAAAQAAGdkDXn0AAgAAAomAAtGDwBnZJwqBAAA
EQAAAyQDD4RwCBGEkPcTpCgAXoRwCGCEkPdhJANnZJwqBAASAAADJAMKJgAL
RgsAEmQiAQAAE6RkABSkZABhJANnZP0UHgAAFgAAAyQDD4SgBRGE0AISZCIB
AAATpGQAFKRkAF6EoAVghNACYSQDZ2T9FB4AAA4AAAMkAxJkIgEAABOkZAAU
pGQAYSQDZ2T9FB4AABKPDgAAkA4AAKoOAADYDgAA2Q4AANoOAADoDgAA/g4A
AA4PAAAcDwAANw8AADkPAAB7DwAAqw8AAKwPAACtDwAAwA8AAMsPAADqDwAA
9Q8AAPYPAADr18HXsNfB17DBsMGw15yGdmJPPAAAAAAAAAAAAAAAAAAAAAAk
FWi0aU4AFmiUA+AAQ0oUAE9KAwBRSgMAYUoUAG1ICQhzSAkIACQVaLRpTgAW
aF9zlgBDShQAT0oDAFFKAwBhShQAbUgJCHNICQgAJxVoV2O3ABZo/RQeADUI
gUNKFABPSgMAUUoDAGFKFABtSAkIc0gJCB4WaP0UHgBDShQAT0oDAFFKAwBh
ShQAbUgJCHNICQgAKhVotGlOABZok3gIADUIgTYIgUNKFABPSgMAUUoDAGFK
FABtSAkIc0gJCAAnFWi0aU4AFmi0aU4AQ0oUAE9KAwBRSgMAXAiBYUoUAG1I
CQhzSAkIIRZoDXn0AENKFABPSgMAUUoDAFwIgWFKFABtSAkIc0gJCCoVaFdj
twAWaA159AA1CIFDShQAT0oDAFFKAwBcCIFhShQAbUgJCHNICQgAJxVoDXn0
ABZoDXn0AENKFABPSgMAUUoDAFwIgWFKFABtSAkIc0gJCCcVaLRpTgAWaA15
9ABDShQAT0oDAFFKAwBcCIFhShQAbUgJCHNICQgAFA8PAAA5DwAAfQ8AAKwP
AACtDwAAwA8AAPcPAABFEAAAbxAAAJ0QAACeEAAArxAAANEQAAD4EAAASxEA
AKQRAADyAAAAAAAAAAAAAAAA8gAAAAAAAAAAAAAAAPIAAAAAAAAAAAAAAADt
AAAAAAAAAAAAAAAAzAAAAAAAAAAAAAAAAL8AAAAAAAAAAAAAAACtAAAAAAAA
AAAAAAAAvwAAAAAAAAAAAAAAAL8AAAAAAAAAAAAAAACjAAAAAAAAAAAAAAAA
zAAAAAAAAAAAAAAAAJkAAAAAAAAAAAAAAACZAAAAAAAAAAAAAAAAjwAAAAAA
AAAAAAAAAJkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAACQAAAyQDE6QoAGEkA2dk9BoKAAAJAAADJAMTpCgAYSQDZ2SUA+AAAAkA
AAMkAxOkKABhJANnZF9zlgASAAADJAMKJgALRgEAEmQiAQAAE6RkABSkZABh
JANnZP0UHgANAAADJAMKJgALRgEAE6RQAGEkA2dkX3OWACEAAAMkASRkGBIA
ASZkGBIAAS1EAAFNxgoAAAD/5ubmAAAATsYIAAAA/xgSAQBQxggAAAD/GBIB
AGEkAWdkk3gIAAAEAABnZJN4CAANAAADJAMKJgALRgEAE6RQAGEkA2dkDXn0
AAAP9g8AAPcPAAAFEAAAFhAAACsQAABFEAAAbxAAAJwQAACdEAAAnhAAAK8Q
AAC9EAAAvhAAAL8QAADAEAAA8OHRwuGyoo98ZlI/LLIAAAAAAAAAAAAAAAAA
ACQVaLRpTgAWaJQD4ABDShQAT0oDAFFKAwBhShQAbUgJCHNICQgAJBVotGlO
ABZok3gIAENKFABPSgMAUUoDAGFKFABtSAkIc0gJCAAnFWi0aU4AFmiTeAgA
NQiBQ0oUAE9KAwBRSgMAYUoUAG1ICQhzSAkIKhVotGlOABZok3gIADUIgTYI
gUNKFABPSgMAUUoDAGFKFABtSAkIc0gJCAAkFWi0aU4AFmhfc5YAQ0oUAE9K
AwBRSgMAYUoUAG1ICQhzSAkIACQVaLRpTgAWaPQaCgBDShQAT0oDAFFKAwBh
ShQAbUgJCHNICQgAHhZo9BoKAENKFABPSgMAUUoDAGFKFABtSAkIc0gJCAAe
FmixLiQAQ0oUAE9KAwBRSgMAYUoUAG1ICQhzSAkIABwVaAFSogAWaNx89QBD
ShQAT0oDAFFKAwBhShQAAB8VaAFSogAWaP0UHgA1CIFDShQAT0oDAFFKAwBh
ShQAHBVoAVKiABZo/RQeAENKFABPSgMAUUoDAGFKFAAAHhZok3gIAENKFABP
SgMAUUoDAGFKFABtSAkIc0gJCA7AEAAAwhAAAMsQAADPEAAA0BAAANEQAADZ
EAAA2xAAANwQAADrEAAA7BAAAPAQAAD2EAAA9xAAAPgQAAD/EAAAAhEAACMR
AADr28jbtaGNobV9tch9bVxIOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHhZo
9BoKAENKFABPSgMAUUoDAGFKFABtSAkIc0gJCAAnFWi0aU4AFmj0GgoANQiB
Q0oUAE9KAwBRSgMAYUoUAG1ICQhzSAkIIRZo9BoKADUIgUNKFABPSgMAUUoD
AGFKFABtSAkIc0gJCB4WaF9zlgBDShQAT0oDAFFKAwBhShQAbUgJCHNICQgA
HhZo3Hz1AENKFABPSgMAUUoDAGFKFABtSAkIc0gJCAAnFWi0aU4AFmiTeAgA
NQiBQ0oUAE9KAwBRSgMAYUoUAG1ICQhzSAkIJxVotGlOABZolAPgADUIgUNK
FABPSgMAUUoDAGFKFABtSAkIc0gJCCQVaLRpTgAWaJN4CABDShQAT0oDAFFK
AwBhShQAbUgJCHNICQgAJBVotGlOABZoX3OWAENKFABPSgMAUUoDAGFKFABt
SAkIc0gJCAAeFmixLiQAQ0oUAE9KAwBRSgMAYUoUAG1ICQhzSAkIACcVaLEu
JAAWaLEuJABDShQASCoBT0oDAFFKAwBhShQAbUgJCHNICQgAESMRAABDEQAA
SxEAAFwRAABeEQAAoxEAAKQRAACyEQAAwhEAAP4RAAACEgAABBIAAAUSAAAI
EgAAExIAABUSAAAXEgAA8ODMuKSTpH2kaaRYk0STMwAAAAAAAAAAAAAAAAAA
AAAAACEWaAFSogBDShQAT0oDAFFKAwBcCIFhShQAbUgJCHNICQgnFWi0aU4A
FmjcfPUAQ0oUAE9KAwBRSgMAXAiBYUoUAG1ICQhzSAkIIRZoUmEOAENKFABP
SgMAUUoDAFwIgWFKFABtSAkIc0gJCCcVaLRpTgAWaAdauQBDShQAT0oDAFFK
AwBcCIFhShQAbUgJCHNICQgqFWi0aU4AFmiUA+AANQiBQ0oUAE9KAwBRSgMA
XAiBYUoUAG1ICQhzSAkIACEWaNx89QBDShQAT0oDAFFKAwBcCIFhShQAbUgJ
CHNICQgnFWi0aU4AFmiUA+AAQ0oUAE9KAwBRSgMAXAiBYUoUAG1ICQhzSAkI
JxVotGlOABZok3gIADUIgUNKFABPSgMAUUoDAGFKFABtSAkIc0gJCCcVaLRp
TgAWaJQD4AA1CIFDShQAT0oDAFFKAwBhShQAbUgJCHNICQgeFmj0GgoAQ0oU
AE9KAwBRSgMAYUoUAG1ICQhzSAkIAB4WaH5LEABDShQAT0oDAFFKAwBhShQA
bUgJCHNICQgQpBEAALIRAAAFEgAAFRIAABYSAAAXEgAAGBIAABkSAAAaEgAA
GxIAAK0SAACuEgAArxIAALASAACxEgAAshIAANgSAADZEgAA2hIAAO0AAAAA
AAAAAAAAAADjAAAAAAAAAAAAAAAA4wAAAAAAAAAAAAAAAOMAAAAAAAAAAAAA
AADjAAAAAAAAAAAAAAAA4wAAAAAAAAAAAAAAAOMAAAAAAAAAAAAAAADjAAAA
AAAAAAAAAAAA4wAAAAAAAAAAAAAAAN4AAAAAAAAAAAAAAADeAAAAAAAAAAAA
AAAA3gAAAAAAAAAAAAAAAN4AAAAAAAAAAAAAAADeAAAAAAAAAAAAAAAA3gAA
AAAAAAAAAAAAAN4AAAAAAAAAAAAAAADjAAAAAAAAAAAAAAAA4wAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAQAAGdkAVKiAAAJAAADJAMTpCgAYSQDZ2RAfZEAABEAAAMkAw+EoAUR
hNACE6QoAF6EoAVghNACYSQDZ2TcfPUAABIXEgAAGBIAABkSAAAbEgAArhIA
ALASAACxEgAAuBIAALoSAAC+EgAA1xIAANgSAADZEgAA2hIAAO7dzLmxoZWJ
fYmV3WkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAnFWi0aU4AFmgBUqIAQ0oUAE9KAwBRSgMAXAiBYUoUAG1I
CQhzSAkIFhZopzrJAENKFABPSgIAUUoCAF5KAgAAFhZor36TAENKFABPSgIA
UUoCAF5KAgAAFhZoAVKiAENKFABPSgIAUUoCAF5KAgAAHxZoAVKiAEIqAUNK
FABPSgIAUUoCAF5KAgBwaAAAAAAPFmgBUqIAQioBcGgzMzMAJRVoAVKiABZo
AVKiAEIqAUNKFABPSgMAUUoDAGFKFABwaDMzMwAhFmgiKJcAQ0oUAE9KAwBR
SgMAXAiBYUoUAG1ICQhzSAkIIRZoAVKiAENKFABPSgMAUUoDAFwIgWFKFABt
SAkIc0gJCCEWaDwxSgBDShQAT0oDAFFKAwBcCIFhShQAbUgJCHNICQgADX4A
JlAJACtwDAEAOCxwDAEAOC1wDAEAOC5wDAEAODGQaAEvUiAANNIIAAAA/wwB
OAA10ggAAAD/DAE4ADbSCAAAAP8MATgAN9IIAAAA/wwBOAA6cJQD4AAfsIUu
ILDCQSGw8AMisPADI5DwAySQ8AMlsAAAF7AAABiwAAAMkNACAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAF4EFAASAAEACwEPAAcAAAAAAAAAAAAEAAgAAAAI
AAAADgAAAA4AAAAOAAAADgAAAA4AAAAOAAAADgAAAA4AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAIAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADIGAAAYAAAAwAMA
ANADAADgAwAA8AMAAAAEAAAQBAAAIAQAADAEAABABAAAUAQAAGAEAABwBAAA
gAQAAJAEAADAAwAA0AMAAOADAADwAwAAAAQAABAEAAAyBgAAKAIAANgBAADo
AQAAIAQAADAEAABABAAAUAQAAGAEAABwBAAAgAQAAJAEAADAAwAA0AMAAOAD
AADwAwAAAAQAABAEAAAgBAAAMAQAAEAEAABQBAAAYAQAAHAEAACABAAAkAQA
AMADAADQAwAA4AMAAPADAAAABAAAEAQAACAEAAAwBAAAQAQAAFAEAABgBAAA
cAQAAIAEAACQBAAAwAMAANADAADgAwAA8AMAAAAEAAAQBAAAIAQAADAEAABA
BAAAUAQAAGAEAABwBAAAgAQAAJAEAADAAwAA0AMAAOADAADwAwAAAAQAABAE
AAAgBAAAMAQAAEAEAABQBAAAYAQAAHAEAACABAAAkAQAAMADAADQAwAA4AMA
APADAAAABAAAEAQAACAEAAAwBAAAQAQAAFAEAABgBAAAcAQAAIAEAACQBAAA
OAEAAFgBAAD4AQAACAIAABgCAABWAgAAfgIAABQAAABfSAEEbUgJCG5ICQhz
SAkIdEgJCAAAAABIAABg8f8CAEgADBQAAJN4CAAAAAYATgBvAHIAbQBhAGwA
AAACAAAAIABDShEAT0oEAFFKBABfSAEEYUoRAG1ICQRzSAkEdEgJBAAAAAAA
AAAAAAAAAAAAAAAAAEQAQSDy/6EARAAMBQAAAAAAAAAAFgBEAGUAZgBhAHUA
bAB0ACAAUABhAHIAYQBnAHIAYQBwAGgAIABGAG8AbgB0AAAAAABSAGkA8/+z
AFIADAUAAAAAAAAAAAwAVABhAGIAbABlACAATgBvAHIAbQBhAGwAAAAcABf2
AwAANNYGAAEKA2wANNYGAAEFAwAAYfYDAAACAAsAAAAoAGsg9P/BACgAAAUA
AAAAAAAAAAcATgBvACAATABpAHMAdAAAAAIADAAAAAAANgBVIPL/8QA2AAwE
AACTeAgAAAAJAEgAeQBwAGUAcgBsAGkAbgBrAAAADAA+KgFCKgJwaAAA/wBC
ACcg8v8BAUIADAUAAEB9kQAAABEAQwBvAG0AbQBlAG4AdAAgAFIAZQBmAGUA
cgBlAG4AYwBlAAAACABDShAAYUoQADwAHgABABIBPAAMBQAAQH2RAAAADABD
AG8AbQBtAGUAbgB0ACAAVABlAHgAdAAAAAIAEQAIAENKFABhShQAQABqABEB
EgFAAAwFAABAfZEAAAAPAEMAbwBtAG0AZQBuAHQAIABTAHUAYgBqAGUAYwB0
AAAAAgASAAYANQiBXAiBSACZAAEAMgFIAAwFAABAfZEAAAAMAEIAYQBsAGwA
bwBvAG4AIABUAGUAeAB0AAAAAgATABQAQ0oQAE9KBQBRSgUAXkoFAGFKEABQ
SwMEFAAGAAgAAAAhAIKKvBP6AAAAHAIAABMAAABbQ29udGVudF9UeXBlc10u
eG1srJHLasMwEEX3hf6D0LbYcroopdjOokl3fSzSDxjksS1qj4Q0Ccnfd+y4
ULoILXQjEGLOmXtVro/joA4Yk/NU6VVeaIVkfeOoq/T77im71yoxUAODJ6z0
CZNe19dX5e4UMCmZplTpnjk8GJNsjyOk3AckeWl9HIHlGjsTwH5Ah+a2KO6M
9cRInPHE0HX5KgtE16B6g8gvMIrHsKDw+/kMJICYC1irxzNhWqLSEMLgLLBE
MAdqfugz37bOYuPtfhRpPoMX2M0EM79cYPU/6i/nBlvYD6y2R+niXH/EIf0t
21JrLpNz/tS7kC4YLpe3tGHmv60/AQAA//8DAFBLAwQUAAYACAAAACEApdan
58AAAAA2AQAACwAAAF9yZWxzLy5yZWxzhI/PasMwDIfvhb2D0X1R0sMYJXYv
pZBDL6N9AOEof2giG9sb69tPxwYKuwiEpO/3qT3+rov54ZTnIBaaqgbD4kM/
y2jhdj2/f4LJhaSnJQhbeHCGo3vbtV+8UNGjPM0xG6VItjCVEg+I2U+8Uq5C
ZNHJENJKRds0YiR/p5FxX9cfmJ4Z4DZM0/UWUtc3YK6PqMn/s8MwzJ5PwX+v
LOVFBG43lExp5GKhqC/jU72QqGWq1B7Qtbj51v0BAAD//wMAUEsDBBQABgAI
AAAAIQBreZYWgwAAAIoAAAAcAAAAdGhlbWUvdGhlbWUvdGhlbWVNYW5hZ2Vy
LnhtbAzMTQrDIBBA4X2hd5DZN2O7KEVissuuu/YAQ5waQceg0p/b1+XjgzfO
3xTVm0sNWSycBw2KZc0uiLfwfCynG6jaSBzFLGzhxxXm6XgYybSNE99JyHNR
fSPVkIWttd0g1rUr1SHvLN1euSRqPYtHV+jT9yniResrJgoCOP0BAAD//wMA
UEsDBBQABgAIAAAAIQCWta3ilgYAAFAbAAAWAAAAdGhlbWUvdGhlbWUvdGhl
bWUxLnhtbOxZT2/bNhS/D9h3IHRvYyd2Ggd1itixmy1NG8Ruhx5piZbYUKJA
0kl9G9rjgAHDumGHFdhth2FbgRbYpfs02TpsHdCvsEdSksVYXpI22IqtPiQS
+eP7/x4fqavX7scMHRIhKU/aXv1yzUMk8XlAk7Dt3R72L615SCqcBJjxhLS9
KZHetY3337uK11VEYoJgfSLXcduLlErXl5akD8NYXuYpSWBuzEWMFbyKcCkQ
+AjoxmxpuVZbXYoxTTyU4BjI3hqPqU/QUJP0NnLiPQaviZJ6wGdioEkTZ4XB
Bgd1jZBT2WUCHWLW9oBPwI+G5L7yEMNSwUTbq5mft7RxdQmvZ4uYWrC2tK5v
ftm6bEFwsGx4inBUMK33G60rWwV9A2BqHtfr9bq9ekHPALDvg6ZWljLNRn+t
3slplkD2cZ52t9asNVx8if7KnMytTqfTbGWyWKIGZB8bc/i12mpjc9nBG5DF
N+fwjc5mt7vq4A3I4lfn8P0rrdWGizegiNHkYA6tHdrvZ9QLyJiz7Ur4GsDX
ahl8hoJoKKJLsxjzRC2KtRjf46IPAA1kWNEEqWlKxtiHKO7ieCQo1gzwOsGl
GTvky7khzQtJX9BUtb0PUwwZMaP36vn3r54/RccPnh0/+On44cPjBz9aQs6q
bZyE5VUvv/3sz8cfoz+efvPy0RfVeFnG//rDJ7/8/Hk1ENJnJs6LL5/89uzJ
i68+/f27RxXwTYFHZfiQxkSim+QI7fMYFDNWcSUnI3G+FcMI0/KKzSSUOMGa
SwX9nooc9M0pZpl3HDk6xLXgHQHlowp4fXLPEXgQiYmiFZx3otgB7nLOOlxU
WmFH8yqZeThJwmrmYlLG7WN8WMW7ixPHv71JCnUzD0tH8W5EHDH3GE4UDklC
FNJz/ICQCu3uUurYdZf6gks+VuguRR1MK00ypCMnmmaLtmkMfplW6Qz+dmyz
ewd1OKvSeoscukjICswqhB8S5pjxOp4oHFeRHOKYlQ1+A6uoSsjBVPhlXE8q
8HRIGEe9gEhZteaWAH1LTt/BULEq3b7LprGLFIoeVNG8gTkvI7f4QTfCcVqF
HdAkKmM/kAcQohjtcVUF3+Vuhuh38ANOFrr7DiWOu0+vBrdp6Ig0CxA9MxHa
l1CqnQoc0+TvyjGjUI9tDFxcOYYC+OLrxxWR9bYW4k3Yk6oyYftE+V2EO1l0
u1wE9O2vuVt4kuwRCPP5jeddyX1Xcr3/fMldlM9nLbSz2gplV/cNtik2LXK8
sEMeU8YGasrIDWmaZAn7RNCHQb3OnA5JcWJKI3jM6rqDCwU2a5Dg6iOqokGE
U2iw654mEsqMdChRyiUc7MxwJW2NhyZd2WNhUx8YbD2QWO3ywA6v6OH8XFCQ
MbtNaA6fOaMVTeCszFauZERB7ddhVtdCnZlb3YhmSp3DrVAZfDivGgwW1oQG
BEHbAlZehfO5Zg0HE8xIoO1u997cLcYLF+kiGeGAZD7Ses/7qG6clMeKuQmA
2KnwkT7knWK1EreWJvsG3M7ipDK7xgJ2uffexEt5BM+8pPP2RDqypJycLEFH
ba/VXG56yMdp2xvDmRYe4xS8LnXPh1kIF0O+EjbsT01mk+Uzb7ZyxdwkqMM1
hbX7nMJOHUiFVFtYRjY0zFQWAizRnKz8y00w60UpYCP9NaRYWYNg+NekADu6
riXjMfFV2dmlEW07+5qVUj5RRAyi4AiN2ETsY3C/DlXQJ6ASriZMRdAvcI+m
rW2m3OKcJV359srg7DhmaYSzcqtTNM9kCzd5XMhg3krigW6Vshvlzq+KSfkL
UqUcxv8zVfR+AjcFK4H2gA/XuAIjna9tjwsVcahCaUT9voDGwdQOiBa4i4Vp
CCq4TDb/BTnU/23OWRomreHAp/ZpiASF/UhFgpA9KEsm+k4hVs/2LkuSZYRM
RJXElakVe0QOCRvqGriq93YPRRDqpppkZcDgTsaf+55l0CjUTU4535waUuy9
Ngf+6c7HJjMo5dZh09Dk9i9ErNhV7XqzPN97y4roiVmb1cizApiVtoJWlvav
KcI5t1pbseY0Xm7mwoEX5zWGwaIhSuG+B+k/sP9R4TP7ZUJvqEO+D7UVwYcG
TQzCBqL6km08kC6QdnAEjZMdtMGkSVnTZq2Ttlq+WV9wp1vwPWFsLdlZ/H1O
YxfNmcvOycWLNHZmYcfWdmyhqcGzJ1MUhsb5QcY4xnzSKn914qN74OgtuN+f
MCVNMME3JYGh9RyYPIDktxzN0o2/AAAA//8DAFBLAwQUAAYACAAAACEADdGQ
n7YAAAAbAQAAJwAAAHRoZW1lL3RoZW1lL19yZWxzL3RoZW1lTWFuYWdlci54
bWwucmVsc4SPTQrCMBSE94J3CG9v07oQkSbdiNCt1AOE5DUNNj8kUeztDa4s
CC6HYb6ZabuXnckTYzLeMWiqGgg66ZVxmsFtuOyOQFIWTonZO2SwYIKObzft
FWeRSyhNJiRSKC4xmHIOJ0qTnNCKVPmArjijj1bkIqOmQci70Ej3dX2g8ZsB
fMUkvWIQe9UAGZZQmv+z/TgaiWcvHxZd/lFBc9mFBSiixszgI5uqTATKW7q6
xN8AAAD//wMAUEsBAi0AFAAGAAgAAAAhAIKKvBP6AAAAHAIAABMAAAAAAAAA
AAAAAAAAAAAAAFtDb250ZW50X1R5cGVzXS54bWxQSwECLQAUAAYACAAAACEA
pdan58AAAAA2AQAACwAAAAAAAAAAAAAAAAArAQAAX3JlbHMvLnJlbHNQSwEC
LQAUAAYACAAAACEAa3mWFoMAAACKAAAAHAAAAAAAAAAAAAAAAAAUAgAAdGhl
bWUvdGhlbWUvdGhlbWVNYW5hZ2VyLnhtbFBLAQItABQABgAIAAAAIQCWta3i
lgYAAFAbAAAWAAAAAAAAAAAAAAAAANECAAB0aGVtZS90aGVtZS90aGVtZTEu
eG1sUEsBAi0AFAAGAAgAAAAhAA3RkJ+2AAAAGwEAACcAAAAAAAAAAAAAAAAA
mwkAAHRoZW1lL3RoZW1lL19yZWxzL3RoZW1lTWFuYWdlci54bWwucmVsc1BL
BQYAAAAABQAFAF0BAACWCgAAAAA8P3htbCB2ZXJzaW9uPSIxLjAiIGVuY29k
aW5nPSJVVEYtOCIgc3RhbmRhbG9uZT0ieWVzIj8+DQo8YTpjbHJNYXAgeG1s
bnM6YT0iaHR0cDovL3NjaGVtYXMub3BlbnhtbGZvcm1hdHMub3JnL2RyYXdp
bmdtbC8yMDA2L21haW4iIGJnMT0ibHQxIiB0eDE9ImRrMSIgYmcyPSJsdDIi
IHR4Mj0iZGsyIiBhY2NlbnQxPSJhY2NlbnQxIiBhY2NlbnQyPSJhY2NlbnQy
IiBhY2NlbnQzPSJhY2NlbnQzIiBhY2NlbnQ0PSJhY2NlbnQ0IiBhY2NlbnQ1
PSJhY2NlbnQ1IiBhY2NlbnQ2PSJhY2NlbnQ2IiBobGluaz0iaGxpbmsiIGZv
bEhsaW5rPSJmb2xIbGluayIvPgAAAADaCgAACwAAOAAAAAD/////AAgAAG4I
AAA/CQAAEQsAAK0LAAA0DAAAvgwAABgNAACPDgAA9g8AAMAQAAAjEQAAFxIA
ANoSAAAKAAAADAAAAA0AAAAOAAAAEAAAABEAAAASAAAAEwAAABUAAAAXAAAA
GAAAABkAAAAbAAAAAAgAABsLAAD1DAAADw8AAKQRAADaEgAACwAAAA8AAAAU
AAAAFgAAABoAAAAPAADwOAAAAAAABvAYAAAAAggAAAIAAAABAAAAAQAAAAEA
AAACAAAAQAAe8RAAAAD//wAAAAD/AICAgAD3AAAQAA8AAvCSAAAAEAAI8AgA
AAABAAAAAQQAAA8AA/AwAAAADwAE8CgAAAABAAnwEAAAAAAAAAAAAAAAAAAA
AAAAAAACAArwCAAAAAAEAAAFAAAADwAE8EIAAAASAArwCAAAAAEEAAAADgAA
UwAL8B4AAAC/AQAAEADLAQAAAAD/AQAACAAEAwkAAAA/AwEAAQAAABHwBAAA
AAEAAAD//wIAAAAGAFwgDAARAAEAbHZKAAYAXSAMABAAAQDsfkoA0QkAANEJ
AADcCgAAAAAAAAIAAQAAAAIA2QkAANkJAADcCgAAAAAAAAEAAAACAAAAOAAA
AAIAAAAqgHVybjpzY2hlbWFzLW1pY3Jvc29mdC1jb206b2ZmaWNlOnNtYXJ0
dGFncwSAQ2l0eQCAOQAAAAEAAAAqgHVybjpzY2hlbWFzLW1pY3Jvc29mdC1j
b206b2ZmaWNlOnNtYXJ0dGFncwWAcGxhY2UAgAwAAAHwmSkFAAAAAAIAAAAA
AAEAAAAAAAAAAAAIAAAADAAAABIAAABFAQAASgEAAEsDAABQAwAAugMAAL8D
AABDBAAATQQAAIgJAACNCQAA6AkAAPMJAADECgAAzAoAANAKAADWCgAA3AoA
ABwABwAcAAcAHAAHABwABwAcAAcAHAAHABwABwAcAAcAHAAHABwABwAAAAAA
GwMAAG8DAABDBAAAeQQAANwHAADeBwAApQkAALEJAADJCQAAygkAAAgKAAAU
CgAAsgoAALgKAADcCgAABwAzAAcAMwAHADMABwAzAAcAMwAHADMABwAzAAcA
AAAAAJUEAACWBAAAQgkAAEMJAAAWCgAAFwoAABgKAADYCgAA2QoAANkKAADc
CgAAAwAEAAMABAADAAQAAwAEAAMABAAHAAAAAACVBAAAlgQAAEIJAABDCQAA
FgoAABcKAAAYCgAA2AoAANkKAADZCgAA3AoAAAMABAADAAQAAwAEAAMABAAD
AAQABwANAJgNoQJGrPID/w//D/8P/w//D/8P/w//D/8PEABxZPkIDAowF/8P
/w//D/8P/w//D/8P/w//DxAA00AOFgK77Er/D/8P/w//D/8P/w//D/8P/w8Q
ALUZiBr8hWjr/w//D/8P/w//D/8P/w//D/8PEACuSwElOoMwLP8P/w//D/8P
/w//D/8P/w//DxAAwmiYMCqc0Er/D/8P/w//D/8P/w//D/8P/w8QAA4ltTFK
6QIX/w//D/8P/w//D/8P/w//D/8PEAACI3E0PmXyR/8P/w//D/8P/w//D/8P
/w//DxAAnTEAP57lKrD/D/8P/w//D/8P/w//D/8P/w8QAN85tU7oE16v/w//
D/8P/w//D/8P/w//D/8PEABec0FgSsTcvP8P/w//D/8P/w//D/8P/w//DxAA
uC+gb7QlAOP/D/8P/w//D/8P/w//D/8P/w8QAGdGlnEAEXrz/w//D/8P/w//
D/8P/w//D/8PEAABAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAZGAAAD4TK/xGE
KP8VxgUAAcr/Bl6Eyv9ghCj/NQgBNggAQ0oWAE9KAQBRSgEAYUoWAG8oAAEA
t/ABAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAZGAAAD4SSBBGEmP4VxgUAAZIE
Bl6EkgRghJj+NQgBNggAQ0oWAE9KAQBRSgEAYUoWAG8oAAEAt/ABAAAAF4AA
AAAAAAAAAAAAAAAAAAAAAAALGAAAD4RiBxGEmP4VxgUAAWIHBl6EYgdghJj+
T0oGAFFKBgBvKAABAKfwAQAAABeAAAAAAAAAAAAAAAAAAAAAAAAACxgAAA+E
MgoRhJj+FcYFAAEyCgZehDIKYISY/k9KAQBRSgEAbygAAQC38AEAAAAXgAAA
AAAAAAAAAAAAAAAAAAAAAA8YAAAPhAINEYSY/hXGBQABAg0GXoQCDWCEmP5P
SgcAUUoHAF5KBwBvKAABAG8AAQAAABeAAAAAAAAAAAAAAAAAAAAAAAAACxgA
AA+E0g8RhJj+FcYFAAHSDwZehNIPYISY/k9KBgBRSgYAbygAAQCn8AEAAAAX
gAAAAAAAAAAAAAAAAAAAAAAAAAsYAAAPhKISEYSY/hXGBQABohIGXoSiEmCE
mP5PSgEAUUoBAG8oAAEAt/ABAAAAF4AAAAAAAAAAAAAAAAAAAAAAAAAPGAAA
D4RyFRGEmP4VxgUAAXIVBl6EchVghJj+T0oHAFFKBwBeSgcAbygAAQBvAAEA
AAAXgAAAAAAAAAAAAAAAAAAAAAAAAAsYAAAPhEIYEYSY/hXGBQABQhgGXoRC
GGCEmP5PSgYAUUoGAG8oAAEAp/ABAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAV
GAAAD4SgBRGEmP4VxgUAAaAFBl6EoAVghJj+T0oGAFFKBgBvKACHaAAAAACI
SAAAAQDY8AEAAAAXAAAAAAAAAAAAAAAAAAAAAAAAABkYAAAPhHAIEYSY/hXG
BQABcAgGXoRwCGCEmP5PSgcAUUoHAF5KBwBvKACHaAAAAACISAAAAQBvAAEA
AAAXAAAAAAAAAAAAAAAAAAAAAAAAABUYAAAPhEALEYSY/hXGBQABQAsGXoRA
C2CEmP5PSgYAUUoGAG8oAIdoAAAAAIhIAAABAKfwAQAAABcAAAAAAAAAAAAA
AAAAAAAAAAAAFRgAAA+EEA4RhJj+FcYFAAEQDgZehBAOYISY/k9KAQBRSgEA
bygAh2gAAAAAiEgAAAEAt/ABAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAZGAAA
D4TgEBGEmP4VxgUAAeAQBl6E4BBghJj+T0oHAFFKBwBeSgcAbygAh2gAAAAA
iEgAAAEAbwABAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAVGAAAD4SwExGEmP4V
xgUAAbATBl6EsBNghJj+T0oGAFFKBgBvKACHaAAAAACISAAAAQCn8AEAAAAX
AAAAAAAAAAAAAAAAAAAAAAAAABUYAAAPhIAWEYSY/hXGBQABgBYGXoSAFmCE
mP5PSgEAUUoBAG8oAIdoAAAAAIhIAAABALfwAQAAABcAAAAAAAAAAAAAAAAA
AAAAAAAAGRgAAA+EUBkRhJj+FcYFAAFQGQZehFAZYISY/k9KBwBRSgcAXkoH
AG8oAIdoAAAAAIhIAAABAG8AAQAAABcAAAAAAAAAAAAAAAAAAAAAAAAAFRgA
AA+EIBwRhJj+FcYFAAEgHAZehCAcYISY/k9KBgBRSgYAbygAh2gAAAAAiEgA
AAEAp/ABAAAAFxAAAAAAAAAAAAAAaAEAAAAAAAASEAAAD4TCARGEmP5ehMIB
YISY/k9KBgBRSgYAh2gAAAAAiEgAAAEA8PABAAAAF5AAAAAAAAAAAAAAaAEA
AAAAAAAZEAAAD4SSBBGEmP5ehJIEYISY/k9KBwBRSgcAXkoHAG8oAIdoAAAA
AIhIAAABAG8AAQAAABeQAAAAAAAAAAAAAGgBAAAAAAAAFRAAAA+EYgcRhJj+
XoRiB2CEmP5PSgYAUUoGAG8oAIdoAAAAAIhIAAABAKfwAQAAABeQAAAAAAAA
AAAAAGgBAAAAAAAAFRAAAA+EMgoRhJj+XoQyCmCEmP5PSgEAUUoBAG8oAIdo
AAAAAIhIAAABALfwAQAAABeQAAAAAAAAAAAAAGgBAAAAAAAAGRAAAA+EAg0R
hJj+XoQCDWCEmP5PSgcAUUoHAF5KBwBvKACHaAAAAACISAAAAQBvAAEAAAAX
kAAAAAAAAAAAAABoAQAAAAAAABUQAAAPhNIPEYSY/l6E0g9ghJj+T0oGAFFK
BgBvKACHaAAAAACISAAAAQCn8AEAAAAXkAAAAAAAAAAAAABoAQAAAAAAABUQ
AAAPhKISEYSY/l6EohJghJj+T0oBAFFKAQBvKACHaAAAAACISAAAAQC38AEA
AAAXkAAAAAAAAAAAAABoAQAAAAAAABkQAAAPhHIVEYSY/l6EchVghJj+T0oH
AFFKBwBeSgcAbygAh2gAAAAAiEgAAAEAbwABAAAAF5AAAAAAAAAAAAAAaAEA
AAAAAAAVEAAAD4RCGBGEmP5ehEIYYISY/k9KBgBRSgYAbygAh2gAAAAAiEgA
AAEAp/ABAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAALEAAAD4TQAhGEmP5ehNAC
YISY/k9KAQBRSgEAbygAAQC38AEAAAAXgAAAAAAAAAAAAAAAAAAAAAAAAA8Q
AAAPhKAFEYSY/l6EoAVghJj+T0oHAFFKBwBeSgcAbygAAQBvAAEAAAAXgAAA
AAAAAAAAAAAAAAAAAAAAAAsQAAAPhHAIEYSY/l6EcAhghJj+T0oGAFFKBgBv
KAABAKfwAQAAABeAAAAAAAAAAAAAAAAAAAAAAAAACxAAAA+EQAsRhJj+XoRA
C2CEmP5PSgEAUUoBAG8oAAEAt/ABAAAAF4AAAAAAAAAAAAAAAAAAAAAAAAAP
EAAAD4QQDhGEmP5ehBAOYISY/k9KBwBRSgcAXkoHAG8oAAEAbwABAAAAF4AA
AAAAAAAAAAAAAAAAAAAAAAALEAAAD4TgEBGEmP5ehOAQYISY/k9KBgBRSgYA
bygAAQCn8AEAAAAXgAAAAAAAAAAAAAAAAAAAAAAAAAsQAAAPhLATEYSY/l6E
sBNghJj+T0oBAFFKAQBvKAABALfwAQAAABeAAAAAAAAAAAAAAAAAAAAAAAAA
DxAAAA+EgBYRhJj+XoSAFmCEmP5PSgcAUUoHAF5KBwBvKAABAG8AAQAAABeA
AAAAAAAAAAAAAAAAAAAAAAAACxAAAA+EUBkRhJj+XoRQGWCEmP5PSgYAUUoG
AG8oAAEAp/ABAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAALEAAAD4TQAhGEmP5e
hNACYISY/k9KBgBRSgYAbygAAQCn8AEAAAAXgAAAAAAAAAAAAAAAAAAAAAAA
AA8QAAAPhKAFEYSY/l6EoAVghJj+T0oHAFFKBwBeSgcAbygAAQBvAAEAAAAX
gAAAAAAAAAAAAAAAAAAAAAAAAAsQAAAPhHAIEYSY/l6EcAhghJj+T0oGAFFK
BgBvKAABAKfwAQAAABeAAAAAAAAAAAAAAAAAAAAAAAAACxAAAA+EQAsRhJj+
XoRAC2CEmP5PSgEAUUoBAG8oAAEAt/ABAAAAF4AAAAAAAAAAAAAAAAAAAAAA
AAAPEAAAD4QQDhGEmP5ehBAOYISY/k9KBwBRSgcAXkoHAG8oAAEAbwABAAAA
F4AAAAAAAAAAAAAAAAAAAAAAAAALEAAAD4TgEBGEmP5ehOAQYISY/k9KBgBR
SgYAbygAAQCn8AEAAAAXgAAAAAAAAAAAAAAAAAAAAAAAAAsQAAAPhLATEYSY
/l6EsBNghJj+T0oBAFFKAQBvKAABALfwAQAAABeAAAAAAAAAAAAAAAAAAAAA
AAAADxAAAA+EgBYRhJj+XoSAFmCEmP5PSgcAUUoHAF5KBwBvKAABAG8AAQAA
ABeAAAAAAAAAAAAAAAAAAAAAAAAACxAAAA+EUBkRhJj+XoRQGWCEmP5PSgYA
UUoGAG8oAAEAp/ABAAAAFxAAAAAAAAAAAAAAAAAAAAAAAAASGAAAD4RoARGE
mP4VxgUAAWgBBl6EaAFghJj+T0oGAFFKBgCHaAAAAACISAAAAQDw8AEAAAAX
kAAAAAAAAAAAAAAAAAAAAAAAABkYAAAPhKAFEYSY/hXGBQABoAUGXoSgBWCE
mP5PSgcAUUoHAF5KBwBvKACHaAAAAACISAAAAQBvAAEAAAAXkAAAAAAAAAAA
AAAAAAAAAAAAABUYAAAPhHAIEYSY/hXGBQABcAgGXoRwCGCEmP5PSgYAUUoG
AG8oAIdoAAAAAIhIAAABAKfwAQAAABeQAAAAAAAAAAAAAAAAAAAAAAAAFRgA
AA+EQAsRhJj+FcYFAAFACwZehEALYISY/k9KAQBRSgEAbygAh2gAAAAAiEgA
AAEAt/ABAAAAF5AAAAAAAAAAAAAAAAAAAAAAAAAZGAAAD4QQDhGEmP4VxgUA
ARAOBl6EEA5ghJj+T0oHAFFKBwBeSgcAbygAh2gAAAAAiEgAAAEAbwABAAAA
F5AAAAAAAAAAAAAAAAAAAAAAAAAVGAAAD4TgEBGEmP4VxgUAAeAQBl6E4BBg
hJj+T0oGAFFKBgBvKACHaAAAAACISAAAAQCn8AEAAAAXkAAAAAAAAAAAAAAA
AAAAAAAAABUYAAAPhLATEYSY/hXGBQABsBMGXoSwE2CEmP5PSgEAUUoBAG8o
AIdoAAAAAIhIAAABALfwAQAAABeQAAAAAAAAAAAAAAAAAAAAAAAAGRgAAA+E
gBYRhJj+FcYFAAGAFgZehIAWYISY/k9KBwBRSgcAXkoHAG8oAIdoAAAAAIhI
AAABAG8AAQAAABeQAAAAAAAAAAAAAAAAAAAAAAAAFRgAAA+EUBkRhJj+FcYF
AAFQGQZehFAZYISY/k9KBgBRSgYAbygAh2gAAAAAiEgAAAEAp/ABAAAAFwAA
AAAAAAAAAAAAAAAAAAAAAAAVGAAAD4Q4BBGEmP4VxgUAATgEBl6EOARghJj+
T0oGAFFKBgBvKACHaAAAAACISAAAAQDY8AEAAAAXAAAAAAAAAAAAAAAAAAAA
AAAAABkYAAAPhAgHEYSY/hXGBQABCAcGXoQIB2CEmP5PSgcAUUoHAF5KBwBv
KACHaAAAAACISAAAAQBvAAEAAAAXAAAAAAAAAAAAAAAAAAAAAAAAABUYAAAP
hNgJEYSY/hXGBQAB2AkGXoTYCWCEmP5PSgYAUUoGAG8oAIdoAAAAAIhIAAAB
AKfwAQAAABcAAAAAAAAAAAAAAAAAAAAAAAAAFRgAAA+EqAwRhJj+FcYFAAGo
DAZehKgMYISY/k9KAQBRSgEAbygAh2gAAAAAiEgAAAEAt/ABAAAAFwAAAAAA
AAAAAAAAAAAAAAAAAAAZGAAAD4R4DxGEmP4VxgUAAXgPBl6EeA9ghJj+T0oH
AFFKBwBeSgcAbygAh2gAAAAAiEgAAAEAbwABAAAAFwAAAAAAAAAAAAAAAAAA
AAAAAAAVGAAAD4RIEhGEmP4VxgUAAUgSBl6ESBJghJj+T0oGAFFKBgBvKACH
aAAAAACISAAAAQCn8AEAAAAXAAAAAAAAAAAAAAAAAAAAAAAAABUYAAAPhBgV
EYSY/hXGBQABGBUGXoQYFWCEmP5PSgEAUUoBAG8oAIdoAAAAAIhIAAABALfw
AQAAABcAAAAAAAAAAAAAAAAAAAAAAAAAGRgAAA+E6BcRhJj+FcYFAAHoFwZe
hOgXYISY/k9KBwBRSgcAXkoHAG8oAIdoAAAAAIhIAAABAG8AAQAAABcAAAAA
AAAAAAAAAAAAAAAAAAAAFRgAAA+EuBoRhJj+FcYFAAG4GgZehLgaYISY/k9K
BgBRSgYAbygAh2gAAAAAiEgAAAEAp/ABAAAAAAABAAAAAAAAAAAAAAAAAAAA
AAAKGAAAD4RACxGEmP4VxgUAAUALBl6EQAtghJj+h2gAAAAAiEgAAAIAAAAu
AAEAAAAEAAEAAAAAAAAAAAAAAAAAAAAAAAoYAAAPhBAOEYSY/hXGBQABEA4G
XoQQDmCEmP6HaAAAAACISAAAAgABAC4AAQAAAAICAQAAAAAAAAAAAAAAAAAA
AAAAChgAAA+E4BARhEz/FcYFAAHgEAZehOAQYIRM/4doAAAAAIhIAAACAAIA
LgABAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAKGAAAD4SwExGEmP4VxgUAAbAT
Bl6EsBNghJj+h2gAAAAAiEgAAAIAAwAuAAEAAAAEAAEAAAAAAAAAAAAAAAAA
AAAAAAoYAAAPhIAWEYSY/hXGBQABgBYGXoSAFmCEmP6HaAAAAACISAAAAgAE
AC4AAQAAAAICAQAAAAAAAAAAAAAAAAAAAAAAChgAAA+EUBkRhEz/FcYFAAFQ
GQZehFAZYIRM/4doAAAAAIhIAAACAAUALgABAAAAAAABAAAAAAAAAAAAAAAA
AAAAAAAKGAAAD4QgHBGEmP4VxgUAASAcBl6EIBxghJj+h2gAAAAAiEgAAAIA
BgAuAAEAAAAEAAEAAAAAAAAAAAAAAAAAAAAAAAoYAAAPhPAeEYSY/hXGBQAB
8B4GXoTwHmCEmP6HaAAAAACISAAAAgAHAC4AAQAAAAICAQAAAAAAAAAAAAAA
AAAAAAAAChgAAA+EwCERhEz/FcYFAAHAIQZehMAhYIRM/4doAAAAAIhIAAAC
AAgALgABAAAAAAABAAAAAAAAAAAAAAAAAAAAAAADGAAAD4TQAhGEmP4VxgUA
AdACBl6E0AJghJj+bygAAgAAAC4AAQAAAASAAQAAAAAAAAAAAAAAAAAAAAAA
ABgAAA+EoAURhJj+FcYFAAGgBQZehKAFYISY/gIAAQAuAAEAAAACggEAAAAA
AAAAAAAAAAAAAAAAAAAYAAAPhHAIEYRM/xXGBQABcAgGXoRwCGCETP8CAAIA
LgABAAAAAIABAAAAAAAAAAAAAAAAAAAAAAAAGAAAD4RACxGEmP4VxgUAAUAL
Bl6EQAtghJj+AgADAC4AAQAAAASAAQAAAAAAAAAAAAAAAAAAAAAAABgAAA+E
EA4RhJj+FcYFAAEQDgZehBAOYISY/gIABAAuAAEAAAACggEAAAAAAAAAAAAA
AAAAAAAAAAAYAAAPhOAQEYRM/xXGBQAB4BAGXoTgEGCETP8CAAUALgABAAAA
AIABAAAAAAAAAAAAAAAAAAAAAAAAGAAAD4SwExGEmP4VxgUAAbATBl6EsBNg
hJj+AgAGAC4AAQAAAASAAQAAAAAAAAAAAAAAAAAAAAAAABgAAA+EgBYRhJj+
FcYFAAGAFgZehIAWYISY/gIABwAuAAEAAAACggEAAAAAAAAAAAAAAAAAAAAA
AAAYAAAPhFAZEYRM/xXGBQABUBkGXoRQGWCETP8CAAgALgABAAAAFwAAAAAA
AAAAAAAAAAAAAAAAAAALGAAAD4SgBRGEmP4VxgUAAaAFBl6EoAVghJj+T0oB
AFFKAQBvKAABALfwAQAAABeAAAAAAAAAAAAAAAAAAAAAAAAACxgAAA+EcAgR
hJj+FcYFAAFwCAZehHAIYISY/k9KBwBRSgcAbygAAQBvAAEAAAAXgAAAAAAA
AAAAAAAAAAAAAAAAAAsYAAAPhEALEYSY/hXGBQABQAsGXoRAC2CEmP5PSgYA
UUoGAG8oAAEAp/ABAAAAF4AAAAAAAAAAAAAAAAAAAAAAAAALGAAAD4QQDhGE
mP4VxgUAARAOBl6EEA5ghJj+T0oBAFFKAQBvKAABALfwAQAAABeAAAAAAAAA
AAAAAAAAAAAAAAAACxgAAA+E4BARhJj+FcYFAAHgEAZehOAQYISY/k9KBwBR
SgcAbygAAQBvAAEAAAAXgAAAAAAAAAAAAAAAAAAAAAAAAAsYAAAPhLATEYSY
/hXGBQABsBMGXoSwE2CEmP5PSgYAUUoGAG8oAAEAp/ABAAAAF4AAAAAAAAAA
AAAAAAAAAAAAAAALGAAAD4SAFhGEmP4VxgUAAYAWBl6EgBZghJj+T0oBAFFK
AQBvKAABALfwAQAAABeAAAAAAAAAAAAAAAAAAAAAAAAACxgAAA+EUBkRhJj+
FcYFAAFQGQZehFAZYISY/k9KBwBRSgcAbygAAQBvAAEAAAAXgAAAAAAAAAAA
AAAAAAAAAAAAAAsYAAAPhCAcEYSY/hXGBQABIBwGXoQgHGCEmP5PSgYAUUoG
AG8oAAEAp/ABAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAZGAAAD4TYABGEKP8V
xgUAAdgABl6E2ABghCj/NQgBNggAQ0oWAE9KAQBRSgEAYUoWAG8oAAEAt/AB
AAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAZGAAAD4SgBRGEmP4VxgUAAaAFBl6E
oAVghJj+NQgBNggAQ0oWAE9KAQBRSgEAYUoWAG8oAAEAt/ABAAAAF4AAAAAA
AAAAAAAAAAAAAAAAAAALGAAAD4RwCBGEmP4VxgUAAXAIBl6EcAhghJj+T0oG
AFFKBgBvKAABAKfwAQAAABeAAAAAAAAAAAAAAAAAAAAAAAAACxgAAA+EQAsR
hJj+FcYFAAFACwZehEALYISY/k9KAQBRSgEAbygAAQC38AEAAAAXgAAAAAAA
AAAAAAAAAAAAAAAAAA8YAAAPhBAOEYSY/hXGBQABEA4GXoQQDmCEmP5PSgcA
UUoHAF5KBwBvKAABAG8AAQAAABeAAAAAAAAAAAAAAAAAAAAAAAAACxgAAA+E
4BARhJj+FcYFAAHgEAZehOAQYISY/k9KBgBRSgYAbygAAQCn8AEAAAAXgAAA
AAAAAAAAAAAAAAAAAAAAAAsYAAAPhLATEYSY/hXGBQABsBMGXoSwE2CEmP5P
SgEAUUoBAG8oAAEAt/ABAAAAF4AAAAAAAAAAAAAAAAAAAAAAAAAPGAAAD4SA
FhGEmP4VxgUAAYAWBl6EgBZghJj+T0oHAFFKBwBeSgcAbygAAQBvAAEAAAAX
gAAAAAAAAAAAAAAAAAAAAAAAAAsYAAAPhFAZEYSY/hXGBQABUBkGXoRQGWCE
mP5PSgYAUUoGAG8oAAEAp/ABAAAAFxAAAAAAAAAAAAAAAAAAAAAAAAAVGAAA
D4QgARGE4P4VxgUAASABBl6EIAFghOD+T0oGAFFKBgBvKACHaAAAAACISAAA
AQB38AEAAAAXEAAAAAAAAAAAAAAAAAAAAAAAABkYAAAPhKAFEYSY/hXGBQAB
oAUGXoSgBWCEmP5PSgcAUUoHAF5KBwBvKACHaAAAAACISAAAAQBvAAEAAAAX
kAAAAAAAAAAAAAAAAAAAAAAAABUYAAAPhHAIEYSY/hXGBQABcAgGXoRwCGCE
mP5PSgYAUUoGAG8oAIdoAAAAAIhIAAABAKfwAQAAABeQAAAAAAAAAAAAAAAA
AAAAAAAAFRgAAA+EQAsRhJj+FcYFAAFACwZehEALYISY/k9KAQBRSgEAbygA
h2gAAAAAiEgAAAEAt/ABAAAAF5AAAAAAAAAAAAAAAAAAAAAAAAAZGAAAD4QQ
DhGEmP4VxgUAARAOBl6EEA5ghJj+T0oHAFFKBwBeSgcAbygAh2gAAAAAiEgA
AAEAbwABAAAAF5AAAAAAAAAAAAAAAAAAAAAAAAAVGAAAD4TgEBGEmP4VxgUA
AeAQBl6E4BBghJj+T0oGAFFKBgBvKACHaAAAAACISAAAAQCn8AEAAAAXkAAA
AAAAAAAAAAAAAAAAAAAAABUYAAAPhLATEYSY/hXGBQABsBMGXoSwE2CEmP5P
SgEAUUoBAG8oAIdoAAAAAIhIAAABALfwAQAAABeQAAAAAAAAAAAAAAAAAAAA
AAAAGRgAAA+EgBYRhJj+FcYFAAGAFgZehIAWYISY/k9KBwBRSgcAXkoHAG8o
AIdoAAAAAIhIAAABAG8AAQAAABeQAAAAAAAAAAAAAAAAAAAAAAAAFRgAAA+E
UBkRhJj+FcYFAAFQGQZehFAZYISY/k9KBgBRSgYAbygAh2gAAAAAiEgAAAEA
p/ABAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAALGAAAD4SgBRGEmP4VxgUAAaAF
Bl6EoAVghJj+T0oBAFFKAQBvKAABALfwAQAAABeAAAAAAAAAAAAAAAAAAAAA
AAAADxgAAA+EcAgRhJj+FcYFAAFwCAZehHAIYISY/k9KBwBRSgcAXkoHAG8o
AAEAbwABAAAAF4AAAAAAAAAAAAAAAAAAAAAAAAALGAAAD4RACxGEmP4VxgUA
AUALBl6EQAtghJj+T0oGAFFKBgBvKAABAKfwAQAAABeAAAAAAAAAAAAAAAAA
AAAAAAAACxgAAA+EEA4RhJj+FcYFAAEQDgZehBAOYISY/k9KAQBRSgEAbygA
AQC38AEAAAAXgAAAAAAAAAAAAAAAAAAAAAAAAA8YAAAPhOAQEYSY/hXGBQAB
4BAGXoTgEGCEmP5PSgcAUUoHAF5KBwBvKAABAG8AAQAAABeAAAAAAAAAAAAA
AAAAAAAAAAAACxgAAA+EsBMRhJj+FcYFAAGwEwZehLATYISY/k9KBgBRSgYA
bygAAQCn8AEAAAAXgAAAAAAAAAAAAAAAAAAAAAAAAAsYAAAPhIAWEYSY/hXG
BQABgBYGXoSAFmCEmP5PSgEAUUoBAG8oAAEAt/ABAAAAF4AAAAAAAAAAAAAA
AAAAAAAAAAAPGAAAD4RQGRGEmP4VxgUAAVAZBl6EUBlghJj+T0oHAFFKBwBe
SgcAbygAAQBvAAEAAAAXgAAAAAAAAAAAAAAAAAAAAAAAAAsYAAAPhCAcEYSY
/hXGBQABIBwGXoQgHGCEmP5PSgYAUUoGAG8oAAEAp/APAAAAwmiYMAAAAAAA
AAAAAAAAAJgNoQIAAAAAAAAAAAAAAADfObVOAAAAAAAAAAAAAAAAtRmIGgAA
AAAAAAAAAAAAAGdGlnEAAAAAAAAAAAAAAACuSwElAAAAAAAAAAAAAAAAuC+g
bwAAAAAAAAAAAAAAAF5zQWAAAAAAAAAAAAAAAACdMQA/AAAAAAAAAAAAAAAA
DiW1MQAAAAAQqbECCQD+AAIjcTQAAAAAIKixAgkA/gBxZPkIAAAAAICssQIJ
AP4AcWT5CAAAAAAAAAAAAAAAAAIjcTQAAAAAAAAAAAAAAADTQA4WAAAAAAAA
AAAAAAAA////////////////////////////////////////////////////
/wEAAABAO30NAQAAAEFlbDkBAAAAQi1udQEAAABDb21hAQAAAERvLWwBAAAA
RTo1LgEAAABGZXZlAQAAAEd0aW8BAAAASHJnaf////8BAAAAEAAAAAEAAAAR
AAAAAQAAABIAAAABAAAAEwAAAAEAAAAUAAAAAQAAABUAAAABAAAAFgAAAAEA
AAAXAAAAAQAAABgAAAD/////AQAAAEBsc2UBAAAAQWhlbgEAAAACTmFtAQAA
AEN0IDIBAAAABAogIAEAAABFb24gAQAAAEYiIFABAAAAB1NlbQEAAABIZSIN
//////////////////8NAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/
/w0AAAASAKp8dOYBAAlABQAJBAEACQQDAAkEBQAJBAEACQQDAAkEBQAJBBIA
CwAJBAMACQQFAAkEAQAJBAMACQQFAAkEAQAJBAMACQQFAAkEEgABAAAAAwAJ
BAUACQQBAAkEAwAJBAUACQQBAAkEAwAJBAUACQQSAAEACQQDAAkEBQAJBAEA
CQQDAAkEBQAJBAEACQQDAAkEBQAJBBIABQAJBAMACQQFAAkEAQAJBAMACQQF
AAkEAQAJBAMACQQFAAkEEgABAAAAAwAJBAUACQQBAAkEAwAJBAUACQQBAAkE
AwAJBAUACQQSAAsACQQDAAkEBQAJBAEACQQDAAkEBQAJBAEACQQDAAkEBQAJ
BBIAwHzADBkACQQbAAkEDwAJBBkACQQbAAkEDwAJBBkACQQbAAkEEgCKjlQ+
GQAJBBsACQQPAAkEGQAJBBsACQQPAAkEGQAJBBsACQQSAAEACQQDAAkEBQAJ
BAEACQQDAAkEBQAJBAEACQQDAAkEBQAJBBIAqnx05gEACUAFAAkEAQAJBAMA
CQQFAAkEAQAJBAMACQQFAAkEEgAM0qx7AwAJBAUACQQBAAkEAwAJBAUACQQB
AAkEAwAJBAUACQQSAFjo4PoDAAkEBQAJBAEACQQDAAkEBQAJBAEACQQDAAkE
BQAJBAMAMHUrDAAAAAAAAAAAAAECAAIANiNxegAAAAAAAAAAAAECAAIAaypl
fwAAAAAAAAAAAAECAAIAMAAAAAQAAAAIAAAA5QAAAAAAAAAvAAAAnCoEAHtz
BQCTeAgA9BoKAG0CDADgDA4AUmEOAH5LEACoZBsA/RQeALEuJACNTjIA0HY+
AKMFSgA8MUoAtGlOAOgcUgB+HVsA0zZlAApzbQDUQHcACWeEAEB9kQCvfpMA
bheWAF9zlgAiKJcA5jCcAOVcoAABUqIAvkayAFdjtwAdMbgAB1q5AMQXvwDy
H78ARSfEAKc6yQAFVNAAMxzUAMgV2gBxQNsA2CPcAJQD4ADaHuAAIgThAA15
9ADcfPUAAAAAANoKAADcCgAAAAAAAAEAAAD/QAGAAQBlCAAAZQgAAAAoGQLf
AN8AZQgAAAAAAABlCAAAAAAAAAIQAAAAAAAAANoKAABYAAAQAEAAAP//AQAA
AAcAVQBuAGsAbgBvAHcAbgD//wEACAAAAAAAAAAAAAAA//8BAAAAAAD//wAA
AgD//wAAAAD//wAAAgD//wAAAAAJAAAARx6QAQAAAgIGAwUEBQIDBO8qAOBB
eADACQAAAAAAAAD/AQAAAAAAAFQAaQBtAGUAcwAgAE4AZQB3ACAAUgBvAG0A
YQBuAAAANR6QAQIABQUBAgEHBgIFBwAAAAAAAAAQAAAAAAAAAAAAAACAAAAA
AFMAeQBtAGIAbwBsAAAAMy6QAQAAAgsGBAICAgICBP8qAOBDeADACQAAAAAA
AAD/AQAAAAAAAEEAcgBpAGEAbAAAAEsekAEAAAIEBQIFBQUDAwSHAgDgEwAA
QAAAAAAAAAAAnwEAAAAAAABQAGEAbABhAHQAaQBuAG8AIABMAGkAbgBvAHQA
eQBwAGUAAAA3LpABAAACCwYEAwUEBAIE/wYAoVsgAEAQAAAAAAAAAJ8BAAAA
AAAAVgBlAHIAZABhAG4AYQAAADUukAEAAAILBgQDBQQEAgT/KgDhW2AAwCkA
AAAAAAAA/wEBAAAAAABUAGEAaABvAG0AYQAAADsOkAECAAUAAAAAAAAAAAAA
AAAAAAAAEAAAAAAAAAAAAAAAgAAAAABXAGkAbgBnAGQAaQBuAGcAcwAAAD89
kAEAAAIHAwkCAgUCBAT/KgDgQ3gAwAkAAAAAAAAA/wEAAAAAAABDAG8AdQBy
AGkAZQByACAATgBlAHcAAABBHpABAAACBAUDBQQGAwIE7wIAoOsgAEIAAAAA
AAAAAJ8AAAAAAAAAQwBhAG0AYgByAGkAYQAgAE0AYQB0AGgAAAAiAAQAcQiI
GADw0AIAAGgBAAAAAF018YZdNfGGAAAAAAIABAAAAJ4BAAA8CQAAAgAFAAAA
BAADEBMAAACeAQAAPAkAAAIABQAAABMAAAAAAAAAIQMA8BAAAAABAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8APwA7QAtACBgTI0
AAAAAAAAAAAAAAAAAADVCgAA1QoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAA
AAAMMoNxAPAQAAgA//0BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACEhYAAAA
AAnw/w8BCAE/AADkBAAA////f////3////9/////f////3////9/////f5N4
CAAABAAAMgAAAAAAAAAAAAAAAAAAAAAAAAAAACEEAAAAAAAAAAAAAAAAAAAA
AAAAEBwAAAgAAAAAAAAAAAB4AAAAeAAAAAAAAAAAAAAAoAUAAP//EgAAAAAA
AAADAEoATQBLAAAAAAAAAAMASgBNAEsAEABTAG8AbgB5ACAATgAxADEASAAg
ADEANQA5ADcAMwAxAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAYAAAANAAAA
AAAMAAEADAACAAwAAwAMAAQADAAFAAwABgAMAAcADAAIAAwACQAMAAoADAAL
AAwADAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+/wAABgACAAAAAAAAAAAAAAAA
AAAAAAABAAAA4IWf8vlPaBCrkQgAKyez2TAAAAA0AQAADgAAAAEAAAB4AAAA
AgAAAIAAAAAEAAAAjAAAAAcAAACYAAAACAAAAKgAAAAJAAAAxAAAABIAAADQ
AAAACgAAAPAAAAAMAAAA/AAAAA0AAAAIAQAADgAAABQBAAAPAAAAHAEAABAA
AAAkAQAAEwAAACwBAAACAAAA5AQAAB4AAAAEAAAASk1LAB4AAAAEAAAASk1L
AB4AAAAIAAAATm9ybWFsAAAeAAAAFAAAAFNvbnkgTjExSCAxNTk3MzEAAAAA
HgAAAAQAAAAyAAAAHgAAABgAAABNaWNyb3NvZnQgT2ZmaWNlIFdvcmQAAABA
AAAAABgNjwAAAABAAAAAAP5WpBKuywFAAAAAAP5WpBKuywEDAAAAAgAAAAMA
AACeAQAAAwAAADwJAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v8AAAYAAgAAAAAAAAAAAAAA
AAAAAAAAAQAAAALVzdWcLhsQk5cIACss+a4wAAAABAEAAAwAAAABAAAAaAAA
AA8AAABwAAAABQAAAJQAAAAGAAAAnAAAABEAAACkAAAAFwAAAKwAAAALAAAA
tAAAABAAAAC8AAAAEwAAAMQAAAAWAAAAzAAAAA0AAADUAAAADAAAAOQAAAAC
AAAA5AQAAB4AAAAcAAAASW5mb2VkZ2UgSW5kaWEgUHZ0LiBMdGQuAAAAAAMA
AAATAAAAAwAAAAUAAAADAAAA1QoAAAMAAAAAAAwACwAAAAAAAAALAAAAAAAA
AAsAAAAAAAAACwAAAAAAAAAeEAAAAQAAAAQAAABKTUsADBAAAAIAAAAeAAAA
BgAAAFRpdGxlAAMAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAACAAAAAwAAAAQAAAAF
AAAABgAAAAcAAAAIAAAACQAAAAoAAAALAAAADAAAAA0AAAAOAAAADwAAABAA
AAARAAAAEgAAABMAAAAUAAAAFQAAABYAAAAXAAAAGAAAABkAAAAaAAAAGwAA
ABwAAAD+////HgAAAB8AAAAgAAAAIQAAACIAAAAjAAAAJAAAAP7///8mAAAA
JwAAACgAAAApAAAAKgAAACsAAAAsAAAALQAAAC4AAAAvAAAAMAAAADEAAAAy
AAAAMwAAADQAAAA1AAAANgAAADcAAAA4AAAAOQAAADoAAAA7AAAAPAAAAD0A
AAA+AAAAPwAAAEAAAABBAAAAQgAAAEMAAABEAAAARQAAAEYAAABHAAAA/v//
/0kAAABKAAAASwAAAEwAAABNAAAATgAAAE8AAAD+////UQAAAFIAAABTAAAA
VAAAAFUAAABWAAAAVwAAAP7////9////WgAAAP7////+/////v//////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
UgBvAG8AdAAgAEUAbgB0AHIAeQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAABYABQH//////////wMAAAAGCQIAAAAAAMAA
AAAAAABGAAAAAAAAAAAAAAAA0JTutBKuywFcAAAAgAAAAAAAAABEAGEAdABh
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAACgACAf///////////////wAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAB0AAAAAEAAAAAAAADEAVABhAGIAbABlAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAOAAIBAQAAAAYAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAJQAAAFhEAAAAAAAAVwBvAHIAZABEAG8AYwB1AG0AZQBu
AHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoA
AgECAAAABQAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAgDgAAAAAAAAFAFMAdQBtAG0AYQByAHkASQBuAGYAbwByAG0A
YQB0AGkAbwBuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAACAf//////
/////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEgA
AAAAEAAAAAAAAAUARABvAGMAdQBtAGUAbgB0AFMAdQBtAG0AYQByAHkASQBu
AGYAbwByAG0AYQB0AGkAbwBuAAAAAAAAAAAAAAA4AAIBBAAAAP//////////
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAQAAAA
AAAAAQBDAG8AbQBwAE8AYgBqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAAgD///////////////8AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeQAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAP///////////////wAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAD+////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////AQD+/wMKAAD/////BgkCAAAAAADAAAAAAAAARicAAABNaWNyb3Nv
ZnQgT2ZmaWNlIFdvcmQgOTctMjAwMyBEb2N1bWVudAAKAAAATVNXb3JkRG9j
ABAAAABXb3JkLkRvY3VtZW50LjgA9DmycQAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

--0-1837947753-1295666969=:73308--
