Return-Path: info@modernfinancereport.com
Received: from mx89.stngva01.us.mxservers.net (198.173.112.6)
	by mail19k.g19.rapidsite.net (RS ver 1.0.95vs) with SMTP id 1-0601964891
	for <jayanthi@altechstar.com>; Tue,  1 Mar 2011 05:21:31 -0500 (EST)
Received: from unknown [208.84.243.183] (EHLO if04-mail-fb09-mia.mta.terra.com)
	by va1-mx89.stngva01.us.mxservers.net (mxl_mta-3.1.0-05)
	with ESMTP id ba8cc6d4.1910434720.148895.00-004.va1-mx89.stngva01.us.mxservers.net (envelope-from <alvaronavarro@speedy.com.ar>);
	Tue, 01 Mar 2011 05:21:31 -0500 (EST)
Received: from midland.terra.com (midland.tpn.terra.com [10.235.200.8])
	by mail-fb09-mia.tpn.terra.com (Postfix) with ESMTP id F024F7676;
	Tue,  1 Mar 2011 10:03:13 +0000 (UTC)
X-Terra-Karma:          0%
X-Terra-Hash: 1f63604fb5d7605aa6e84a3853fcbe82
Received-SPF: pass (midland.terra.com: domain of speedy.com.ar designates 208.84.242.62 as permitted sender) client-ip=208.84.242.62; envelope-from=alvaronavarro@speedy.com.ar; helo=sarita;
Received: from sarita (unknown [190.234.218.105])
	(authenticated user alvaronavarro@speedy.com.ar)
	by midland.terra.com (Postfix) with ESMTPA id AE64AC58E7B5;
	Tue,  1 Mar 2011 10:03:09 +0000 (UTC)
Message-ID: <002301cbd85c$bbec0a5b$2dca9e0d@qvrrqywd>
Reply-To: "Modern Finance Report" <info@modernfinancereport.com>
From: "Modern Finance Report" <alvaronavarro@speedy.com.ar>
To: <sandraloyola@terra.com.pe>
Subject: 20% Discount at Workshops in New York, Sydney, Singapore, Hong Kong and Mumbai
Date: Tue, 1 Mar 2011 05:02:52 -0500
MIME-Version: 1.0
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: 7bit
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2900.2180
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2900.2180
X-CLX-Rate-Response: fi=10.235.200.253:2001; rg=B; GT=0; fs=1011; PS=jayanthi@altechstar.com:0,jayant@danr.com:0,jayan.kalathil@vh1staff.com:0,jay_siu@msn.com:0,jay_xie@alibaba-inc.com:0,jayalex80@aol.com:0,jay0419@cm1.hinet.net:0,jayac@dbsinyc.com:0,jay_teborek@yahoo.com:0,jayagopal@nmc.ae:0; ns=0; id=a123GLF880yS0VH-211003D; rv=6379/208.84.242.253:14051; ts=Eomj8; fl=IAI; ip=190.234.218.105; he=P16L6a5ZBZj; nr=10; ho=K79nVLmQ9M5; hd=PSGRXrlw5k3; hf=NkdzCm9M/99; hF=M0K5d4oGtbr; hj=DFZDpaZltF0; ZM=CHSmrRTQ2yw; ZB=JWu0+CaLqaO; ZB=BjWPGCvp5WD; ZB=C8COavjguNf; ZB=FYzxYY6of3g; ZB=F/jXjw7O2QY; ZU=Hr459hHtZWv; Zu=MtD9a9Skpxj; ZU=PJDBAXNxtcx; Zu=H4brl97Bb9B; ZU=PM/vDl57mWB; Zu=K3FvvKA+lUf; Zu=IPe8VWUHA7+; Zu=BKOm39mODIY; ZU=ObWM+Kwd+za; Zu=J24NqYSxYRR; ZF=OP/3hn88IFq;
X-Spam: [F=0.2000000000; B=0.500(0); S=0.200(2010122901); MH=0.500(2011030106)]
X-MAIL-FROM: <alvaronavarro@speedy.com.ar>
X-SOURCE-IP: [208.84.243.183]
X-SF-Loop: 1

<table border="0" cellspacing="0" cellpadding="0" width="770" align="center">
<tbody>
<tr>
<td>
<div id="masthead" style="font-size: xx-small; border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px 0px 0px; vertical-align: baseline; text-align: center;"><a title="High-Frequency Trading Experts Workshop 2011" href="http://www.HFTExpertsWorkshop.com" target="_blank"><img style="border: 0; display: block; margin-left: auto; margin-right: auto;" src="http://ultrahighfrequencytrading.files.wordpress.com/2011/02/hftewhead940198.jpg" alt="High-Frequency Trading Experts Workshop 2011" width="770" /></a><br />If you are having trouble   viewing this email, <a title="Modern Finance Report" href="http://modernfinancereport.com/" target="_blank">click here</a></div>
<div id="masthead" style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px 0px 0px; vertical-align: baseline;"><br />
<h1 id="site-title" style="border-width: 0px; font-family: 'Helvetica Neue',Arial,Helvetica,'Nimbus Sans L',sans-serif; font-style: inherit; font-weight: bold; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #000000; text-rendering: optimizelegibility; letter-spacing: -0.03em; font-size: 36px; line-height: 42px; text-align: center;"><span style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline;"><a style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: bold; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #000000; text-decoration: none;" title="Modern Finance Report" rel="home" href="http://modernfinancereport.com/">Modern Finance Report</a></span></h1>
<div id="site-description" style="border-width: 0px; font-family: 'Helvetica Neue',Arial,Helvetica,'Nimbus Sans L',sans-serif; font-style: inherit; font-weight: inherit; margin: 0px 0px 9px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #000000; font-size: 18px; text-align: center;">How Modern Finance is Impacting the Business World<br />Special Promotional   Edition</div>
</div>
<div id="access" style="border-width: 1px 0px 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px auto; outline-width: 0px; padding: 1px 0px 0px; vertical-align: baseline; border-top: 1px solid #cccccc; display: block; float: left; width: 770px;">
<div class="menu" style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline;">
<ul style="border-width: 0px; font-family: 'Helvetica Neue',Arial,Helvetica,'Nimbus Sans L',sans-serif; font-style: inherit; font-weight: bold; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; list-style-type: none; font-size: 13px; text-transform: uppercase;">
<li class="current_page_item" style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; float: left; position: relative;"><span style="color: #000000;"><a style="border-width: 0px; font-family: inherit; font-style: inherit; font-  weight: inherit; margin: 0px 1px 0px   0px; outline-width: 0px; padding: 0.25em 1em 0px; vertical-align: baseline; color: #ffffff; display: block; line-height: 2em; text-decoration: none; background-color: #000000;" title="Home" href="http://modernfinancereport.com/">HOME</a></span></li>
<li class="page_item page-item-2" style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; float: left; position: relative;"><span style="color: #000000;"><a style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px 1px 0px 0px; outline-width: 0px; padding: 0.25em 1em 0px; vertical-align: baseline; color: #000000; display: block; line-height: 2em; text-decoration: none;" title="About" href="http://modernfinancereport.com/about/">ABOUT</a></span></li>
</ul>
</div>
<div id="branding" style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline;"><a style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical  -align: baseline; color: #df0000;" href="http://modernfinancereport.com/"><img style="border: 0;" src="http://modernfinancereport.files.wordpress.com/2011/01/cropped-footer7701401.jpg" alt="Modern Finance Report" width="770" /></a></div>
<br /> 
<table id="speakers" cellspacing="0" cellpadding="5" width="770">
<tbody>
<tr>
<td class="text2" width="256" align="center" valign="top">
<h3 class="widget-title" style="border-width: 3px 0px 1px; font-family: 'Helvetica Neue',Arial,Helvetica,'Nimbus Sans L',sans-serif; font-style: inherit; font-weight: bold; margin: 0px 0px   8px; outline-width: 0px; padding: 2px; vertical-align: baseline; color: #000000; text-rendering: optimizelegibility; border-bottom: 1px solid   #cccccc; border-top: 3px solid #000000; font-  size: 13px; letter-spacing: 0.025em; text-transform: uppercase; text-align: left;">SEARCH</h3>
<form id="searchform" style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline;" action="http://modernfinancereport.com/" method="get">
<div style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline;"><label class="screen-  reader-text" style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; position: absolute; left: -1000em;" for="s">Search for:</label><input id="s" style="color: #333333; font: 12px/18px   Georgia,'Bitstream Charter',serif; border: 1px solid #888888; padding: 3px; width: 140px;" name="s" type="text" /><span>&nbsp;</span><input id="searchsubmit" style="color: #333333; font: 12px/18px Georgia,'Bitstream Charter',serif;" type="submit" value="Search" /></div>
</form>
<h3 class="widget-title" style="border-width: 3px 0px 1px; font-family: 'Helvetica Neue',Arial,Helvetica,'Nimbus Sans L',sans-serif; font-style: inherit; font-weight: bold; margin: 0px 0px   8px; outline-width: 0px; padding: 2px; vertical-align: baseline; color: #000000; text-rendering: optimizelegibility; border-bottom: 1px solid   #cccccc; border-top: 3px solid #000000; font-  size: 13px; letter-spacing: 0.025em; text-transform: uppercase; text-align: left;">RECENT ENTRIES</h3>
<ul>
<li style="text-align: left;"><a title="Tokyo Bourse Updates Indexes Every Millisecond to Lure&nbsp;Traders" href="http://modernfinancereport.wordpress.com/2011/02/28/tokyo-bourse-updates-indexes-every-millisecond-to-lure-traders/">Tokyo Bourse Updates Indexes Every Millisecond to Lure&nbsp;Traders</a></li>
<li style="text-align: left;"><a title="Time for Next Move on Yuan&nbsp;Liberalization" href="http://modernfinancereport.wordpress.com/2011/02/28/time-for-next-move-on-yuan-liberalization/">Time for Next Move on Yuan&nbsp;Liberalization</a></li>
<li style="text-align: left;"><a title="Economists list U.S. budget deficit as No. 1 worry" href="http://modernfinancereport.wordpress.com/2011/02/28/economists-list-u-s-budget-deficit-as-no-1-worry/" target="_blank">Economists list U.S. budget deficit as No. 1 worry</a></li>
<li style="text-align: left;"><a title="Mergers loom as &ldquo;flash crash&rdquo; back in&nbsp;spotlight" href="http://modernfinancereport.wordpress.com/2011/02/18/mergers-loom-as-flash-crash-back-in-spotlight/">Mergers loom as &ldquo;flash crash&rdquo; back in&nbsp;spotlight</a></li>
<li style="text-align: left;"><a title="Banks Find Loophole on Capital&nbsp;Rule" href="http://modernfinancereport.wordpress.com/2011/02/18/banks-find-loophole-on-capital-rule/">Banks Find Loophole on Capital&nbsp;Rule</a></li>
<li style="text-align: left;"><a title="China flexed its muscles using U.S.&nbsp;Treasuries" href="http://modernfinancereport.wordpress.com/2011/02/18/china-flexed-its-muscles-using-u-s-treasuries/">China flexed its muscles using U.S.&nbsp;Treasuries</a></li>
<li style="text-align: left;"><a title="NYSE Deal Bears Big Breakup&nbsp;Fee" href="http://modernfinancereport.wordpress.com/2011/02/18/nyse-deal-bears-big-breakup-fee/">NYSE Deal Bears Big   Breakup&nbsp;Fee</a></li>
</ul>
<h3 class="widget-title" style="border-width: 3px 0px 1px; font-family: 'Helvetica Neue',Arial,Helvetica,'Nimbus Sans L',sans-serif; font-style: inherit; font-weight: bold; margin: 0px 0px   8px; outline-width: 0px; padding: 2px; vertical-align: baseline; color: #000000; text-rendering: optimizelegibility; border-bottom: 1px solid   #cccccc; border-top: 3px solid #000000; font-  size: 13px; letter-spacing: 0.025em; text-transform: uppercase; text-align: left;">HIGH-FREQUENCY TRADING EXPERTS WORKSHOP 2011</h3>
<div style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; overflow: hidden;"><a style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #0060ff;" href="http://www.hftexpertsworkshop.com/"><img class="alignright" style="border-width: 0px; display: inline; border: 0;" title="High-Frequency Trading Experts Workshop 2011" src="http://www.goldennetworking.net/userfiles/image/Flyer199HEAD300300.jpg" alt="High-Frequency Trading Experts   Workshop 2011" width="236" /></a></div>
<h3 class="widget-title" style="border-width: 3px 0px 1px; font-family: 'Helvetica Neue',Arial,Helvetica,'Nimbus Sans L',sans-serif; font-style: inherit; font-weight: bold; margin: 0px 0px   8px; outline-width: 0px; padding: 2px; vertical-align: baseline; color: #000000; text-rendering: optimizelegibility; border-bottom: 1px solid   #cccccc; border-top: 3px solid #000000; font-  size: 13px; letter-spacing: 0.025em; text-transform: uppercase; text-align: left;">WORKSHOPS AND SEMINARS</h3>
<ul class="xoxo blogroll" style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px 0px 1.5em 1.5em; outline-width: 0px; padding: 0px; vertical-  align: baseline; list-style-type: square;">
<li style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 4px 0px; vertical-align: baseline; text-align: left;"><a style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #0060ff; text-decoration: none;" title="High-Frequency Trading Experts Workshop 2011, March 3-4, New York City" href="http://www.hftexpertsworkshop.com/" target="_blank">High-Frequency Trading Experts   Workshop 2011, March 3-4, New York City</a></li>
<li style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 4px 0px; vertical-align: baseline; text-align: left;"><a style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #0060ff; text-decoration: none;" title="High-Frequency Trading Experts Workshop 2011, March 14-15, Sydney" href="http://www.hftexpertsworkshop.com/" target="_blank">High-Frequency Trading Experts   Workshop 2011, March 14-15, Sydney</a></li>
<li style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 4px 0px; vertical-align: baseline; text-align: left;"><a style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #0060ff; text-decoration: none;" title="High-Frequency Trading Experts Workshop 2011, March 16-17, Singapore" href="http://www.hftexpertsworkshop.com/" target="_blank">High-Frequency Trading Experts   Workshop 2011, March 16-17, Singapore</a></li>
<li style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 4px 0px; vertical-align: baseline; text-align: left;"><a style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #0060ff; text-decoration: none;" title="Advanced Market Timing Experts Workshop 2011, March 21-22, Singapore" href="http://www.advancedmarkettiming.com/" target="_blank">Advanced Market Timing Experts   Workshop 2011, March 21-22, Singapore</a></li>
<li style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 4px 0px; vertical-align: baseline; text-align: left;"><a style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #0060ff; text-decoration: none;" title="Advanced Market Timing Experts Workshop 2011, March 24-25, Hong Kong" href="http://www.hftexpertsworkshop.com/" target="_blank">Advanced Market Timing Experts   Workshop 2011, March 24-25, Hong Kong</a></li>
<li style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 4px 0px; vertical-align: baseline; text-align: left;"><a style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #0060ff; text-decoration: none;" title="Offshore Yuan Trading Experts Workshop 2011, March 28-29, Hong Kong" href="http://offshoreyuantrading.com/" target="_blank">Offshore Yuan Trading Experts   Workshop 2011, March 28-29, Hong Kong</a></li>
<li style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 4px 0px; vertical-align: baseline; text-align: left;"><a style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #0060ff; text-decoration: none;" title="Modern Derivatives Trading Experts Workshop 2011, March 31-April 1, Hong Kong" href="http://modernderivativestrading.com/" target="_blank">Modern Derivatives   Trading Experts Workshop 2011, March 31-April 1, Hong Kong</a></li>
<li style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 4px 0px; vertical-align: baseline; text-align: left;"><a style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #0060ff; text-decoration: none;" title="High-Frequency Trading Experts Workshop 2011, April 7-8, Mumbai" href="http://www.hftexpertsworkshop.com/" target="_blank">High-Frequency Trading Experts   Workshop 2011, April 7-8, Mumbai</a></li>
</ul>
<h3 class="widget-title" style="border-width: 3px 0px 1px; font-family: 'Helvetica Neue',Arial,Helvetica,'Nimbus Sans L',sans-serif; font-style: inherit; font-weight: bold; margin: 0px 0px   8px; outline-width: 0px; padding: 2px; vertical-align: baseline; color: #000000; text-rendering: optimizelegibility; border-bottom: 1px solid   #cccccc; border-top: 3px solid #000000; font-  size: 13px; letter-spacing: 0.025em; text-transform: uppercase; text-align: left;">ADVANCED MARKET TIMING EXPERTS WORKSHOP   2011</h3>
<div style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; overflow: hidden;"><a style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #0060ff;" href="http://www.advancedmarkettiming.com/"><img class="alignright" style="border-width: 0px; display: inline; border: 0;" title="Advanced Market Timing Experts Workshop 2011" src="http://www.goldennetworking.net/userfiles/image/AMTEWBOX300300.jpg" alt="Advanced Market Timing Experts   Workshop 2011" width="236" /></a></div>
<h3 class="widget-title" style="border-width: 3px 0px 1px; font-family: 'Helvetica Neue',Arial,Helvetica,'Nimbus Sans L',sans-serif; font-style: inherit; font-weight: bold; margin: 0px 0px   8px; outline-width: 0px; padding: 2px; vertical-align: baseline; color: #000000; text-rendering: optimizelegibility; border-bottom: 1px solid   #cccccc; border-top: 3px solid #000000; font-  size: 13px; letter-spacing: 0.025em; text-transform: uppercase; text-align: left;">CONFERENCES AND FORUMS</h3>
<ul class="xoxo blogroll" style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px 0px 1.5em 1.5em; outline-width: 0px; padding: 0px; vertical-  align: baseline; list-style-type: square; text-align: left;">
<li style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 4px 0px; vertical-align: baseline;"><a style="border-  width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #0060ff; text-decoration: none;" title="High-Frequency Trading Leaders Forum 2011, May 16-18, New York City" href="http://www.hftleadersforum.com/" target="_blank">High-Frequency Trading Leaders Forum 2011, May 16-18, New   York City</a></li>
</ul>
<h3 class="widget-title" style="border-width: 3px 0px 1px; font-family: 'Helvetica Neue',Arial,Helvetica,'Nimbus Sans L',sans-serif; font-style: inherit; font-weight: bold; margin: 0px 0px   8px; outline-width: 0px; padding: 2px; vertical-align: baseline; color: #000000; text-rendering: optimizelegibility; border-bottom: 1px solid   #cccccc; border-top: 3px solid #000000; font-  size: 13px; letter-spacing: 0.025em; text-transform: uppercase; text-align: left;">OFFSHORE YUAN TRADING EXPERTS WORKSHOP   2011</h3>
<div style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; overflow: hidden;"><a style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #0060ff;" href="http://offshoreyuantrading.com/"><img class="alignright" style="border-width: 0px; display: inline; border: 0;" title="Offshore Yuan Trading Experts Workshop 2011" src="http://www.goldennetworking.net/userfiles/image/OYTBOX300300.jpg" alt="Offshore Yuan Trading Experts Workshop   2011" width="236" /></a></div>
<h3 class="widget-title" style="border-width: 3px 0px 1px; font-family: 'Helvetica Neue',Arial,Helvetica,'Nimbus Sans L',sans-serif; font-style: inherit; font-weight: bold; margin: 0px 0px   8px; outline-width: 0px; padding: 2px; vertical-align: baseline; color: #000000; text-rendering: optimizelegibility; border-bottom: 1px solid   #cccccc; border-top: 3px solid #000000; font-  size: 13px; letter-spacing: 0.025em; text-transform: uppercase; text-align: left;">NETWORKING RECEPTIONS</h3>
<ul class="xoxo blogroll" style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px 0px 1.5em 1.5em; outline-width: 0px; padding: 0px; vertical-  align: baseline; list-style-type: square; text-align: left;">
<li style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 4px 0px; vertical-align: baseline;"><a style="border-  width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #0060ff; text-decoration: none;" title="High-Frequency Trading Happy Hour, March 8, New York City" href="http://www.hfthappyhour.com/" target="_blank">High-Frequency Trading Happy Hour, March 8, New York City</a></li>
<li style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 4px 0px; vertical-align: baseline;"><a style="border-  width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #0060ff; text-decoration: none;" title="High-Frequency Trading Happy Hour, April 12, New York City" href="http://www.hfthappyhour.com/" target="_blank">High-Frequency Trading Happy Hour, April 12, New York City</a></li>
<li style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 4px 0px; vertical-align: baseline;"><a style="border-  width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #0060ff; text-decoration: none;" title="High-Frequency Trading Happy Hour, May 10, New York City" href="http://www.hfthappyhour.com/" target="_blank">High-Frequency Trading Happy Hour, May 10, New York City</a></li>
</ul>
<h3 class="widget-title" style="border-width: 3px 0px 1px; font-family: 'Helvetica Neue',Arial,Helvetica,'Nimbus Sans L',sans-serif; font-style: inherit; font-weight: bold; margin: 0px 0px   8px; outline-width: 0px; padding: 2px; vertical-align: baseline; color: #000000; text-rendering: optimizelegibility; border-bottom: 1px solid   #cccccc; border-top: 3px solid #000000; font-  size: 13px; letter-spacing: 0.025em; text-transform: uppercase; text-align: left;">MODERN DERIVATIVES TRADING EXPERTS WORKSHOP 2011</h3>
<div style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; overflow: hidden; text  -align: left;"><a style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline; color: #0060ff;" href="http://modernderivativestrading.com/"><img class="alignright" style="border-width: 0px; display: inline; border: 0;" title="Modern Derivatives Trading Experts Workshop 2011" src="http://www.goldennetworking.net/userfiles/image/MDTFlyerBOX300300.jpg" alt="Modern Derivatives   Trading Experts Workshop 2011" width="236" /></a></div>
<h3 class="widget-title" style="border-width: 3px 0px 1px; font-family: 'Helvetica Neue',Arial,Helvetica,'Nimbus Sans L',sans-serif; font-style: inherit; font-weight: bold; margin: 0px 0px   8px; outline-width: 0px; padding: 2px; vertical-align: baseline; color: #000000; text-rendering: optimizelegibility; border-bottom: 1px solid   #cccccc; border-top: 3px solid #000000; font-  size: 13px; letter-spacing: 0.025em; text-transform: uppercase; text-align: left;">ARCHIVES</h3>
<ul>
<li style="text-align: left;"><a title="February 2011" href="http://modernfinancereport.wordpress.com/2011/02/">February 2011</a></li>
<li style="text-align: left;"><a title="January 2011" href="http://modernfinancereport.wordpress.com/2011/01/">January 2011</a></li>
</ul>
</td>
<td class="text2" style="text-align: left;" width="514" align="center" valign="top">
<div class="entry-content"><span style="font-family: verdana, geneva; font-size: small;">Dear reader,</span></div>
<div class="entry-content">
<p><span style="font-family: verdana, geneva; font-size: small;"><strong>Did you ever ask yourself what would it take to develop a profitable high-frequency trading platform?    &nbsp;</strong></span></p>
<p><span style="font-family: verdana, geneva; font-size: small;">Peter van Kleef, one of the world's most renowned experts in trading technology and strategy, will conduct a 2-day     seminar, <a title="High-Frequency Trading Experts Workshop 2011" href="http://www.hftexpertsworkshop.com/" target="_blank">&nbsp;<strong>High-Frequency Trading Experts   Workshop 2011</strong></a>, in New York,   March 3 &amp; 4, Sydney, March 14 &amp; 15, Singapore, March 16 &amp; 17 and Mumbai, April 7 &amp; 8.&nbsp;Attending   this important workshop will allow you   to:</span></p>
<ul>
<li><span style="font-family: verdana, geneva; font-size: small;">Understand the requirements to develop sophisticated high-frequency trading platforms</span></li>
<li><span style="font-family: verdana, geneva; font-size: small;">Have a hands-on understanding of high-frequency trading in practice</span></li>
<li><span style="font-family: verdana, geneva; font-size: small;">Learn how to exploit market microstructure with high-frequency trading, and</span></li>
<li><span style="font-family: verdana, geneva; font-size: small;">Leverage alternative and new high-frequency strategies, including arbitrage, news and social networking   based.</span></li>
</ul>
<p><span style="font-family: verdana, geneva; font-size: small;">More information at&nbsp;<a title="http://www.hftexpertsworkshop.com/" href="http://www.hftexpertsworkshop.com/" target="_blank">http://www.HFTExpertsWorkshop.com</a>.</span></p>
<p>&nbsp;</p>
<p><span style="font-family: verdana, geneva; font-size: small;"><strong>Eager to sharpen your edge with Market Timing?</strong></span></p>
<p><span style="font-family: verdana, geneva; font-size: small;">If you are familiar with Technical Analysis and would like to sharpen your edge with the world's &nbsp;leading expert in   the   field, Trevor Neil,   &nbsp;then&nbsp;<strong><a title="Advanced Market Timing Experts Workshop 2011" href="http://www.advancedmarkettiming.com/" target="_blank">Advanced Market Timing     Experts Workshop 2011</a></strong> is for you. This workshop, to be held in&nbsp;Singapore, March 21 &amp; 22 and Hong Kong,   March 24 &amp; 25,&nbsp;is designed for   finance professionals   involved in front office trading, Forex, futures, equities, derivatives, fixed income, commodities,   energy and power; in summary, anyone for whom   precision market timing is   important.</span></p>
<p><span style="font-family: verdana, geneva; font-size: small;">It is suited for those who have knowledge of technical analysis theory but need a bridge between the books they have read   and     courses they have attended and their job.</span></p>
<p><span style="font-family: verdana, geneva; font-size: small;">More information at&nbsp;<a title="http://www.advancedmarkettiming.com" href="http://www.advancedmarkettiming.com/" target="_blank">http://www.AdvancedMarketTiming.com</a>.</span></p>
<p>&nbsp;</p>
<span style="font-family: verdana, geneva; font-size: small;"> <a title="Advanced Market Timing Experts Workshop 2011" href="http://www.AdvancedMarketTiming.com" target="_blank"><img style="border: 0;" src="http://goldennetworking.net/userfiles/image/Trevor800.jpg" alt="Advanced Market Timing Experts Workshop 2011" width="500" /></a> </span>
<p>&nbsp;</p>
<p><span style="font-family: verdana, geneva; font-size: small;"><strong>Trading and Hedging with Interest Rate and Currency Derivatives</strong></span></p>
<p><span style="font-family: verdana, geneva; font-size: small;">Along the same lines,&nbsp;<a title="Modern Derivatives Trading Experts Workshop 2011" href="http://www.modernderivativestrading.com" target="_blank">Modern   Derivatives Trading Experts Workshop 2011</a>, held in Hong Kong, March 31 &amp; April 1  and&nbsp;led by recognized expert Paul North, will introduce attendees to the different types of money market and FX derivatives,   as well as describe the   characteristics of OTC versus exchange based derivatives. This workshop will:</span></p>
<ul>
<li><span style="font-family: verdana, geneva; font-size: small;">Explain the different types of money market and FX derivatives</span></li>
<li><span style="font-family: verdana, geneva; font-size: small;">Describe the characteristics of OTC versus exchange based derivatives</span></li>
<li><span style="font-family: verdana, geneva; font-size: small;">Show how to price and value different derivative instruments</span></li>
<li><span style="font-family: verdana, geneva; font-size: small;">Provide an explanation on how to hedge market risk</span></li>
<li><span style="font-family: verdana, geneva; font-size: small;">Demonstrate how to spread trade with derivatives</span></li>
</ul>
<p><span style="font-family: verdana, geneva; font-size: small;">More information at <a title="Derivatives Trading Experts Workshop 2011" href="http://www.modernderivativestrading.com" target="_blank">http://www.ModernDerivativesTrading.com</a>.&nbsp;</span></p>
<p>&nbsp;</p>
<p><span style="font-family: verdana, geneva; font-size: small;"><strong>Riding on the emergency of China in the global finance scene</strong></span></p>
<p><span style="font-family: verdana, geneva; font-size: small;">According to The Wall Street Journal, China's currency is emerging as a hot property in global foreign-exchange markets,   just   months after Beijing allowed the yuan   to be bought and sold outside the mainland for the first time. Global trading in yuan allows businesses to buy and sell the   currency to finance trade,   investment and   borrowing.</span></p>
<p><span style="font-family: verdana, geneva; font-size: small;">It's an important step for the yuan to play a role in global financial markets.&nbsp;<a title="Offshore Yuan Trading   Experts   Workshop 2011" href="http://www.OffshoreYuanTrading.com." target="_blank">Offshore Yuan Trading Experts Workshop 2011</a>, Hong Kong, March 28 &amp; 29, will   provide you the tools to   take   advantage of the enormous possibilities yuan trading offers. Experts&nbsp;Frances Cheung and&nbsp;Dariusz Kowalczyk will   cover:</span></p>
<ul>
<li><span style="font-family: verdana, geneva; font-size: small;">The Emergence of the Yuan in the Global Currency Scene</span></li>
<li><span style="font-family: verdana, geneva; font-size: small;">A New World of Investment Opportunities</span></li>
<li><span style="font-family: verdana, geneva; font-size: small;">&ldquo;Dim Sum&rdquo; on the Capital Raising Menu</span></li>
<li><span style="font-family: verdana, geneva; font-size: small;">What the Future Holds for the Yuan in the Currency Markets</span></li>
</ul>
<p><span style="font-family: verdana, geneva; font-size: small;">More information at&nbsp;<a title="Offshore Yuan Trading Experts Workshop 2011" href="http://www.OffshoreYuanTrading.com" target="_blank">http://www.OffshoreYuanTrading.com</a>.</span></p>
<p>&nbsp;</p>
<p><span style="font-family: verdana, geneva; font-size: small;"><strong>Terrific Offer for Modern Finance Report readers</strong></span></p>
<p><span style="font-family: verdana, geneva; font-size: small;">And what is the best part of reading about these great workshops here? <a title="Modern Finance Report" href="http://www.modernfinancereport.com" target="_blank">Modern Finance Report</a> readers will enjoy a 20% discount. The discount code to use is MFR2011 and will   apply to all registrations   completed by Friday March 4, 2011.&nbsp;</span></p>
<p><span style="font-family: verdana, geneva; font-size: small;">So hurry up and take advantage of this extraordinary offer now as the available spots are limited.</span></p>
<p>&nbsp;</p>
<p><span style="font-family: verdana, geneva; font-size: small;">Sincerely,</span></p>
<p><span style="font-family: verdana, geneva; font-size: small;">The&nbsp;<a title="Modern Finance Report" href="http://www.modernfinancereport.com" target="_blank">Modern Finance     Report</a>&nbsp;team</span></p>
</div>
</td>
</tr>
</tbody>
</table>
<div id="branding" style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical-align: baseline;"><a style="border-width: 0px; font-family: inherit; font-style: inherit; font-weight: inherit; margin: 0px; outline-width: 0px; padding: 0px; vertical  -align: baseline; color: #df0000;" title="Offshore Yuan Trading Experts Worskshop 2011" href="http://offshoreyuantrading.com/" target="_blank"><img style="border: 0;" src="http://goldennetworking.net/userfiles/image/OYTHEAD940198.jpg" alt="Offshore Yuan Trading Experts Workshop 2011" width="770" /></a></div>
<p style="text-align: center;"><span style="font-size: xx-small;">If not interested in receiving these communications, please reply with Unsubscribe in the subject   line.<br /> <a title="Modern Finance Report" href="http://modernfinancereport.com" target="_blank">Modern Finance Report</a>, 475 Park Avenue South, New York City, NY, USA </span></p>
<p style="text-align: center; font-size: xx-small;"><span style="color: #999999;">Disclaimer: The information contained in this newsletter does not constitute an offer   or solicitation to   sell any security or fund to or by anyone in any jurisdictions, nor should it be regarded as a contractual document. Under no circumstances should   the information provided on this newsletter   be considered as advice for any investment, or as a sufficient basis on which to make investment decisions. The   information contained herein has been gathered by <a title="Modern Finance   Report" href="http://modernfinancereport.com" target="_blank">Modern Finance Report</a> from sources deemed reliable as of the date of publication, but no warranty of accuracy or completeness   is given. <a title="Modern Finance Report" href="http://modernfinancereport.com" target="_blank">Modern Finance Report</a> is not responsible for and provides no guarantee with respect to any   of the information   prov
 ided herein or through the use of
</div>
</td>
</tr>
</tbody>
</table>
