Return-Path: rolandcleffconsultant@gncn.net
Received: from mx102.stngva01.us.mxservers.net (198.173.112.39)
	by mail19f.g19.rapidsite.net (RS ver 1.0.95vs) with SMTP id 3-0928458223
	for <jayanthi@altechstar.com>; Thu,  7 Apr 2011 10:57:03 -0400 (EDT)
Received: from unknown [219.80.29.172] (EHLO mail.aromate.com)
	by va1-mx102.stngva01.us.mxservers.net (mxl_mta-3.1.0-05)
	with ESMTP id eb0dd9d4.1067449248.836812.00-013.va1-mx102.stngva01.us.mxservers.net (envelope-from <rolandcleff@hotmail.com>);
	Thu, 07 Apr 2011 10:57:02 -0400 (EDT)
Received: by mail.aromate.com (Postfix, from userid 98)
	id 81FF0FDD53A; Thu,  7 Apr 2011 12:37:25 +0800 (CST)
Received: from User (unknown [180.215.179.6])
	by mail.aromate.com (Postfix) with ESMTP id 3BE51FDA9DE;
	Thu,  7 Apr 2011 12:01:27 +0800 (CST)
Reply-To: <rolandcleffconsultant@gncn.net>
From: "MR ROLAND CONSULTANT"<rolandcleff@hotmail.com>
Subject: RELIABLE INDIAN BUSINESS PARTNER NEEDED
Date: Wed, 6 Apr 2011 21:02:10 -0700
MIME-Version: 1.0
Content-Type: text/html;
	charset="Windows-1251"
Content-Transfer-Encoding: 7bit
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2600.0000
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2600.0000
Message-Id: <20110407040129.3BE51FDA9DE@mail.aromate.com>
To: undisclosed-recipients:;
X-Spam: [F=0.2000000000; B=0.500(0); S=0.200(2010122901); MH=0.500(2011040715)]
X-MAIL-FROM: <rolandcleff@hotmail.com>
X-SOURCE-IP: [219.80.29.172]
X-SF-Loop: 1

<HTML><HEAD><TITLE></TITLE>
</HEAD>
<BODY bgcolor=#FFFFFF leftmargin=5 topmargin=5 rightmargin=5 bottommargin=5>
<FONT size=2 color=#000000 face="Arial">
<DIV>
DEAR SIR,</DIV>
<DIV>
MY NAME IS MR. (ROLAND CLEFF ) A BUSINESS CONSULTANT BASED IN LONDON UK.</DIV>
<DIV>
I GOT YOUR ESTEEMED CONTACT DURING MY COMPREHENSIVE SEARCH AT THE CHAMBER</DIV>
<DIV>
OF COMMERCE HERE FOR A RELIABLE AND TRUSTWORTHY INDIVIDUAL / COMPANY IN</DIV>
<DIV>
YOUR COUNTRY.</DIV>
<DIV>
MY PROPOSAL:</DIV>
<DIV>
THERE IS A MULTI-NATIONAL COMPANY BASED IN EUROPE.</DIV>
<DIV>
THIS COMPANY PROCURES MOST OF THEIR RAW MATERIALS FROM YOUR COUNTRY(INDIA)</DIV>
<DIV>
SINCE THE PAST 3 YEARS.THE COMPANY WILL PAY SOME PERCENTAGE UPFRONT UPON</DIV>
<DIV>
VERIFICATION OF THE SAMPLES OF THE MATERIALS.</DIV>
<DIV>
I AM LOOKING FOR A RELIABLE INDIAN BUSINESSMAN THAT UNDERSTANDS THE INDIAN</DIV>
<DIV>
LOCAL LANGUAGE WHO WILL ASSIST ME IN CONTACTING THE LOCAL DEALER OF THESE</DIV>
<DIV>
PRODUCT IN INDIA.</DIV>
<DIV>
I HAVE CALLED THE LOCAL DEALER MANY TIMES, BUT COULD NOT UNDERSTAND THE</DIV>
<DIV>
LOCAL LANGUAGE, TO ENABLE ME NEGOTIATE THE TERMS OF THE SUPPLY WITH THEM.</DIV>
<DIV>
I TRIED MANY TIMES TO SPEAK TO THE LOCAL DEALER, BUT SHE DOES NOT UNDERSTAND</DIV>
<DIV>
ENGLISH OR RATHER MY ACCENT.</DIV>
<DIV>
THIS PROPOSAL IS RISK FREE AND WILL BE ANOTHER INCOME GENERATING BUSINESS</DIV>
<DIV>
OUTSIDE YOUR SPECIALIZATION.</DIV>
<DIV>
I WILL GIVE YOU MORE DETAILS, OF THIS PROPOSALS THE MOMENT I HEAR FROM YOU</DIV>
<DIV>
AND I WILL PERSONALLY COME TO YOUR COUNTRY TO SUPERVISE THE SUPPLY.</DIV>
<DIV>
PLEASE KINDLY SEND YOUR REPLY TO MY PERSONAL EMAIL ID (</DIV>
<DIV>
rolandcleffconsultant@gncn.net )FOR MORE DETAILS.</DIV>
<DIV>
I ANTICIPATE HEARING FROM YOU URGENTLY.</DIV>
<DIV>
BEST REGARDS,</DIV>
<DIV>
(ROLAND CLEFF )</DIV>
<DIV>
SUIT 125, 6th FLOOR,</DIV>
<DIV>
St. GEORGES HOUSE</DIV>
<DIV>
CROYDON</DIV>
<DIV>
SURREY</DIV>
<DIV>
CR9 1NR</DIV>
<DIV>
UK.</DIV>
<DIV>
TEL.&nbsp; +447014243045</DIV>
<DIV>
&nbsp;&nbsp;&nbsp;&nbsp; </DIV>
</FONT>
</BODY></HTML>
