Return-Path: terencmcculleyambassadorterencep@yahoo.in
Received: from mx11.stngva01.us.mxservers.net (204.202.242.100)
	by mail19i.g19.rapidsite.net (RS ver 1.0.95vs) with SMTP id 1-0745982361
	for <jayanthi@altechstar.com>; Sun, 10 Jul 2011 22:46:01 -0400 (EDT)
Received: from unknown [95.167.97.150] (EHLO orton)
	by va1-mx11.stngva01.us.mxservers.net (mxl_mta-3.1.0-05)
	with ESMTP id 9e36a1e4.989854624.766130.00-001.va1-mx11.stngva01.us.mxservers.net (envelope-from <mregojim@yahoo.com>);
	Sun, 10 Jul 2011 22:46:01 -0400 (EDT)
Received: from [82.128.66.152] ([82.128.66.152])
	by orton (Kerio MailServer 6.7.2);
	Mon, 11 Jul 2011 08:05:02 +0700
From: "otchet.oracle" <mregojim@yahoo.com>
Reply-to: terencmcculleyambassadorterencep@yahoo.in
Organization: AMBASSADOR TERENCE P. MCCULLEY 
Subject: [SPAM] FROM UNITED STATE OF AMERICA AMBASSADOR.
X-Mailer: Kerio MailServer 6.7.2 WebMail Mini
To: undisclosed-recipients:;
Message-ID: <20110711080502.d9886910@orton>
Date: Mon, 11 Jul 2011 08:05:02 +0700
X-User-Agent: Opera/9.80 (Windows NT 5.1; U; en) Presto/2.8.131 Version/11.11
MIME-Version: 1.0
Content-Type: text/plain;
	charset="us-ascii"
Content-Transfer-Encoding: quoted-printable
X-Spam-Flag: YES
X-Spam: [F=0.9611650485; B=0.500(0); S=0.200(2010122901); MH=0.990(2011071010)]
X-MAIL-FROM: <mregojim@yahoo.com>
X-SOURCE-IP: [95.167.97.150]
X-SF-Loop: 1

GOOD NEWS!!!=20
US AMBASSADOR TO NIGERIA=20
11 GARKI ROAD ABUJA=20
ABUJA, NIGERIA=20
PLEASE REPLY TO THIS EMAIL-pambassadorterence@yahoo.in


ATTN:=20
MY NAME IS TERENCE PATRICK MCCULLEY, THE NEW UNITED STATES AMBASSADOR TO=
 THE FEDERAL REPUBLIC OF NIGERIA. THE UNITED STATES SENATE HAD CONFIRMED=
 MY NOMINATION ON AUGUST 5 2010, AFTER BEING NOMINATED FOR THIS POSITION=
 BY U.S. PRESIDENT BARACK OBAMA ON JUNE 28, 2010. MY CREDENTIALS AS THE =
NEW AMBASSADOR APPOINTED WERE PRESENTED TO HIS EXCELLENCY PRESIDENT GOOD=
LUCK EBELE JONATHAN AT THE PRESIDENTIAL VILLA IN ABUJA, NIGERIA, ON NOVE=
MBER 2, 2010. I AM A CAREER MEMBER OF THE SENIOR FOREIGN SERVICE WITH TH=
E RANK OF MINISTER-COUNSELOR WHOSE DIPLOMATIC CAREER HAS BEEN SPENT MOST=
LY IN AFRICA OR WORKING ON AFRICA ISSUES. I SERVED MOST RECENTLY AS THE =
DEPUTY CHIEF OF MISSION AT THE U.S EMBASSY IN COPENHAGEN, DENMARK. PRIOR=
 TO THIS, I WAS THE U.S AMBASSADOR TO MALI, AND I HAVE SERVED AS DEPUTY =
CHIEF OF MISSION AT THE U.S EMBASSIES IN TUNISIA, SENEGAL AND TOGO. OTHE=
R OVERSEAS POSTINGS INCLUDES NIGER, SOUTH AFRICA, INDIA AND CHAD.=20
HOWEVER, FOLLOWING THE RESOLUTIONOF THE MEETING HELD WITH HIS EXCELLENCY=
 PRESIDENT GOODLUCK EBELE JONATHAN AT THE PRESIDENTIAL VILLA IN ABUJA YE=
STERDAY WITH SOME MEMBERS OF THE FEDERAL HOUSE OF SENATE, I SHALL BE COM=
ING TO YOUR COUNTRY FOR AN OFFICIAL MEETING ON THURSDAY AND I WILL BE BR=
INGING YOUR FUNDS OF $15.5M ALONG WITH ME BUT THIS TIME I WILL NOT GO TH=
ROUGH CUSTOMS BECAUSE AS AN AMBASSADOR TO NIGERIA, I AM A US GOVERNMENT =
AGENT AND I HAVE THE VETO POWER TO GO THROUGH CUSTOMS. AS SOON AS I AM T=
HROUGH WITH THE MEETING I SHALL THEN PROCEED TO YOUR ADDRESS. (SEND YOUR=
 CELL PHONE NUMBER AND THE ADDRESS WHERE YOU WANT ME TO BRING THE PACKAG=
E).=20

YOU HAVE REALLY PAID SO MUCH IN THIS DELIVERY THAT MAKES ME WONDER. YOU =
ARE A VERY LUCKY PERSON BECAUSE I SHALL BE BRINGING IT MYSELF AND THERE =
IS NOTHING ANYONE CAN DO ABOUT IT.=20

YOUR PACKAGE($15.5M) MUST BE REGISTERED AS AN AMBASSADORIAL PACKAGE FOR =
ME TO DEFEAT ALL ODDS AND THE COST OF REGISTERING IT IS $100 THE FEE MUS=
T BE PAID IN THE NEXT 50 HOURS VIA WESTERN UNION SO THAT ALL NECCESSARY =
ARRANGEMENT CAN BE MADE BEFORE TIME WILL BE AGAINST US.=20

SEND THE FEE VIA WESTERN UNION MONEY TRANSFER OR MONEY GRAM WITH THE PAY=
MENT DETAILS BELOW:=20
SENDER'S NAME:........................=20
RECEIVER'S NAME: OKAFOR MIKE REV
ADDRESS: LAGOS, NIGERIA=20
TEXT QUESTION: GOD IS=20
ANSWER: GOOD
AMOUNT$100=20
MTCN..................................

AS SOON AS YOU SEND THE FEE MAKE SURE YOU SEND ME THE PAYMENT INFORMATIO=
NS FOR EASY PICKUP. MY FLIGHT IS FRIDAY AND I EXPECT YOU TO COMPLY BEFOR=
E THEN SO THAT THE DELIVERY CAN BE COMPLETED. IF YOU DO NOT COMPLY, THEN=
 IT WILL NOT BE MY FAULT IF YOU DO NOT RECEIVE YOUR PACKAGE.=20
OFFICIALLY SIGNED=20

AMBASSADOR TERENCE P. MCCULLEY=20
UNITED STATE OF AMERICA AMBASSADOR.
