Return-Path: madhu@bsmprofessionals.com
Received: from mx111.stngva01.us.mxservers.net (198.173.112.17)
	by mail19d.g19.rapidsite.net (RS ver 1.0.95vs) with SMTP id 3-0216136088
	for <abhra@altechstar.com>; Tue, 15 Feb 2011 13:54:48 -0500 (EST)
Received: from unknown [173.251.33.19] (EHLO bsmprofessionals.com)
	by va1-mx111.stngva01.us.mxservers.net (mxl_mta-3.1.0-05)
	with ESMTP id 7fbca5d4.945109920.1256093.00-007.va1-mx111.stngva01.us.mxservers.net (envelope-from <joseph@bsmprofessionals.com>);
	Tue, 15 Feb 2011 13:54:47 -0500 (EST)
Received: from [192.168.0.60] (account remove HELO IBM3)
  by bsmprofessionals.com (CommuniGate Pro SMTP 5.2.16)
  with ESMTPA id 7143984 for abhra@altechstar.com; Tue, 15 Feb 2011 13:56:26 -0500
From: Madhu Babu (BSM)<madhu@bsmprofessionals.com>
To: <abhra@altechstar.com>
Message-Id: <20110215135518.1133336062@bsmprofessionals.com>
Subject: BSM req:  PeopleSoft  HRMS  Admin  (Chicago, IL)  -  C2C  -  6+ Months
Date: Tue, 15 Feb 2011 13:55:18 -0500
MIME-Version: 1.0
Reply-To: madhu@bsmprofessionals.com
Content-Type: multipart/alternative; boundary="AlternativeBoundary.22222222.22222222"
X-Spam: [F=0.2000000000; B=0.500(0); S=0.200(2010122901); MH=0.500(2011021521)]
X-MAIL-FROM: <joseph@bsmprofessionals.com>
X-SOURCE-IP: [173.251.33.19]
X-Loop-Detect:1

--AlternativeBoundary.22222222.22222222
Content-Type: text/plain; charset="ISO-8859-1"
Content-Transfer-Encoding: 8bit



--AlternativeBoundary.22222222.22222222
Content-Type: text/html; charset="ISO-8859-1"
Content-Transfer-Encoding: 8bit

<HEAD>

</HEAD>
<BODY>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><B style="mso-bidi-font-weight: normal"><FONT size=2><FONT face="Franklin Gothic Medium">Hi <SPAN style="mso-spacerun: yes">&nbsp;</SPAN>,<?xml:namespace prefix = o ns = "urn:schemas-microsoft-com:office:office" /><o:p></o:p></FONT></FONT></B></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></P>
<P>
<TABLE style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; BORDER-COLLAPSE: collapse; BORDER-TOP: medium none; BORDER-RIGHT: medium none; mso-table-layout-alt: fixed; mso-border-top-alt: thin-thick-small-gap; mso-border-left-alt: thin-thick-small-gap; mso-border-bottom-alt: thick-thin-small-gap; mso-border-right-alt: thick-thin-small-gap; mso-border-color-alt: #999999; mso-border-width-alt: 4.5pt; mso-yfti-tbllook: 480; mso-padding-alt: 0in 5.4pt 0in 5.4pt" class=MsoNormalTable border=1 cellSpacing=0 cellPadding=0>
<TBODY>
<TR style="mso-yfti-irow: 0; mso-yfti-firstrow: yes">
<TD style="BORDER-BOTTOM: #d4d0c8; BORDER-LEFT: #999999 4.5pt double; PADDING-BOTTOM: 0in; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 509.4pt; PADDING-RIGHT: 5.4pt; BORDER-TOP: #999999 4.5pt double; BORDER-RIGHT: #d4d0c8; PADDING-TOP: 0in; mso-border-top-alt: thin-thick-small-gap #999999 4.5pt; mso-border-left-alt: thin-thick-small-gap #999999 4.5pt" vAlign=top width=679>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in">Role:</SPAN><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>PeopleSoft <SPAN style="mso-spacerun: yes">&nbsp;</SPAN>HRMS<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Admin </B>(upgrading from Tools release 8.49 to 8.51)<B style="mso-bidi-font-weight: normal"><SPAN style="mso-bidi-font-size: 12.0pt"><o:p></o:p></SPAN></B></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Location:</B><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>Chicago, IL<SPAN style="mso-bidi-font-size: 12.0pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Duration:</B><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>6+ months<SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Rate:</B><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>$ DOE /Hr C2C All inclusive<SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Interview:</B><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>Immediate (Telephonic)<SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal"># of Positions:</B><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>1<SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Start Date: </B><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>Immediate<B style="mso-bidi-font-weight: normal"><o:p></o:p></B></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Client:</B> <SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>Technology Firm<SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN style="FONT-FAMILY: 'Times New Roman'; COLOR: maroon; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><B style="mso-bidi-font-weight: normal"><SPAN style="FONT-FAMILY: 'Times New Roman'; COLOR: maroon; FONT-SIZE: 12pt"><o:p>&nbsp;</o:p></SPAN></B></P></TD>
<TD style="BORDER-BOTTOM: #d4d0c8; BORDER-LEFT: #d4d0c8; PADDING-BOTTOM: 0in; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 189pt; PADDING-RIGHT: 5.4pt; BORDER-TOP: #999999 4.5pt double; BORDER-RIGHT: #999999 4.5pt double; PADDING-TOP: 0in; mso-border-top-alt: thin-thick-small-gap #999999 4.5pt; mso-border-right-alt: thick-thin-small-gap #999999 4.5pt" vAlign=top width=252>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B style="mso-bidi-font-weight: normal"><SPAN style="FONT-FAMILY: 'Arial Black'; COLOR: #333333; FONT-SIZE: 59pt; mso-bidi-font-size: 10.0pt">BS</SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="FONT-FAMILY: 'Arial Black'; COLOR: red; FONT-SIZE: 59pt; mso-bidi-font-size: 10.0pt">M</SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="FONT-FAMILY: 'Arial Black'; FONT-SIZE: 59pt; mso-bidi-font-size: 10.0pt"><o:p></o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B style="mso-bidi-font-weight: normal"><SPAN style="FONT-FAMILY: Verdana; FONT-SIZE: 9pt">Business Success Management</SPAN></B><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></P></TD></TR>
<TR style="HEIGHT: 4pt; mso-yfti-irow: 1">
<TD style="BORDER-BOTTOM: #d4d0c8; BORDER-LEFT: #999999 4.5pt double; PADDING-BOTTOM: 0in; PADDING-LEFT: 5.4pt; WIDTH: 9.7in; PADDING-RIGHT: 5.4pt; BACKGROUND: #ffcc00; HEIGHT: 4pt; BORDER-TOP: #d4d0c8; BORDER-RIGHT: #999999 4.5pt double; PADDING-TOP: 0in; mso-border-left-alt: thin-thick-small-gap #999999 4.5pt; mso-border-right-alt: thick-thin-small-gap #999999 4.5pt" vAlign=top width=931 colSpan=2>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><SPAN style="FONT-FAMILY: Verdana; COLOR: #005500; FONT-SIZE: 1pt; mso-bidi-font-style: italic; mso-no-proof: yes"><o:p>&nbsp;</o:p></SPAN></P></TD></TR>
<TR style="mso-yfti-irow: 2">
<TD style="BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #999999 4.5pt double; PADDING-BOTTOM: 0in; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 509.4pt; PADDING-RIGHT: 5.4pt; BORDER-TOP: #d4d0c8; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0in; mso-border-left-alt: thin-thick-small-gap #999999 4.5pt; mso-border-bottom-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt" vAlign=top width=679>
<P style="TEXT-INDENT: -0.25in; MARGIN: 0in 0in 0pt 0.25in; mso-list: l0 level1 lfo1" class=MsoNormal><SPAN style="FONT-FAMILY: Symbol; FONT-SIZE: 8pt; mso-bidi-font-size: 10.0pt; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol"><SPAN style="mso-list: Ignore">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="mso-bidi-font-family: Arial"><FONT size=2><FONT face="Franklin Gothic Medium">We are in the early stage of a People Tools Upgrade to our Campus Solutions 9.0 system.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>We are upgrading from Tools release 8.49 to 8.51.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><o:p></o:p></FONT></FONT></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN: 0in 0in 0pt 0.25in; mso-list: l0 level1 lfo1" class=MsoNormal><SPAN style="FONT-FAMILY: Symbol; FONT-SIZE: 8pt; mso-bidi-font-size: 10.0pt; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol"><SPAN style="mso-list: Ignore">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="mso-bidi-font-family: Arial"><FONT size=2><FONT face="Franklin Gothic Medium">The project is in need of a<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>PeopleSoft Upgrader to complete the process.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>An important detail of this request is that I would like the consultant to complete the Upgrade tasks but also train staff members on how the Upgrade process works.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Therefore, I would like the consultant to be on site as much as possible.<o:p></o:p></FONT></FONT></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN: 0in 0in 0pt 0.25in; mso-list: l0 level1 lfo1" class=MsoNormal><SPAN style="FONT-FAMILY: Symbol; FONT-SIZE: 8pt; mso-bidi-font-size: 10.0pt; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol"><SPAN style="mso-list: Ignore">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="mso-bidi-font-family: Arial"><FONT size=2><FONT face="Franklin Gothic Medium">Upgrading from Tools 8.49 to 8.51 on CS 9.0 system<o:p></o:p></FONT></FONT></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN: 0in 0in 0pt 0.25in; mso-list: l0 level1 lfo1" class=MsoNormal><SPAN style="FONT-FAMILY: Symbol; FONT-SIZE: 8pt; mso-bidi-font-size: 10.0pt; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol"><SPAN style="mso-list: Ignore">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="mso-bidi-font-family: Arial"><FONT size=2><FONT face="Franklin Gothic Medium">The system is configured as follows:<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Application Servers on AIX 6.1, Web servers use Web Logic on Server 2008 R2, and Schedulers on both AIX and NT.<o:p></o:p></FONT></FONT></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN: 0in 0in 0pt 0.25in; mso-list: l0 level1 lfo1" class=MsoNormal><SPAN style="FONT-FAMILY: Symbol; FONT-SIZE: 8pt; mso-bidi-font-size: 10.0pt; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol"><SPAN style="mso-list: Ignore">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="mso-bidi-font-family: Arial"><FONT size=2><FONT face="Franklin Gothic Medium">The database we are currently on is DB2 9.1, but will be using DB2 9.7 as part of the upgrade.<o:p></o:p></FONT></FONT></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN: 0in 0in 0pt 0.25in; mso-list: l0 level1 lfo1" class=MsoNormal><SPAN style="FONT-FAMILY: Symbol; FONT-SIZE: 8pt; mso-bidi-font-size: 10.0pt; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol"><SPAN style="mso-list: Ignore">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="mso-bidi-font-family: Arial"><FONT size=2><FONT face="Franklin Gothic Medium">The resource would be mainly technical but obviously any help the resource can offer to both Functional and Technical groups will be highly valued.<o:p></o:p></FONT></FONT></SPAN></P>
<P style="TEXT-INDENT: -0.25in; MARGIN: 0in 0in 0pt 0.25in; mso-list: l0 level1 lfo1" class=MsoNormal><SPAN style="FONT-FAMILY: Symbol; FONT-SIZE: 8pt; mso-bidi-font-size: 10.0pt; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol"><SPAN style="mso-list: Ignore">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>Although experience with Campus Solutions 9.0 is not required, it will be highly valued.<o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><FONT size=2><STRONG><SPAN style="FONT-FAMILY: 'Franklin Gothic Medium'; mso-bidi-font-family: Arial">If interested, please reply with matching profiles along with their contact details, rate, availability, current location details</SPAN></STRONG><FONT face="Franklin Gothic Medium"><SPAN style="mso-bidi-font-family: Arial">:</SPAN><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P></TD>
<TD style="BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #d4d0c8; PADDING-BOTTOM: 0in; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 189pt; PADDING-RIGHT: 5.4pt; BORDER-TOP: #d4d0c8; BORDER-RIGHT: #999999 4.5pt double; PADDING-TOP: 0in; mso-border-left-alt: solid windowtext .5pt; mso-border-bottom-alt: solid windowtext .5pt; mso-border-right-alt: thick-thin-small-gap #999999 4.5pt" vAlign=top width=252>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B><SPAN style="FONT-FAMILY: Verdana; COLOR: #005500; mso-bidi-font-style: italic; mso-no-proof: yes"><o:p><FONT size=2>&nbsp;</FONT></o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B><SPAN style="FONT-FAMILY: Verdana; COLOR: #007f3f; FONT-SIZE: 8.5pt">Madhu Babu</SPAN></B><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B><SPAN style="FONT-FAMILY: Verdana; COLOR: #999999; FONT-SIZE: 8.5pt">Sr. Technical Recruiter </SPAN></B><B><SPAN style="FONT-FAMILY: Verdana; COLOR: #993300; FONT-SIZE: 8.5pt; mso-bidi-font-family: Arial"><o:p></o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B><SPAN style="FONT-FAMILY: Verdana; COLOR: red; mso-bidi-font-family: Arial"><FONT size=2>BSM</FONT></SPAN></B><B><SPAN style="FONT-FAMILY: Verdana; FONT-SIZE: 8.5pt; mso-bidi-font-size: 10.0pt; mso-bidi-font-family: Arial"> - </SPAN></B><SPAN style="FONT-FAMILY: Verdana; FONT-SIZE: 8.5pt; mso-bidi-font-weight: bold; mso-bidi-font-size: 10.0pt; mso-bidi-font-family: Arial">“Business Success Management”</SPAN><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: right; TEXT-INDENT: -0.75in; MARGIN: 0in 0in 0pt 0.75in" class=MsoNormal align=right><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><o:p>&nbsp;</o:p></SPAN></P>
<P style="TEXT-ALIGN: right; TEXT-INDENT: -0.75in; MARGIN: 0in 0in 0pt 0.75in" class=MsoNormal align=right><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">732 777 0800 x 511<SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp; </SPAN>-<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Office<o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: right; TEXT-INDENT: -0.75in; MARGIN: 0in 0in 0pt 0.75in" class=MsoNormal align=right><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">732 777 7328<SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp; </SPAN>-<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp;</SPAN>Fax<o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; mso-no-proof: yes"><SPAN style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN>bsm.us.com<SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp; </SPAN>-<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Learn<B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in"><o:p></o:p></SPAN></B></SPAN></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><o:p>&nbsp;</o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">Certified </SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: red; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><FONT size=2>M</FONT></SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">inority &amp; </SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: red; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><FONT size=2>W</FONT></SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">omen Owned<o:p></o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: red; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><FONT size=2>B</FONT></SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">usiness </SPAN></B><?xml:namespace prefix = st1 ns = "urn:schemas-microsoft-com:office:smarttags" /><st1:City w:st="on"><st1:place w:st="on"><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: red; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><FONT size=2>E</FONT></SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">nterprise</SPAN></B></st1:place></st1:City><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><o:p></o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; TEXT-INDENT: -45pt; MARGIN: 0in 0in 0pt 45pt" class=MsoNormal align=right><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><o:p>&nbsp;</o:p></SPAN></P>
<P style="TEXT-ALIGN: right; TEXT-INDENT: -0.75in; MARGIN: 0in 0in 0pt 0.75in" class=MsoNormal align=right><st1:Street w:st="on"><st1:address w:st="on"><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; mso-no-proof: yes">2 Kilmer Road</SPAN></st1:address></st1:Street><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; mso-no-proof: yes"> | <st1:place w:st="on">Edison</st1:place>,<o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; mso-no-proof: yes">NJ –08817 | <st1:place w:st="on"><st1:country-region w:st="on">United States</st1:country-region></st1:place><o:p></o:p></SPAN></P></TD></TR>
<TR style="HEIGHT: 31pt; mso-yfti-irow: 3; mso-yfti-lastrow: yes">
<TD style="BORDER-BOTTOM: #999999 4.5pt double; BORDER-LEFT: #999999 4.5pt double; PADDING-BOTTOM: 0in; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 9.7in; PADDING-RIGHT: 5.4pt; HEIGHT: 31pt; BORDER-TOP: #d4d0c8; BORDER-RIGHT: #999999 4.5pt double; PADDING-TOP: 0in; mso-border-top-alt: solid windowtext .5pt; mso-border-left-alt: thin-thick-small-gap #999999 4.5pt; mso-border-bottom-alt: thick-thin-small-gap #999999 4.5pt; mso-border-right-alt: thick-thin-small-gap #999999 4.5pt" vAlign=top width=931 colSpan=2>
<P style="TEXT-ALIGN: justify; MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="FONT-FAMILY: 'Times New Roman'; COLOR: white; FONT-SIZE: 1pt; mso-bidi-font-family: 'Lucida Sans Unicode'">Hyperion &amp; Essbase , .NET, Sharepoint, Business Analysts, Java/J2EE, Oracle DBA &amp; Developer, PeopleSoft, SAP, Cognos, Informatica, SAS, Crystal Reports &amp; CISCO Admin<o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: justify; MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 7pt; mso-no-proof: yes; mso-bidi-font-family: Arial">The information contained in this e-mail transmission is confidential and may be privileged. It is intended only for the addressee(s) stated above. If you are not an addressee, any use, dissemination, distribution, publication, or copying of the information contained in this e-mail is strictly prohibited. If you have received this e-mail in error, please immediately </SPAN><B><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 7pt; mso-bidi-font-size: 10.0pt; mso-no-proof: yes; mso-bidi-font-family: Arial">notify us by replying to this email with&nbsp;the word "REMOVE" in the subject line. We apologize for inconvenience, if any caused.</SPAN></B><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></P></TD></TR></TBODY></TABLE></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p>&nbsp;</o:p></SPAN></P></BODY>



--AlternativeBoundary.22222222.22222222--

