Return-Path: dilip@bsmprofessionals.com
Received: from mx124.stngva01.us.mxservers.net (198.173.112.53)
	by mail19j.g19.rapidsite.net (RS ver 1.0.95vs) with SMTP id 3-0124942463
	for <abhra@altechstar.com>; Fri, 18 Mar 2011 14:21:03 -0400 (EDT)
Received: from unknown [173.251.33.19] (EHLO bsmprofessionals.com)
	by va1-mx124.stngva01.us.mxservers.net (mxl_mta-3.1.0-05)
	with ESMTP id e82a38d4.2451553184.44441.00-011.va1-mx124.stngva01.us.mxservers.net (envelope-from <joseph@bsmprofessionals.com>);
	Fri, 18 Mar 2011 14:21:02 -0400 (EDT)
Received: from [192.168.0.60] (account dilip HELO IBM3)
  by bsmprofessionals.com (CommuniGate Pro SMTP 5.2.16)
  with ESMTPA id 7913617 for abhra@altechstar.com; Fri, 18 Mar 2011 14:22:46 -0400
From: Dilip Kumar (BSM)<dilip@bsmprofessionals.com>
To: <abhra@altechstar.com>
Message-Id: <20110318142134.584912234@bsmprofessionals.com>
Subject: BSM req:     Java Developer    ( Mountain View, CA ) - C2C - Long Term
Date: Fri, 18 Mar 2011 14:21:34 -0400
MIME-Version: 1.0
Reply-To: dilip@bsmprofessionals.com
Content-Type: multipart/alternative; boundary="AlternativeBoundary.22222222.22222222"
X-Spam: [F=0.2000000000; B=0.500(0); S=0.200(2010122901); MH=0.500(2011031815)]
X-MAIL-FROM: <joseph@bsmprofessionals.com>
X-SOURCE-IP: [173.251.33.19]
X-SF-Loop: 1

--AlternativeBoundary.22222222.22222222
Content-Type: text/plain; charset="ISO-8859-1"
Content-Transfer-Encoding: 8bit



--AlternativeBoundary.22222222.22222222
Content-Type: text/html; charset="ISO-8859-1"
Content-Transfer-Encoding: 8bit

<HEAD>

</HEAD>
<BODY>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><B style="mso-bidi-font-weight: normal"><FONT size=2><FONT face="Franklin Gothic Medium">Hi <SPAN style="mso-spacerun: yes">&nbsp;</SPAN>,<?xml:namespace prefix = o ns = "urn:schemas-microsoft-com:office:office" /><o:p></o:p></FONT></FONT></B></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></P>
<P>
<TABLE style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; BORDER-COLLAPSE: collapse; BORDER-TOP: medium none; BORDER-RIGHT: medium none; mso-table-layout-alt: fixed; mso-border-top-alt: thin-thick-small-gap; mso-border-left-alt: thin-thick-small-gap; mso-border-bottom-alt: thick-thin-small-gap; mso-border-right-alt: thick-thin-small-gap; mso-border-color-alt: #999999; mso-border-width-alt: 4.5pt; mso-yfti-tbllook: 480; mso-padding-alt: 0in 5.4pt 0in 5.4pt" class=MsoNormalTable border=1 cellSpacing=0 cellPadding=0>
<TBODY>
<TR style="mso-yfti-irow: 0; mso-yfti-firstrow: yes">
<TD style="BORDER-BOTTOM: #d4d0c8; BORDER-LEFT: #999999 4.5pt double; PADDING-BOTTOM: 0in; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 509.4pt; PADDING-RIGHT: 5.4pt; BORDER-TOP: #999999 4.5pt double; BORDER-RIGHT: #d4d0c8; PADDING-TOP: 0in; mso-border-top-alt: thin-thick-small-gap #999999 4.5pt; mso-border-left-alt: thin-thick-small-gap #999999 4.5pt" vAlign=top width=679>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in">Role:</SPAN><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>Java Developer</B><B style="mso-bidi-font-weight: normal"><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></B></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Location:</B><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>Mountain View, CA<SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Duration:</B><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>6+ months<SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Rate:</B><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>$ DOE /Hr C2C All inclusive<SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Interview:</B><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>Immediate (Face-Face / Telephonic)<SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal"># of Positions:</B><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>5<SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Start Date: </B><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>Immediate<B style="mso-bidi-font-weight: normal"><o:p></o:p></B></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Client:</B> <SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>Financials<SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN style="FONT-FAMILY: 'Times New Roman'; COLOR: maroon; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><B style="mso-bidi-font-weight: normal"><SPAN style="FONT-FAMILY: 'Times New Roman'; COLOR: maroon; FONT-SIZE: 12pt"><o:p>&nbsp;</o:p></SPAN></B></P></TD>
<TD style="BORDER-BOTTOM: #d4d0c8; BORDER-LEFT: #d4d0c8; PADDING-BOTTOM: 0in; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 189pt; PADDING-RIGHT: 5.4pt; BORDER-TOP: #999999 4.5pt double; BORDER-RIGHT: #999999 4.5pt double; PADDING-TOP: 0in; mso-border-top-alt: thin-thick-small-gap #999999 4.5pt; mso-border-right-alt: thick-thin-small-gap #999999 4.5pt" vAlign=top width=252>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B style="mso-bidi-font-weight: normal"><SPAN style="FONT-FAMILY: 'Arial Black'; COLOR: black; FONT-SIZE: 59pt; mso-bidi-font-size: 10.0pt">BS</SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="FONT-FAMILY: 'Arial Black'; COLOR: red; FONT-SIZE: 59pt; mso-bidi-font-size: 10.0pt">M</SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="FONT-FAMILY: 'Arial Black'; FONT-SIZE: 59pt; mso-bidi-font-size: 10.0pt"><o:p></o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B style="mso-bidi-font-weight: normal"><SPAN style="FONT-FAMILY: Verdana; FONT-SIZE: 9pt">Business Success Management</SPAN></B><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></P></TD></TR>
<TR style="HEIGHT: 4pt; mso-yfti-irow: 1">
<TD style="BORDER-BOTTOM: #d4d0c8; BORDER-LEFT: #999999 4.5pt double; PADDING-BOTTOM: 0in; PADDING-LEFT: 5.4pt; WIDTH: 9.7in; PADDING-RIGHT: 5.4pt; BACKGROUND: #ffcc00; HEIGHT: 4pt; BORDER-TOP: #d4d0c8; BORDER-RIGHT: #999999 4.5pt double; PADDING-TOP: 0in; mso-border-left-alt: thin-thick-small-gap #999999 4.5pt; mso-border-right-alt: thick-thin-small-gap #999999 4.5pt" vAlign=top width=931 colSpan=2>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><SPAN style="FONT-FAMILY: Verdana; COLOR: #005500; FONT-SIZE: 1pt; mso-bidi-font-style: italic; mso-no-proof: yes"><o:p>&nbsp;</o:p></SPAN></P></TD></TR>
<TR style="mso-yfti-irow: 2">
<TD style="BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #999999 4.5pt double; PADDING-BOTTOM: 0in; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 509.4pt; PADDING-RIGHT: 5.4pt; BORDER-TOP: #d4d0c8; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0in; mso-border-left-alt: thin-thick-small-gap #999999 4.5pt; mso-border-bottom-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt" vAlign=top width=679>
<P style="MARGIN: 0in 0in 0pt; mso-layout-grid-align: none" class=MsoNormal><B style="mso-bidi-font-weight: normal"><SPAN style="COLOR: red; mso-bidi-font-family: Calibri; mso-fareast-font-family: Symbol"><FONT face="Franklin Gothic Medium"><FONT size=2>Must Have:<o:p></o:p></FONT></FONT></SPAN></B></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>Description Design and Develop highly scalable and fault-tolerant systems &amp; interfaces using J2EE and open source technologies - specifically Struts/ JAVA/ JSP/ JSF/ Spring/ Ajax/ JQuery/ TagLibs and JDBC · <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>8+ years experience designing and developing Java and JEE applications and struts based web applications using MVC architecture · Analyze requirements and design workflows and database schemas · Be willing to work on both server-side and UI-side modules of MVC architecture (Struts or JSF or Spring) · <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>Expertise in AJAX and AJAX/JavaScript libraries like JQUERY or PROTOTYPE · Extensive experience with Application Server like JBOSS, TomCat, or WebSphere · Design and develop web applications, web services API, java processes, reports, and reporting applications · <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>Lead a team of developers along with being an active member of the team<o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><FONT size=2><STRONG><SPAN style="FONT-FAMILY: 'Franklin Gothic Medium'; mso-bidi-font-family: Arial">If interested, please reply with matching profiles along with their contact details, rate, availability, current location details</SPAN></STRONG><FONT face="Franklin Gothic Medium"><SPAN style="mso-bidi-font-family: Arial">:</SPAN><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P></TD>
<TD style="BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #d4d0c8; PADDING-BOTTOM: 0in; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 189pt; PADDING-RIGHT: 5.4pt; BORDER-TOP: #d4d0c8; BORDER-RIGHT: #999999 4.5pt double; PADDING-TOP: 0in; mso-border-left-alt: solid windowtext .5pt; mso-border-bottom-alt: solid windowtext .5pt; mso-border-right-alt: thick-thin-small-gap #999999 4.5pt" vAlign=top width=252>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B><SPAN style="FONT-FAMILY: Verdana; COLOR: #005500; mso-bidi-font-style: italic; mso-no-proof: yes"><o:p><FONT size=2>&nbsp;</FONT></o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B><SPAN style="FONT-FAMILY: Verdana; COLOR: #007f3f; FONT-SIZE: 8.5pt">Dilip Kumar</SPAN></B><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B><SPAN style="FONT-FAMILY: Verdana; COLOR: #999999; FONT-SIZE: 8.5pt">Sr. Technical Recruiter </SPAN></B><B><SPAN style="FONT-FAMILY: Verdana; COLOR: #993300; FONT-SIZE: 8.5pt; mso-bidi-font-family: Arial"><o:p></o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B><SPAN style="FONT-FAMILY: Verdana; COLOR: red; mso-bidi-font-family: Arial"><FONT size=2>BSM</FONT></SPAN></B><B><SPAN style="FONT-FAMILY: Verdana; FONT-SIZE: 8.5pt; mso-bidi-font-size: 10.0pt; mso-bidi-font-family: Arial"> - </SPAN></B><SPAN style="FONT-FAMILY: Verdana; FONT-SIZE: 8.5pt; mso-bidi-font-weight: bold; mso-bidi-font-size: 10.0pt; mso-bidi-font-family: Arial">“Business Success Management”</SPAN><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: right; TEXT-INDENT: -0.75in; MARGIN: 0in 0in 0pt 0.75in" class=MsoNormal align=right><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><o:p>&nbsp;</o:p></SPAN></P>
<P style="TEXT-ALIGN: right; TEXT-INDENT: -0.75in; MARGIN: 0in 0in 0pt 0.75in" class=MsoNormal align=right><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">732 777 0800 x 507<SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp; </SPAN>-<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Office<o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: right; TEXT-INDENT: -0.75in; MARGIN: 0in 0in 0pt 0.75in" class=MsoNormal align=right><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">732 777 7328<SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp; </SPAN>-<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp;</SPAN>Fax<o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; mso-no-proof: yes"><SPAN style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN>bsm.us.com<SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp; </SPAN>-<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Learn<B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in"><o:p></o:p></SPAN></B></SPAN></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><SPAN style="FONT-FAMILY: Verdana; FONT-SIZE: 8.5pt">http://bsmhotpositions.blogspot.com<o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><o:p>&nbsp;</o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">Certified </SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: red; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><FONT size=2>M</FONT></SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">inority &amp; </SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: red; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><FONT size=2>W</FONT></SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">omen Owned<o:p></o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: red; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><FONT size=2>B</FONT></SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">usiness </SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: red; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><FONT size=2>E</FONT></SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">nterprise<o:p></o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; TEXT-INDENT: -45pt; MARGIN: 0in 0in 0pt 45pt" class=MsoNormal align=right><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><o:p>&nbsp;</o:p></SPAN></P>
<P style="TEXT-ALIGN: right; TEXT-INDENT: -0.75in; MARGIN: 0in 0in 0pt 0.75in" class=MsoNormal align=right><?xml:namespace prefix = st1 ns = "urn:schemas-microsoft-com:office:smarttags" /><st1:Street w:st="on"><st1:address w:st="on"><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; mso-no-proof: yes">2 Kilmer Road</SPAN></st1:address></st1:Street><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; mso-no-proof: yes"> | <st1:place w:st="on">Edison</st1:place>,<o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; mso-no-proof: yes">NJ –08817 | <st1:place w:st="on"><st1:country-region w:st="on">United States</st1:country-region></st1:place><o:p></o:p></SPAN></P></TD></TR>
<TR style="HEIGHT: 31pt; mso-yfti-irow: 3; mso-yfti-lastrow: yes">
<TD style="BORDER-BOTTOM: #999999 4.5pt double; BORDER-LEFT: #999999 4.5pt double; PADDING-BOTTOM: 0in; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 9.7in; PADDING-RIGHT: 5.4pt; HEIGHT: 31pt; BORDER-TOP: #d4d0c8; BORDER-RIGHT: #999999 4.5pt double; PADDING-TOP: 0in; mso-border-top-alt: solid windowtext .5pt; mso-border-left-alt: thin-thick-small-gap #999999 4.5pt; mso-border-bottom-alt: thick-thin-small-gap #999999 4.5pt; mso-border-right-alt: thick-thin-small-gap #999999 4.5pt" vAlign=top width=931 colSpan=2>
<P style="TEXT-ALIGN: justify; MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="FONT-FAMILY: 'Times New Roman'; COLOR: white; FONT-SIZE: 1pt; mso-bidi-font-family: 'Lucida Sans Unicode'">Hyperion &amp; Essbase , .NET, Sharepoint, Business Analysts, Java/J2EE, Oracle DBA &amp; Developer, PeopleSoft, SAP, Cognos, Informatica, SAS, Crystal Reports &amp; CISCO Admin<o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: justify; MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 7pt; mso-no-proof: yes; mso-bidi-font-family: Arial">The information contained in this e-mail transmission is confidential and may be privileged. It is intended only for the addressee(s) stated above. If you are not an addressee, any use, dissemination, distribution, publication, or copying of the information contained in this e-mail is strictly prohibited. If you have received this e-mail in error, please immediately </SPAN><B><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 7pt; mso-bidi-font-size: 10.0pt; mso-no-proof: yes; mso-bidi-font-family: Arial">notify us by replying to this email with&nbsp;the word "REMOVE" in the subject line. We apologize for inconvenience, if any caused.</SPAN></B><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></P></TD></TR></TBODY></TABLE></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p>&nbsp;</o:p></SPAN></P></BODY>



--AlternativeBoundary.22222222.22222222--

