Return-Path: Prashanth@bsmprofessionals.com
Received: from mx116.stngva01.us.mxservers.net (198.173.112.22)
	by mail19h.g19.rapidsite.net (RS ver 1.0.95vs) with SMTP id 1-0232831686
	for <abhra@altechstar.com>; Thu,  9 Jun 2011 11:01:26 -0400 (EDT)
Received: from unknown [173.251.33.19] (EHLO bsmprofessionals.com)
	by va1-mx116.stngva01.us.mxservers.net (mxl_mta-3.1.0-05)
	with ESMTP id 640e0fd4.1603230624.560441.00-003.va1-mx116.stngva01.us.mxservers.net (envelope-from <joseph@bsmprofessionals.com>);
	Thu, 09 Jun 2011 11:01:26 -0400 (EDT)
Received: from [192.168.0.60] (account remove HELO IBM3)
  by bsmprofessionals.com (CommuniGate Pro SMTP 5.2.16)
  with ESMTPA id 9678345 for abhra@altechstar.com; Thu, 09 Jun 2011 10:33:05 -0400
From: Prashanth  |  BSM<Prashanth@bsmprofessionals.com>
To: Friend <abhra@altechstar.com>
Message-Id: <20110609103245.-847550811@bsmprofessionals.com>
Subject: BSM req:   Oracle Apps DBA, TN
Date: Thu, 9 Jun 2011 10:32:45 -0400
MIME-Version: 1.0
Reply-To: Prashanth@bsmprofessionals.com
Content-Type: multipart/alternative; boundary="AlternativeBoundary.22222222.22222222"
X-Spam: [F=0.2000000000; B=0.500(0); S=0.200(2010122901); MH=0.500(2011060919)]
X-MAIL-FROM: <joseph@bsmprofessionals.com>
X-SOURCE-IP: [173.251.33.19]
X-SF-Loop: 1

--AlternativeBoundary.22222222.22222222
Content-Type: text/plain; charset="ISO-8859-1"
Content-Transfer-Encoding: 8bit



--AlternativeBoundary.22222222.22222222
Content-Type: text/html; charset="ISO-8859-1"
Content-Transfer-Encoding: 8bit

<HEAD>

</HEAD>
<BODY>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><B style="mso-bidi-font-weight: normal"><FONT size=2><FONT face="Franklin Gothic Medium">Hi <SPAN style="mso-spacerun: yes">&nbsp;</SPAN>Friend,<?xml:namespace prefix = o ns = "urn:schemas-microsoft-com:office:office" /><o:p></o:p></FONT></FONT></B></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></P>
<P>
<TABLE style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; BORDER-COLLAPSE: collapse; BORDER-TOP: medium none; BORDER-RIGHT: medium none; mso-yfti-tbllook: 480; mso-padding-alt: 0in 5.4pt 0in 5.4pt; mso-border-left-alt: thin-thick-small-gap; mso-border-top-alt: thin-thick-small-gap; mso-table-layout-alt: fixed; mso-border-bottom-alt: thick-thin-small-gap; mso-border-right-alt: thick-thin-small-gap; mso-border-color-alt: #999999; mso-border-width-alt: 4.5pt" class=MsoNormalTable border=1 cellSpacing=0 cellPadding=0>
<TBODY>
<TR style="mso-yfti-irow: 0; mso-yfti-firstrow: yes">
<TD style="BORDER-BOTTOM: #d4d0c8; BORDER-LEFT: #999999 4.5pt double; PADDING-BOTTOM: 0in; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 509.4pt; PADDING-RIGHT: 5.4pt; BORDER-TOP: #999999 4.5pt double; BORDER-RIGHT: #d4d0c8; PADDING-TOP: 0in; mso-border-left-alt: thin-thick-small-gap #999999 4.5pt; mso-border-top-alt: thin-thick-small-gap #999999 4.5pt" vAlign=top width=679>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in">Role:</SPAN><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>Oracle Apps DBA</B><B style="mso-bidi-font-weight: normal"><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></B></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Location:</B><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><?xml:namespace prefix = st1 ns = "urn:schemas-microsoft-com:office:smarttags" /><st1:place w:st="on"><st1:City w:st="on">Memphis</st1:City>, <st1:State w:st="on">TN</st1:State></st1:place><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Duration:</B><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>6+ months<SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Rate:</B><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>$ DOE /Hr C2C All inclusive<SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Interview:</B><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>Immediate (Face-Face / Telephonic)<SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal"># of Positions:</B><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>2<SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Start Date: </B><SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>Immediate<B style="mso-bidi-font-weight: normal"><o:p></o:p></B></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><FONT size=2><FONT face="Franklin Gothic Medium"><B style="mso-bidi-font-weight: normal">Client:</B> <SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN>Technology<SPAN style="mso-tab-count: 1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN><SPAN style="FONT-FAMILY: 'Times New Roman'; COLOR: maroon; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P>
<P style="TEXT-INDENT: -81pt; MARGIN: 0in 0in 0pt 81pt" class=MsoNormal><B style="mso-bidi-font-weight: normal"><SPAN style="FONT-FAMILY: 'Times New Roman'; COLOR: maroon; FONT-SIZE: 12pt"><o:p>&nbsp;</o:p></SPAN></B></P></TD>
<TD style="BORDER-BOTTOM: #d4d0c8; BORDER-LEFT: #d4d0c8; PADDING-BOTTOM: 0in; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 189pt; PADDING-RIGHT: 5.4pt; BORDER-TOP: #999999 4.5pt double; BORDER-RIGHT: #999999 4.5pt double; PADDING-TOP: 0in; mso-border-top-alt: thin-thick-small-gap #999999 4.5pt; mso-border-right-alt: thick-thin-small-gap #999999 4.5pt" vAlign=top width=252>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B style="mso-bidi-font-weight: normal"><SPAN style="FONT-FAMILY: 'Arial Black'; COLOR: black; FONT-SIZE: 59pt; mso-bidi-font-size: 10.0pt">BS</SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="FONT-FAMILY: 'Arial Black'; COLOR: red; FONT-SIZE: 59pt; mso-bidi-font-size: 10.0pt">M</SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="FONT-FAMILY: 'Arial Black'; FONT-SIZE: 59pt; mso-bidi-font-size: 10.0pt"><o:p></o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B style="mso-bidi-font-weight: normal"><SPAN style="FONT-FAMILY: Verdana; FONT-SIZE: 9pt">Business Success Management</SPAN></B><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></P></TD></TR>
<TR style="HEIGHT: 4pt; mso-yfti-irow: 1">
<TD style="BORDER-BOTTOM: #d4d0c8; BORDER-LEFT: #999999 4.5pt double; PADDING-BOTTOM: 0in; PADDING-LEFT: 5.4pt; WIDTH: 9.7in; PADDING-RIGHT: 5.4pt; BACKGROUND: #ffcc00; HEIGHT: 4pt; BORDER-TOP: #d4d0c8; BORDER-RIGHT: #999999 4.5pt double; PADDING-TOP: 0in; mso-border-left-alt: thin-thick-small-gap #999999 4.5pt; mso-border-right-alt: thick-thin-small-gap #999999 4.5pt" vAlign=top width=931 colSpan=2>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><SPAN style="FONT-FAMILY: Verdana; COLOR: #005500; FONT-SIZE: 1pt; mso-no-proof: yes; mso-bidi-font-style: italic"><o:p>&nbsp;</o:p></SPAN></P></TD></TR>
<TR style="mso-yfti-irow: 2">
<TD style="BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #999999 4.5pt double; PADDING-BOTTOM: 0in; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 509.4pt; PADDING-RIGHT: 5.4pt; BORDER-TOP: #d4d0c8; BORDER-RIGHT: windowtext 1pt solid; PADDING-TOP: 0in; mso-border-left-alt: thin-thick-small-gap #999999 4.5pt; mso-border-bottom-alt: solid windowtext .5pt; mso-border-right-alt: solid windowtext .5pt" vAlign=top width=679>
<P style="MARGIN: 0in 0in 0pt; mso-layout-grid-align: none" class=MsoNormal><B style="mso-bidi-font-weight: normal"><SPAN style="COLOR: red; mso-bidi-font-family: Calibri; mso-fareast-font-family: Symbol"><FONT face="Franklin Gothic Medium"><FONT size=2>Must Have:<o:p></o:p></FONT></FONT></SPAN></B></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><B style="mso-bidi-font-weight: normal"><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>Title: Oracle R12 Consultant / Oracle Apps DBA <o:p></o:p></FONT></FONT></SPAN></B></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><B style="mso-bidi-font-weight: normal"><SPAN style="mso-bidi-font-family: Arial"><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></SPAN></B></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><B style="mso-bidi-font-weight: normal"><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>Description: <o:p></o:p></FONT></FONT></SPAN></B></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>Need one DBA (possibly 2) with technical and functional experience to analyze and assist client with upgrading the current Oracle eBusiness Suite R11.5.10.2 to R12.1+ and provide assistance as directed by the DBA team lead. <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><B style="mso-bidi-font-weight: normal"><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>Job Skills / Skill preferences are as follows: <o:p></o:p></FONT></FONT></SPAN></B></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>1. Technical knowledge of Oracle eBusiness Suite Release 12.1+ specifically in the following modules: • Time and Labor • Core Human Resources (including payroll) • Advanced Benefits • Learning Management • Self-Service HR • iRecruitment <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>2. Experience with Oracle eBusiness Suite upgrade of the Oracle eBusiness Suite R12.1 <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>3. Experience with Oracle Database 9i through 11gR1. <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>4. Experience with project planning and preparation for major release upgrades<o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><B style="mso-bidi-font-weight: normal"><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>Job Duties: <o:p></o:p></FONT></FONT></SPAN></B></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>1. Research and apply patches for Oracle eBusiness upgrade. <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>2. Assist with database management duties for 9i – 11g databases. <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>3. Perform compare/contrast analysis <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>4. Provide recommendation for strategic roadmap for upgrading <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>5. Assist in development of a project plan <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>6. Knowledge transfer to existing support team <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>7. Other duties as determined by the team lead <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>8. Troubleshoot and recover down database / eBusiness application systems. Follow contingency plans for each database system (backup, recovery, failover) as needed. <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>9. Analyze and resolve end user and system reported problems. Communicate problems and their resolution to the team. <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>10. Follow and maintain policies and procedures to ensure system availability and keep each system tuned for optimum performance. Monitor the health of each database and the success of each backup. </FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT style="BORDER-BOTTOM: 1px; BORDER-LEFT: 1px; BORDER-TOP: 1px; BORDER-RIGHT: 1px" size=2>11. Enforce standards – documentation, data formats, naming conventions and change control. Follow standardized routine database maintenance procedures across all environments. <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>12. Assist software engineers in query performance tuning as requested. Help identify inefficient queries; suggest alternatives in a constructive manner. <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>13. Write PL/SQL packages and stored procedures as assigned. <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>14. Share 24/7 on call rotation with other team members. <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>15. Perform upgrade of Oracle Applications database from 9i to 11g. <o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><FONT face="Franklin Gothic Medium"><FONT size=2>16. Perform upgrade or Oracle Applications suite from 11.5.10.2. to 12.1+.<o:p></o:p></FONT></FONT></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="mso-bidi-font-family: Arial"><o:p><FONT size=2 face="Franklin Gothic Medium">&nbsp;</FONT></o:p></SPAN></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><FONT size=2><STRONG><SPAN style="FONT-FAMILY: 'Franklin Gothic Medium'; mso-bidi-font-family: Arial">If interested, please reply with matching profiles along with their contact details, rate, availability, current location details</SPAN></STRONG><FONT face="Franklin Gothic Medium"><SPAN style="mso-bidi-font-family: Arial">:</SPAN><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></FONT></FONT></P></TD>
<TD style="BORDER-BOTTOM: windowtext 1pt solid; BORDER-LEFT: #d4d0c8; PADDING-BOTTOM: 0in; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 189pt; PADDING-RIGHT: 5.4pt; BORDER-TOP: #d4d0c8; BORDER-RIGHT: #999999 4.5pt double; PADDING-TOP: 0in; mso-border-left-alt: solid windowtext .5pt; mso-border-bottom-alt: solid windowtext .5pt; mso-border-right-alt: thick-thin-small-gap #999999 4.5pt" vAlign=top width=252>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B><SPAN style="FONT-FAMILY: Verdana; COLOR: #005500; mso-no-proof: yes; mso-bidi-font-style: italic"><o:p><FONT size=2>&nbsp;</FONT></o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B><SPAN style="FONT-FAMILY: Verdana; COLOR: #007f3f; FONT-SIZE: 8.5pt">Prashanth Raju</SPAN></B><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B><SPAN style="FONT-FAMILY: Verdana; COLOR: #999999; FONT-SIZE: 8.5pt">Sr. Technical Recruiter </SPAN></B><B><SPAN style="FONT-FAMILY: Verdana; COLOR: #993300; FONT-SIZE: 8.5pt; mso-bidi-font-family: Arial"><o:p></o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B><SPAN style="FONT-FAMILY: Verdana; COLOR: red; mso-bidi-font-family: Arial"><FONT size=2>BSM</FONT></SPAN></B><B><SPAN style="FONT-FAMILY: Verdana; FONT-SIZE: 8.5pt; mso-bidi-font-size: 10.0pt; mso-bidi-font-family: Arial"> - </SPAN></B><SPAN style="FONT-FAMILY: Verdana; FONT-SIZE: 8.5pt; mso-bidi-font-weight: bold; mso-bidi-font-size: 10.0pt; mso-bidi-font-family: Arial">�Business Success Management�</SPAN><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: right; TEXT-INDENT: -0.75in; MARGIN: 0in 0in 0pt 0.75in" class=MsoNormal align=right><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><o:p>&nbsp;</o:p></SPAN></P>
<P style="TEXT-ALIGN: right; TEXT-INDENT: -0.75in; MARGIN: 0in 0in 0pt 0.75in" class=MsoNormal align=right><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">732 777 0800 x 525<SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp; </SPAN>-<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Office<o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: right; TEXT-INDENT: -0.75in; MARGIN: 0in 0in 0pt 0.75in" class=MsoNormal align=right><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">732 777 7328<SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp; </SPAN>-<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp;</SPAN>Fax<o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; mso-no-proof: yes"><SPAN style="mso-spacerun: yes">&nbsp;&nbsp; </SPAN>bsm.us.com<SPAN style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp; </SPAN>-<SPAN style="mso-spacerun: yes">&nbsp; </SPAN>Learn<B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in"><o:p></o:p></SPAN></B></SPAN></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><SPAN style="FONT-FAMILY: Verdana; FONT-SIZE: 8.5pt">http://bsmhotpositions.blogspot.com<o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><o:p>&nbsp;</o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">Certified </SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: red; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><FONT size=2>M</FONT></SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">inority &amp; </SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: red; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><FONT size=2>W</FONT></SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">omen Owned<o:p></o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: red; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><FONT size=2>B</FONT></SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">usiness </SPAN></B><st1:City w:st="on"><st1:place w:st="on"><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: red; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><FONT size=2>E</FONT></SPAN></B><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes">nterprise</SPAN></B></st1:place></st1:City><B style="mso-bidi-font-weight: normal"><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><o:p></o:p></SPAN></B></P>
<P style="TEXT-ALIGN: right; TEXT-INDENT: -45pt; MARGIN: 0in 0in 0pt 45pt" class=MsoNormal align=right><SPAN style="BORDER-BOTTOM: windowtext 1pt; BORDER-LEFT: windowtext 1pt; PADDING-BOTTOM: 0in; PADDING-LEFT: 0in; PADDING-RIGHT: 0in; FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; BORDER-TOP: windowtext 1pt; BORDER-RIGHT: windowtext 1pt; PADDING-TOP: 0in; mso-border-alt: none windowtext 0in; mso-no-proof: yes"><o:p>&nbsp;</o:p></SPAN></P>
<P style="TEXT-ALIGN: right; TEXT-INDENT: -0.75in; MARGIN: 0in 0in 0pt 0.75in" class=MsoNormal align=right><st1:Street w:st="on"><st1:address w:st="on"><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; mso-no-proof: yes">2 Kilmer Road</SPAN></st1:address></st1:Street><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; mso-no-proof: yes"> | <st1:place w:st="on">Edison</st1:place>,<o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: right; MARGIN: 0in 0in 0pt" class=MsoNormal align=right><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 8.5pt; mso-no-proof: yes">NJ �08817 | <st1:place w:st="on"><st1:country-region w:st="on">United States</st1:country-region></st1:place><o:p></o:p></SPAN></P></TD></TR>
<TR style="HEIGHT: 31pt; mso-yfti-irow: 3; mso-yfti-lastrow: yes">
<TD style="BORDER-BOTTOM: #999999 4.5pt double; BORDER-LEFT: #999999 4.5pt double; PADDING-BOTTOM: 0in; BACKGROUND-COLOR: transparent; PADDING-LEFT: 5.4pt; WIDTH: 9.7in; PADDING-RIGHT: 5.4pt; HEIGHT: 31pt; BORDER-TOP: #d4d0c8; BORDER-RIGHT: #999999 4.5pt double; PADDING-TOP: 0in; mso-border-left-alt: thin-thick-small-gap #999999 4.5pt; mso-border-top-alt: solid windowtext .5pt; mso-border-bottom-alt: thick-thin-small-gap #999999 4.5pt; mso-border-right-alt: thick-thin-small-gap #999999 4.5pt" vAlign=top width=931 colSpan=2>
<P style="TEXT-ALIGN: justify; MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="FONT-FAMILY: 'Times New Roman'; COLOR: white; FONT-SIZE: 1pt; mso-bidi-font-family: 'Lucida Sans Unicode'">Hyperion &amp; Essbase , .NET, Sharepoint, Business Analysts, Java/J2EE, Oracle DBA &amp; Developer, PeopleSoft, SAP, Cognos, Informatica, SAS, Crystal Reports &amp; CISCO Admin<o:p></o:p></SPAN></P>
<P style="TEXT-ALIGN: justify; MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 7pt; mso-no-proof: yes; mso-bidi-font-family: Arial">The information contained in this e-mail transmission is confidential and may be privileged. It is intended only for the addressee(s) stated above. If you are not an addressee, any use, dissemination, distribution, publication, or copying of the information contained in this e-mail is strictly prohibited. If you have received this e-mail in error, please immediately </SPAN><B><SPAN style="FONT-FAMILY: Verdana; COLOR: black; FONT-SIZE: 7pt; mso-bidi-font-size: 10.0pt; mso-no-proof: yes; mso-bidi-font-family: Arial">notify us by replying to this email with&nbsp;the word "REMOVE" in the subject line. We apologize for inconvenience, if any caused.</SPAN></B><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p></o:p></SPAN></P></TD></TR></TBODY></TABLE></P>
<P style="MARGIN: 0in 0in 0pt" class=MsoNormal><SPAN style="FONT-FAMILY: 'Times New Roman'; FONT-SIZE: 12pt"><o:p>&nbsp;</o:p></SPAN></P></BODY>



--AlternativeBoundary.22222222.22222222--

